import type { AbilityDef, AbilityKind, ClassDef, Element, TalentDef } from '../game/types';

const t = (de: string, en: string) => ({ de, en });
const ability = (
  id: string,
  de: string,
  en: string,
  descriptionDe: string,
  descriptionEn: string,
  kind: AbilityKind,
  element: Element,
  power: number,
  range: number,
  cooldown: number,
  cost: number,
  color: string,
): AbilityDef => ({
  id,
  name: t(de, en),
  description: t(descriptionDe, descriptionEn),
  kind,
  element,
  power,
  range,
  cooldown,
  cost,
  color,
});
const talent = (
  id: string,
  de: string,
  en: string,
  descriptionDe: string,
  descriptionEn: string,
  stat: string,
  value: number,
): TalentDef => ({
  id,
  name: t(de, en),
  description: t(descriptionDe, descriptionEn),
  stat,
  value,
});

export const CLASSES: ClassDef[] = [
  {
    id: 'breaker',
    name: t('Brecher', 'Breaker'),
    color: '#d79760',
    sprite: 'warrior',
    hp: 145,
    resource: 100,
    speed: 142,
    power: 22,
    ranged: false,
    description: t(
      'Stehe im Weg. Brich ihre Formation. Ein zäher Nahkämpfer mit Schutz und weit ausholenden Angriffen.',
      'Stand your ground. Break their formation. A resilient melee fighter with shields and sweeping strikes.',
    ),
    lore: t(
      'Du kennst die Traglast jeder Tür. Der Sender kennt nur die Einschaltquote. Heute findest du heraus, welches Gewicht zuerst nachgibt. Deine Kollegen haben dir keinen Orden hinterlassen, aber einen zuverlässigen Abrisshammer.',
      'You know the load limit of every door. The broadcaster only knows viewing figures. Today you find out which weight gives first. Your colleagues left you no medal, but a reliable demolition hammer.',
    ),
    abilities: [
      ability(
        'breaker-ram',
        'Rammschlag',
        'Ram Strike',
        'Stürme nach vorn und taumle getroffene Gegner. Der Anlauf endet an Wänden.',
        'Rush forward and stagger enemies in your path. Walls stop the charge.',
        'dash',
        'stagger',
        1.8,
        136,
        5,
        22,
        '#e5b16b',
      ),
      ability(
        'breaker-shield',
        'Schrottschild',
        'Scrap Shield',
        'Baue eine vorübergehende Barriere aus herumliegenden Teilen.',
        'Assemble a temporary barrier from discarded components.',
        'shield',
        'shield',
        1.6,
        110,
        10,
        28,
        '#bfc2aa',
      ),
      ability(
        'breaker-ground',
        'Bodenbruch',
        'Ground Break',
        'Ein weiter Hammerschlag erschüttert alle Gegner in deiner Nähe.',
        'A broad hammer strike shakes every nearby enemy.',
        'nova',
        'stagger',
        2.2,
        122,
        8,
        30,
        '#c98b56',
      ),
      ability(
        'breaker-provoke',
        'Provokation',
        'Provocation',
        'Markiere nahe Gegner und mache ihre nächsten Treffer leichter abfangbar.',
        'Mark nearby enemies and make their next strikes easier to absorb.',
        'mark',
        'exposed',
        1.1,
        172,
        9,
        20,
        '#d66b58',
      ),
    ],
    ultimate: ability(
      'breaker-ultimate',
      'Abrisskommando',
      'Demolition Crew',
      'Entfessle einen gewaltigen Einschlag. Gegner taumeln; selbst schwere Panzer verlieren ihre Ruhe.',
      'Unleash a massive impact. Enemies stagger; even heavy armour loses its footing.',
      'nova',
      'stagger',
      5,
      214,
      35,
      0,
      '#edc08b',
    ),
    specs: [
      {
        name: t('Bollwerk', 'Bulwark'),
        description: t(
          'Verstärkter Schutz: +12 Rüstung. Halte einen engen Durchgang, statt jedem Treffer auszuweichen.',
          'Reinforced defence: +12 armour. Hold a narrow passage rather than dodge every strike.',
        ),
        stat: 'armor',
        value: 12,
      },
      {
        name: t('Randalierer', 'Riot Maker'),
        description: t(
          '+25 % Schaden. Nutze Taumelfenster zum Angriff, bevor sich die Formation erholt.',
          '+25% damage. Attack during stagger windows before the formation recovers.',
        ),
        stat: 'damage',
        value: 0.25,
      },
    ],
    talents: [
      talent(
        'breaker-t01',
        'Lastverteiler',
        'Load Distributor',
        '+20 maximales Leben. Eine zusätzliche Reserve für lange Räume.',
        '+20 maximum health. An extra reserve for long rooms.',
        'maxHp',
        20,
      ),
      talent(
        'breaker-t02',
        'Stahlrücken',
        'Steel Back',
        '+4 Rüstung. Kleine Treffer verlieren ihre Schärfe.',
        '+4 armour. Small hits lose their edge.',
        'armor',
        4,
      ),
      talent(
        'breaker-t03',
        'Hebelwirkung',
        'Leverage',
        '+8 % Schaden. Triff mit dem ganzen Werkzeug.',
        '+8% damage. Strike with the entire tool.',
        'damage',
        0.08,
      ),
      talent(
        'breaker-t04',
        'Ruhiger Puls',
        'Steady Pulse',
        '+1,2 Ressource pro Sekunde. Zwischen zwei Wellen findest du Luft.',
        '+1.2 resource per second. Find your breath between waves.',
        'regen',
        1.2,
      ),
      talent(
        'breaker-t05',
        'Stoßreserve',
        'Impact Reserve',
        '+15 maximale Ressource. Platz für einen weiteren Rammschlag.',
        '+15 maximum resource. Room for another Ram Strike.',
        'maxResource',
        15,
      ),
      talent(
        'breaker-t06',
        'Schichtwechsel',
        'Shift Change',
        '+8 % kürzere Abklingzeiten. Schutz und Druck bleiben verfügbar.',
        '8% shorter cooldowns. Keep defence and pressure available.',
        'cooldown',
        0.08,
      ),
      talent(
        'breaker-t07',
        'Arbeitsstiefel',
        'Work Boots',
        '+6 % Bewegungstempo. Schwere Ausrüstung hält dich nicht auf.',
        '+6% movement speed. Heavy equipment will not stop you.',
        'speed',
        0.06,
      ),
      talent(
        'breaker-t08',
        'Unbeugsam',
        'Unbending',
        '+25 maximales Leben. Bleib stehen, wenn andere weichen.',
        '+25 maximum health. Stand when others yield.',
        'maxHp',
        25,
      ),
      talent(
        'breaker-t09',
        'Sollbruchstelle',
        'Fracture Point',
        '+6 % kritische Trefferchance. Du siehst die Naht im Panzer.',
        '+6% critical chance. You see the seam in the armour.',
        'crit',
        0.06,
      ),
      talent(
        'breaker-t10',
        'Aus der Tiefe',
        'From the Depths',
        '+4 % Lebensraub. Jeder erfolgreiche Treffer holt etwas zurück.',
        '+4% life steal. Every successful strike takes something back.',
        'lifesteal',
        0.04,
      ),
    ],
  },
  {
    id: 'sparkweaver',
    name: t('Funkenweber', 'Sparkweaver'),
    color: '#8ce2b7',
    sprite: 'sorceress',
    hp: 96,
    resource: 130,
    speed: 155,
    power: 19,
    ranged: true,
    description: t(
      'Lenke Feuer, Frost und Strom. Halte Gruppen auf Abstand und kombiniere Elemente mit dem Boden.',
      'Direct fire, frost and electricity. Keep groups at range and combine elements with the ground.',
    ),
    lore: t(
      'Jede Leitung in der Tiefe trägt Energie und Daten. Du hast gelernt, den Unterschied zu fühlen. Wer dich einen Zauberer nennt, hat noch nie einen Sicherungskasten ohne Kennzeichnung geöffnet.',
      'Every cable in the depths carries energy and data. You learned to feel the difference. Anyone calling you a wizard has never opened an unlabelled fuse box.',
    ),
    abilities: [
      ability(
        'sparkweaver-arc',
        'Lichtbogen',
        'Arc Flash',
        'Schieße einen elektrischen Bogen. Nasse Gruppen bieten das beste Ziel.',
        'Fire an electric arc. Wet groups make the best target.',
        'projectile',
        'shock',
        1.7,
        332,
        4,
        18,
        '#8ce2b7',
      ),
      ability(
        'sparkweaver-frost',
        'Frostanker',
        'Frost Anchor',
        'Setze ein Frostfeld, das herankommende Gegner verlangsamt.',
        'Place a frost field to slow approaching enemies.',
        'trap',
        'frost',
        1.4,
        146,
        8,
        26,
        '#8cc9e2',
      ),
      ability(
        'sparkweaver-fire',
        'Brandknoten',
        'Fire Knot',
        'Entzünde deine Umgebung. Brennende Ziele nehmen weiteren Schaden.',
        'Ignite your surroundings. Burning targets take continuing damage.',
        'nova',
        'fire',
        2,
        138,
        8,
        30,
        '#dc8b55',
      ),
      ability(
        'sparkweaver-exchange',
        'Energietausch',
        'Energy Exchange',
        'Leite überschüssige Energie in eine sofortige Heilung um.',
        'Convert excess energy into immediate healing.',
        'heal',
        'shield',
        1.7,
        100,
        14,
        32,
        '#b0e7c7',
      ),
    ],
    ultimate: ability(
      'sparkweaver-ultimate',
      'Netzüberlastung',
      'Grid Overload',
      'Ein weitreichender Schockpuls trifft das gesamte nahe Netz.',
      'A far-reaching shock pulse strikes the entire nearby grid.',
      'nova',
      'shock',
      4.8,
      240,
      35,
      0,
      '#b7fff1',
    ),
    specs: [
      {
        name: t('Leiter', 'Conductor'),
        description: t(
          '+25 % Elementarschaden. Leitfähige Gegner sind dein Weg durch große Formationen.',
          '+25% elemental damage. Conductive enemies are your path through large formations.',
        ),
        stat: 'elemental',
        value: 0.25,
      },
      {
        name: t('Wärmesenke', 'Heat Sink'),
        description: t(
          '+3 Ressource pro Sekunde. Baue Frostzonen und halte deinen Kreislauf stabil.',
          '+3 resource per second. Build frost zones and keep your cycle stable.',
        ),
        stat: 'regen',
        value: 3,
      },
    ],
    talents: [
      talent(
        'sparkweaver-t01',
        'Isolierung',
        'Insulation',
        '+15 maximales Leben. Auch Stromkundige machen Fehler.',
        '+15 maximum health. Even electricians make mistakes.',
        'maxHp',
        15,
      ),
      talent(
        'sparkweaver-t02',
        'Zusatzkondensator',
        'Extra Capacitor',
        '+20 maximale Ressource. Mehr Energie vor der nächsten Pause.',
        '+20 maximum resource. More energy before the next pause.',
        'maxResource',
        20,
      ),
      talent(
        'sparkweaver-t03',
        'Leitfähigkeit',
        'Conductivity',
        '+10 % Elementarschaden. Leite die Energie ins Ziel.',
        '+10% elemental damage. Conduct energy into your target.',
        'elemental',
        0.1,
      ),
      talent(
        'sparkweaver-t04',
        'Kälterücklauf',
        'Cold Return',
        '+1,5 Ressource pro Sekunde. Ein geschlossener Kreislauf verschwendet nichts.',
        '+1.5 resource per second. A closed circuit wastes nothing.',
        'regen',
        1.5,
      ),
      talent(
        'sparkweaver-t05',
        'Serienfeuer',
        'Series Circuit',
        '+7 % kürzere Abklingzeiten. Deine Elemente greifen schneller ineinander.',
        '7% shorter cooldowns. Your elements mesh more quickly.',
        'cooldown',
        0.07,
      ),
      talent(
        'sparkweaver-t06',
        'Leichte Erdung',
        'Light Grounding',
        '+7 % Bewegungstempo. Wechsle den Pol, bevor sie dich erreichen.',
        '+7% movement speed. Change poles before they reach you.',
        'speed',
        0.07,
      ),
      talent(
        'sparkweaver-t07',
        'Lichtnadel',
        'Light Needle',
        '+6 % kritische Trefferchance. Kleine Öffnungen genügen.',
        '+6% critical chance. Small openings are enough.',
        'crit',
        0.06,
      ),
      talent(
        'sparkweaver-t08',
        'Doppelte Sicherung',
        'Double Fuse',
        '+3 Rüstung. Ein Rückschlag soll nicht das Ende sein.',
        '+3 armour. A backlash should not be the end.',
        'armor',
        3,
      ),
      talent(
        'sparkweaver-t09',
        'Pulsheilung',
        'Pulse Healing',
        '+15 % Heilwirkung. Erholung wird Teil des Stromkreises.',
        '+15% healing. Recovery becomes part of the circuit.',
        'healing',
        0.15,
      ),
      talent(
        'sparkweaver-t10',
        'Freies Netz',
        'Free Grid',
        '+12 % Elementarschaden. Die Leitung gehört niemandem.',
        '+12% elemental damage. Nobody owns the circuit.',
        'elemental',
        0.12,
      ),
    ],
  },
  {
    id: 'shade-runner',
    name: t('Schattengänger', 'Shade Runner'),
    color: '#bba9d2',
    sprite: 'necromancer',
    hp: 105,
    resource: 110,
    speed: 177,
    power: 23,
    ranged: false,
    description: t(
      'Lies den Angriff. Wechsle die Seite. Ein schneller Duellant für kritische Treffer und sichere Flanken.',
      'Read the attack. Change sides. A fast duellist built for critical hits and safe flanking.',
    ),
    lore: t(
      'Du hast die Kulissenwege repariert, die kein Zuschauer sehen darf. Hinter jeder prachtvollen Tür liegt ein schmaler Wartungsgang. Hinter jedem unbesiegbaren Star liegt ein Mensch, der kurz blinzelt.',
      'You repaired the backstage routes no viewer may see. Behind every grand door lies a narrow maintenance passage. Behind every invincible star lies a person who briefly blinks.',
    ),
    abilities: [
      ability(
        'shade-backstab',
        'Rückenstich',
        'Backstab',
        'Ein gezielter Stich trifft hart und legt das Ziel kurz offen.',
        'A precise stab hits hard and briefly exposes the target.',
        'strike',
        'exposed',
        2.4,
        92,
        4,
        18,
        '#d3bfe5',
      ),
      ability(
        'shade-step',
        'Nebeltritt',
        'Mist Step',
        'Springe durch die Flanke und entziehe dich einer angekündigten Linie.',
        'Slip across the flank and escape a telegraphed line.',
        'dash',
        'physical',
        1.2,
        164,
        5,
        22,
        '#b9b4d5',
      ),
      ability(
        'shade-thread',
        'Fadenschnitt',
        'Thread Cut',
        'Eine breite Klinge verursacht Blutung in deiner unmittelbaren Nähe.',
        'A broad blade inflicts bleeding in your immediate vicinity.',
        'nova',
        'bleed',
        1.8,
        112,
        8,
        25,
        '#b86b83',
      ),
      ability(
        'shade-decoy',
        'Köderbild',
        'Decoy Image',
        'Ein schattenhafter Schutz nimmt den nächsten Druck von dir.',
        'A shadowy shield absorbs the next wave of pressure.',
        'shield',
        'shield',
        1.2,
        90,
        12,
        25,
        '#9c93be',
      ),
    ],
    ultimate: ability(
      'shade-ultimate',
      'Schwarzer Schnitt',
      'Black Cut',
      'Schneide durch eine große Zone und verwunde jede getroffene Silhouette.',
      'Cut through a wide area and wound every silhouette it catches.',
      'nova',
      'bleed',
      5.2,
      204,
      35,
      0,
      '#dabfea',
    ),
    specs: [
      {
        name: t('Duellant', 'Duellist'),
        description: t(
          '+15 % kritische Trefferchance. Nutze kurze Öffnungen statt langer Schlagfolgen.',
          '+15% critical chance. Exploit short openings rather than long combinations.',
        ),
        stat: 'crit',
        value: 0.15,
      },
      {
        name: t('Saboteur', 'Saboteur'),
        description: t(
          '+20 % Bewegungstempo. Platziere dich neu und führe Gruppen durch Engstellen.',
          '+20% movement speed. Reposition and lead groups through choke points.',
        ),
        stat: 'speed',
        value: 0.2,
      },
    ],
    talents: [
      talent(
        'shade-t01',
        'Leiser Schritt',
        'Quiet Step',
        '+8 % Bewegungstempo. Du erreichst zuerst die Flanke.',
        '+8% movement speed. Reach the flank first.',
        'speed',
        0.08,
      ),
      talent(
        'shade-t02',
        'Offene Naht',
        'Open Seam',
        '+6 % kritische Trefferchance. Du findest den ungeschützten Übergang.',
        '+6% critical chance. Find the unguarded seam.',
        'crit',
        0.06,
      ),
      talent(
        'shade-t03',
        'Letzter Atem',
        'Last Breath',
        '+15 maximales Leben. Ein knapper Fehler muss überlebbar bleiben.',
        '+15 maximum health. A close mistake should be survivable.',
        'maxHp',
        15,
      ),
      talent(
        'shade-t04',
        'Drahtgriff',
        'Wire Grip',
        '+8 % Schaden. Ruhige Hände führen scharfe Klingen.',
        '+8% damage. Steady hands guide sharp blades.',
        'damage',
        0.08,
      ),
      talent(
        'shade-t05',
        'Abstand halten',
        'Keep Distance',
        '+8 % kürzere Ausweich-Erholung. Deine nächste Bewegung kommt früher.',
        '8% faster dodge recovery. Your next movement comes sooner.',
        'dodge',
        0.08,
      ),
      talent(
        'shade-t06',
        'Ersatzfaden',
        'Spare Thread',
        '+15 maximale Ressource. Reserve für den Rückzug.',
        '+15 maximum resource. A reserve for retreat.',
        'maxResource',
        15,
      ),
      talent(
        'shade-t07',
        'Schattenruhe',
        'Shadow Rest',
        '+1,5 Ressource pro Sekunde. Warte einen Schlag, gewinne den nächsten.',
        '+1.5 resource per second. Wait for one strike, win the next.',
        'regen',
        1.5,
      ),
      talent(
        'shade-t08',
        'Verlorene Sekunde',
        'Lost Second',
        '+7 % kürzere Abklingzeiten. Lasse keine Öffnung verstreichen.',
        '7% shorter cooldowns. Let no opening pass.',
        'cooldown',
        0.07,
      ),
      talent(
        'shade-t09',
        'Rückforderung',
        'Reclamation',
        '+4 % Lebensraub. Die Verletzung des Gegners wird deine Reserve.',
        '+4% life steal. Your enemy’s wound becomes your reserve.',
        'lifesteal',
        0.04,
      ),
      talent(
        'shade-t10',
        'Keine Wiederholung',
        'No Retake',
        '+10 % Schaden. Beende die Aufnahme beim ersten Versuch.',
        '+10% damage. Finish the recording in one take.',
        'damage',
        0.1,
      ),
    ],
  },
  {
    id: 'scrapper',
    name: t('Schrottmeister', 'Scrapper'),
    color: '#e5b16b',
    sprite: 'warrior',
    hp: 122,
    resource: 120,
    speed: 148,
    power: 18,
    ranged: true,
    description: t(
      'Stelle Fallen und Geschütze auf. Ein erfinderischer Fernkämpfer, der den Raum vor dem Gegner versteht.',
      'Deploy traps and turrets. An inventive ranged fighter who understands the room before the enemy does.',
    ),
    lore: t(
      'Die Gilde nennt es Abfall. Du nennst es eine unvollständige Lösung. Deine ersten Geräte liefen mit gestohlenen Batterien; das letzte könnte mit der gesamten Sendung laufen.',
      'The guild calls it waste. You call it an unfinished solution. Your first devices ran on stolen batteries; the last might run on the entire broadcast.',
    ),
    abilities: [
      ability(
        'scrapper-mines',
        'Minenkranz',
        'Mine Wreath',
        'Lege ein sprengendes Feld an deinem Standort. Locke Gegner in den Radius.',
        'Place an explosive field at your position. Lure enemies into its radius.',
        'trap',
        'fire',
        2.1,
        128,
        8,
        25,
        '#d9a463',
      ),
      ability(
        'scrapper-turret',
        'Geschützturm',
        'Turret',
        'Baue ein Geschütz, das für kurze Zeit selbstständig auf nahe Ziele schießt.',
        'Build a turret that automatically fires at nearby targets for a short time.',
        'turret',
        'physical',
        1.2,
        280,
        12,
        35,
        '#d7c69e',
      ),
      ability(
        'scrapper-magnet',
        'Magnetzug',
        'Magnetic Pull',
        'Ein Magnetpuls legt nahe Ziele offen und bereitet die nächste Salve vor.',
        'A magnetic pulse exposes nearby targets and prepares your next volley.',
        'mark',
        'exposed',
        1.3,
        170,
        8,
        20,
        '#83cbc5',
      ),
      ability(
        'scrapper-repair',
        'Reparaturpuls',
        'Repair Pulse',
        'Flicke deine Ausrüstung und dein Leben mit einem schnellen Wartungspuls.',
        'Patch your equipment and health with a quick maintenance pulse.',
        'heal',
        'shield',
        1.8,
        110,
        14,
        30,
        '#afc89e',
      ),
    ],
    ultimate: ability(
      'scrapper-ultimate',
      'Schrottsturm',
      'Scrap Storm',
      'Sprenge eine ganze Bauteilladung in den Raum. Brennende Splitter treffen eine große Fläche.',
      'Blast a whole load of components across the room. Burning fragments strike a wide area.',
      'nova',
      'fire',
      4.8,
      224,
      35,
      0,
      '#f0c28c',
    ),
    specs: [
      {
        name: t('Konstrukteur', 'Constructor'),
        description: t(
          '+20 % kürzere Abklingzeiten. Dein nächstes Gerät ist bereit, bevor das alte verstummt.',
          '20% shorter cooldowns. Your next device is ready before the old one falls silent.',
        ),
        stat: 'cooldown',
        value: 0.2,
      },
      {
        name: t('Plünderer', 'Scavenger'),
        description: t(
          '+35 % Schrottgewinn. Nutze Funde für neue Geräte und mutige Werkstattumbauten.',
          '+35% scrap income. Turn finds into new devices and bold workshop upgrades.',
        ),
        stat: 'gold',
        value: 0.35,
      },
    ],
    talents: [
      talent(
        'scrapper-t01',
        'Doppelte Tasche',
        'Double Pocket',
        '+20 maximale Ressource. Ein weiteres Gerät im Gepäck.',
        '+20 maximum resource. Carry one more device.',
        'maxResource',
        20,
      ),
      talent(
        'scrapper-t02',
        'Werkzeugstahl',
        'Tool Steel',
        '+4 Rüstung. Ersatzteile taugen auch als Schutz.',
        '+4 armour. Spare parts also make good protection.',
        'armor',
        4,
      ),
      talent(
        'scrapper-t03',
        'Sortierter Schrott',
        'Sorted Scrap',
        '+15 % Schrottgewinn. Erkenne das wertvolle Bauteil.',
        '+15% scrap income. Spot the valuable component.',
        'gold',
        0.15,
      ),
      talent(
        'scrapper-t04',
        'Kurzer Aufbau',
        'Quick Assembly',
        '+8 % kürzere Abklingzeiten. Weniger Schrauben, gleiche Haltbarkeit.',
        '8% shorter cooldowns. Fewer screws, same durability.',
        'cooldown',
        0.08,
      ),
      talent(
        'scrapper-t05',
        'Feldreparatur',
        'Field Repair',
        '+15 % Heilwirkung. Dein Werkzeug braucht keinen OP.',
        '+15% healing. Your tools need no operating theatre.',
        'healing',
        0.15,
      ),
      talent(
        'scrapper-t06',
        'Spannungsreserve',
        'Voltage Reserve',
        '+1,5 Ressource pro Sekunde. Leere Batterien sind nur ein Zwischenzustand.',
        '+1.5 resource per second. Empty batteries are a temporary state.',
        'regen',
        1.5,
      ),
      talent(
        'scrapper-t07',
        'Mehr Splitter',
        'More Fragments',
        '+8 % Schaden. Auch kleine Teile finden eine Aufgabe.',
        '+8% damage. Even small parts have a purpose.',
        'damage',
        0.08,
      ),
      talent(
        'scrapper-t08',
        'Stoßfest',
        'Impact Resistant',
        '+20 maximales Leben. Deine Jacke hat eine zweite Innenschicht.',
        '+20 maximum health. Your jacket has a second lining.',
        'maxHp',
        20,
      ),
      talent(
        'scrapper-t09',
        'Rollwerkzeug',
        'Rolling Tools',
        '+6 % Bewegungstempo. Alles Wichtige passt auf einen Wagen.',
        '+6% movement speed. Everything important fits on a trolley.',
        'speed',
        0.06,
      ),
      talent(
        'scrapper-t10',
        'Prototyp NIX',
        'NIX Prototype',
        '+25 % NIX-Schaden. Der Schakal bekommt bessere Zähne.',
        '+25% NIX damage. The jackal gets better teeth.',
        'nix',
        0.25,
      ),
    ],
  },
  {
    id: 'pact-warden',
    name: t('Vertragshüter', 'Pact Warden'),
    color: '#87b6a2',
    sprite: 'necromancer',
    hp: 132,
    resource: 110,
    speed: 145,
    power: 20,
    ranged: false,
    description: t(
      'Schütze, verfluche und fordere zurück. Ein kontrollierter Kämpfer, der gegnerische Stärke in Schulden verwandelt.',
      'Protect, curse and reclaim. A measured fighter who turns enemy strength into debt.',
    ),
    lore: t(
      'Ein Vertrag bindet nur, solange niemand die widersprüchliche Klausel liest. Du hast lange genug die Regeln des Konsortiums geprüft. Jetzt nimmst du sie beim Wort.',
      'A contract binds only while nobody reads its contradictory clause. You spent enough years checking the Consortium’s rules. Now you take them at their word.',
    ),
    abilities: [
      ability(
        'pact-seal',
        'Schutzsiegel',
        'Protective Seal',
        'Ein Vertrag aus Licht absorbiert Schaden, bevor dein Leben betroffen ist.',
        'A contract of light absorbs damage before it reaches your health.',
        'shield',
        'shield',
        1.7,
        120,
        9,
        25,
        '#a2d1b8',
      ),
      ability(
        'pact-debt',
        'Schuldenmal',
        'Debt Mark',
        'Belege ein Ziel und seine Nachbarn mit einem verletzlichen Schuldenmal.',
        'Place a vulnerable debt mark on a target and its neighbours.',
        'curse',
        'exposed',
        1.4,
        178,
        7,
        22,
        '#b8ad78',
      ),
      ability(
        'pact-life',
        'Lebenspfand',
        'Life Pledge',
        'Fordere gebundene Energie als Heilung zurück.',
        'Reclaim bound energy as healing.',
        'heal',
        'shield',
        2.1,
        118,
        14,
        32,
        '#b2dbb5',
      ),
      ability(
        'pact-circle',
        'Bannkreis',
        'Binding Circle',
        'Ein Bannfeld verursacht Korrosion und macht schwere Rüstung angreifbar.',
        'A binding field causes corrosion and leaves heavy armour vulnerable.',
        'trap',
        'corrosion',
        1.5,
        148,
        10,
        28,
        '#81b48a',
      ),
    ],
    ultimate: ability(
      'pact-ultimate',
      'Vertragsbruch',
      'Breach of Contract',
      'Zerreiße den Schutzvertrag aller nahen Ziele. Ein großer Korrosionspuls schlägt zurück.',
      'Tear apart the protection contracts of all nearby targets. A great corrosive pulse strikes back.',
      'nova',
      'corrosion',
      4.6,
      232,
      35,
      0,
      '#d3e1ba',
    ),
    specs: [
      {
        name: t('Hüter', 'Guardian'),
        description: t(
          '+30 % Heilwirkung. Schaffe genug Sicherheit für einen überlegten nächsten Schritt.',
          '+30% healing. Create enough safety for a considered next step.',
        ),
        stat: 'healing',
        value: 0.3,
      },
      {
        name: t('Vollstrecker', 'Enforcer'),
        description: t(
          '+10 % Lebensraub. Nutze offensive Treffer, um den Preis deines Angriffs zurückzufordern.',
          '+10% life steal. Use offensive hits to reclaim the price of your attack.',
        ),
        stat: 'lifesteal',
        value: 0.1,
      },
    ],
    talents: [
      talent(
        'pact-t01',
        'Bindende Zeile',
        'Binding Line',
        '+15 maximale Ressource. Ein Absatz mehr kann den Vertrag ändern.',
        '+15 maximum resource. One more paragraph can change the contract.',
        'maxResource',
        15,
      ),
      talent(
        'pact-t02',
        'Unterschutz',
        'Under Protection',
        '+4 Rüstung. Die erste Klausel schützt den Träger.',
        '+4 armour. The first clause protects the bearer.',
        'armor',
        4,
      ),
      talent(
        'pact-t03',
        'Gegenseitigkeit',
        'Reciprocity',
        '+3 % Lebensraub. Eine Forderung verlangt Gegenleistung.',
        '+3% life steal. Every claim demands something in return.',
        'lifesteal',
        0.03,
      ),
      talent(
        'pact-t04',
        'Schonfrist',
        'Grace Period',
        '+20 maximales Leben. Niemand stirbt vor der Verhandlung.',
        '+20 maximum health. Nobody dies before negotiations.',
        'maxHp',
        20,
      ),
      talent(
        'pact-t05',
        'Wiederaufnahme',
        'Reopening',
        '+8 % kürzere Abklingzeiten. Ein Verfahren darf wieder aufgerufen werden.',
        '8% shorter cooldowns. A case may be reopened.',
        'cooldown',
        0.08,
      ),
      talent(
        'pact-t06',
        'Gute Versorgung',
        'Good Provision',
        '+15 % Heilwirkung. Schutz ist mehr als ein Versprechen.',
        '+15% healing. Protection is more than a promise.',
        'healing',
        0.15,
      ),
      talent(
        'pact-t07',
        'Freie Klausel',
        'Free Clause',
        '+10 % Elementarschaden. Auch Korrosion kennt eine Rechtsgrundlage.',
        '+10% elemental damage. Even corrosion has a legal basis.',
        'elemental',
        0.1,
      ),
      talent(
        'pact-t08',
        'Widerspruch',
        'Objection',
        '+8 % Schaden. Eine knappe Antwort darf scharf sein.',
        '+8% damage. A brief reply may be sharp.',
        'damage',
        0.08,
      ),
      talent(
        'pact-t09',
        'Ausgleich',
        'Settlement',
        '+1,5 Ressource pro Sekunde. Ein sauberer Abschluss gibt Kraft zurück.',
        '+1.5 resource per second. A clean settlement restores strength.',
        'regen',
        1.5,
      ),
      talent(
        'pact-t10',
        'Eigenes Recht',
        'Your Own Right',
        '+25 maximales Leben. Dein Wert steht in keinem Formular.',
        '+25 maximum health. Your worth is in no form.',
        'maxHp',
        25,
      ),
    ],
  },
  {
    id: 'trail-hunter',
    name: t('Spurenjäger', 'Trail Hunter'),
    color: '#89bcc1',
    sprite: 'skeleton-hunter',
    hp: 108,
    resource: 115,
    speed: 164,
    power: 21,
    ranged: true,
    description: t(
      'Markiere dein Ziel und halte Abstand. Präzise Salven, Fangdrähte und ein verlässlicher Partner auf vier Pfoten.',
      'Mark your target and keep your distance. Precise volleys, tripwires and a reliable four-legged partner.',
    ),
    lore: t(
      'Während die Show nach vorn schaut, liest du, was sie zurückgelassen hat. Ein abgerissener Draht, ein Schakalabdruck, ein Atemzug hinter einer Wand. Jede Spur ist eine Antwort, wenn man ihr Zeit gibt.',
      'While the show looks ahead, you read what it left behind. A torn wire, a jackal print, a breath behind a wall. Every trace is an answer if given time.',
    ),
    abilities: [
      ability(
        'hunter-volley',
        'Präzisionssalve',
        'Precision Volley',
        'Schieße eine konzentrierte Salve auf dein Ziel.',
        'Fire a concentrated volley at your target.',
        'projectile',
        'physical',
        2.4,
        370,
        5,
        20,
        '#a8cccd',
      ),
      ability(
        'hunter-wire',
        'Fangdraht',
        'Tripwire',
        'Lege einen kalten Fangdraht, der eintretende Gegner verlangsamt.',
        'Lay a cold tripwire that slows enemies entering it.',
        'trap',
        'frost',
        1.4,
        132,
        8,
        24,
        '#85bfce',
      ),
      ability(
        'hunter-mark',
        'Spürmarke',
        'Trail Mark',
        'Markiere nahe Feinde als verwundbar. NIX erkennt den gleichen Angriffspunkt.',
        'Mark nearby foes as vulnerable. NIX recognises the same point of attack.',
        'mark',
        'exposed',
        1.2,
        240,
        7,
        18,
        '#d7bc88',
      ),
      ability(
        'hunter-retreat',
        'Rückzugsfeuer',
        'Retreating Fire',
        'Wechsle rasch deine Position und durchbrich die Verfolgung.',
        'Quickly change position and break the pursuit.',
        'dash',
        'physical',
        1.5,
        168,
        6,
        22,
        '#a5c1b9',
      ),
    ],
    ultimate: ability(
      'hunter-ultimate',
      'Jagdprotokoll',
      'Hunt Protocol',
      'Eine weite Jagdmarkierung trifft und entblößt die gesamte nahe Gruppe.',
      'A wide hunting mark strikes and exposes the whole nearby group.',
      'nova',
      'exposed',
      4.7,
      248,
      35,
      0,
      '#d6e6c8',
    ),
    specs: [
      {
        name: t('Scharfschütze', 'Sharpshooter'),
        description: t(
          '+25 % Schaden. Geduld und eine freie Schusslinie entscheiden.',
          '+25% damage. Patience and a clear firing line decide the fight.',
        ),
        stat: 'damage',
        value: 0.25,
      },
      {
        name: t('Fährtenleger', 'Pathfinder'),
        description: t(
          '+60 % NIX-Schaden. Markierungen und Fangdrähte schaffen gemeinsame Jagdfenster.',
          '+60% NIX damage. Marks and tripwires create shared hunting windows.',
        ),
        stat: 'nix',
        value: 0.6,
      },
    ],
    talents: [
      talent(
        'hunter-t01',
        'Zielsicherheit',
        'Sure Aim',
        '+5 % kritische Trefferchance. Lasse dir den ersten Schuss nicht nehmen.',
        '+5% critical chance. Do not waste your first shot.',
        'crit',
        0.05,
      ),
      talent(
        'hunter-t02',
        'Leichte Tasche',
        'Light Pack',
        '+7 % Bewegungstempo. Du trägst nur, was du brauchst.',
        '+7% movement speed. Carry only what you need.',
        'speed',
        0.07,
      ),
      talent(
        'hunter-t03',
        'Geteilte Fährte',
        'Shared Trail',
        '+20 % NIX-Schaden. Zwei Jäger erkennen mehr als einer.',
        '+20% NIX damage. Two hunters see more than one.',
        'nix',
        0.2,
      ),
      talent(
        'hunter-t04',
        'Ruhige Hand',
        'Steady Hand',
        '+8 % Schaden. Atme aus, dann löse den Schuss.',
        '+8% damage. Exhale, then release the shot.',
        'damage',
        0.08,
      ),
      talent(
        'hunter-t05',
        'Lange Beobachtung',
        'Long Observation',
        '+15 maximale Ressource. Geduld darf nicht am Vorrat scheitern.',
        '+15 maximum resource. Patience should not fail for lack of supplies.',
        'maxResource',
        15,
      ),
      talent(
        'hunter-t06',
        'Sicherer Pfad',
        'Safe Path',
        '+8 % kürzere Ausweich-Erholung. Du hast den Rückweg schon gesehen.',
        '8% faster dodge recovery. You already saw your way back.',
        'dodge',
        0.08,
      ),
      talent(
        'hunter-t07',
        'Feldration',
        'Field Ration',
        '+15 maximales Leben. Eine Expedition braucht eine Reserve.',
        '+15 maximum health. An expedition needs a reserve.',
        'maxHp',
        15,
      ),
      talent(
        'hunter-t08',
        'Neuer Fangdraht',
        'New Tripwire',
        '+7 % kürzere Abklingzeiten. Die nächste Verfolgung ist vorbereitet.',
        '7% shorter cooldowns. The next pursuit is prepared.',
        'cooldown',
        0.07,
      ),
      talent(
        'hunter-t09',
        'Wildruhe',
        'Wild Calm',
        '+1,5 Ressource pro Sekunde. Auch eine Maschine kennt Geduld.',
        '+1.5 resource per second. Even a machine knows patience.',
        'regen',
        1.5,
      ),
      talent(
        'hunter-t10',
        'Keine Beute verloren',
        'No Prey Lost',
        '+20 % NIX-Schaden. Ein klarer Befehl bringt beide sicher heim.',
        '+20% NIX damage. A clear command brings both hunters home.',
        'nix',
        0.2,
      ),
    ],
  },
];
