import type { BossDef, Element, FloorDef, MobDef, Role } from '../game/types';

const t = (de: string, en: string) => ({ de, en });
type MobSeed = [string, string, Role, Element, string, string, string?];
type BossSeed = [string, string, string, string, Element, string[], string?];
interface FloorSeed {
  name: [string, string];
  description: [string, string];
  story: [string, string];
  colors: string[];
  mechanic: string;
  mobs: MobSeed[];
  elites: MobSeed[];
  guardian: BossSeed;
  hunt: BossSeed;
  boss: BossSeed;
}

const seeds: FloorSeed[] = [
  {
    name: ['Aufnahmehalle', 'Intake Hall'],
    description: [
      'Unter flackernden mintfarbenen Anzeigen schieben Förderbänder die Reste einer verschwundenen Menge weiter. Die Türen kennen deinen Namen, obwohl du ihn noch keinem gesagt hast.',
      'Under flickering mint displays, conveyors move the remains of a vanished crowd. The doors know your name before you have told anyone.',
    ],
    story: [
      'Im Einlassprotokoll steht eine zweite Eigentumszeile: Der Sender erwirbt nicht nur deine Leistung, sondern jede aufgezeichnete Erinnerung. NIX hat genau diesen Absatz aus seinem beschädigten Speicher gerettet.',
      'The admission protocol contains a second ownership clause: the broadcaster acquires not only your performance but every recorded memory. NIX rescued that very paragraph from his damaged storage.',
    ],
    colors: ['#363e38', '#1b2824', '#8ce2b7', '#b5cfc3'],
    mechanic: 'conveyors',
    mobs: [
      [
        'Kehrdrohne',
        'Sweeper Drone',
        'chaser',
        'physical',
        'warrior',
        'Hält die Gänge sauber, indem sie alles Lebende wegschiebt. Weiche dem sichtbaren Bürstenstoß seitlich aus.',
        'Keeps corridors clean by shoving anything alive aside. Step sideways out of the visible brush strike.',
      ],
      [
        'Schlackenschleim',
        'Slag Slime',
        'controller',
        'corrosion',
        'slime',
        'Wandert langsam durch die Halle und verätzt kurze Bodenstreifen. Lock ihn aus dem Durchgang, bevor du weitergehst.',
        'Drifts slowly through the hall, corroding short strips of floor. Lure it away before using the passage.',
      ],
      [
        'Kabelkriecher',
        'Cable Crawler',
        'ambusher',
        'shock',
        'rat',
        'Ruht als unscheinbarer Kabelhaufen. Ein aufglühender Draht verrät den kommenden Sprung.',
        'Rests as an inconspicuous coil of cable. A glowing wire gives away its coming leap.',
      ],
      [
        'Wachkonstrukt',
        'Guard Construct',
        'tank',
        'physical',
        'construct',
        'Schützt die Vorderseite mit einer Türplatte. Umkreise seine langsame Drehung und schlage in die offene Flanke.',
        'Guards its front with a door panel. Circle its slow turn and strike the exposed flank.',
      ],
      [
        'Datenlaus',
        'Data Louse',
        'flanker',
        'bleed',
        'rat',
        'Kleine Sammler greifen von der Seite an. Ein rascher Flächenschlag verhindert, dass sie den ganzen Raum besetzen.',
        'Small collectors attack from the side. A quick area strike prevents them from occupying the whole room.',
      ],
      [
        'Sicherheitsläufer',
        'Security Runner',
        'chaser',
        'stagger',
        'warrior',
        'Hält vor seinem Sprint kurz an und spannt die Beine. Eine ruhige Seitwärtsbewegung lässt ihn vorbeilaufen.',
        'Stops briefly and braces its legs before sprinting. A steady sidestep lets it run past.',
      ],
      [
        'Türwächter',
        'Door Sentinel',
        'tank',
        'shield',
        'construct',
        'Ein enger Schutzbogen blockiert den direkten Weg. Hinter dem Schild liegt der ungesicherte Türantrieb.',
        'A narrow guard arc blocks the direct approach. Behind the shield lies an unprotected door drive.',
      ],
      [
        'Inkassospäher',
        'Collection Scout',
        'support',
        'exposed',
        'skeleton-hunter',
        'Seine Zielmarke verstärkt nachfolgende Angriffe. Unterbrich die Erfassung, bevor die rote Linie vollständig ist.',
        'Its target mark strengthens follow-up attacks. Interrupt the scan before the red line is complete.',
      ],
    ],
    elites: [
      [
        'Schichtführer',
        'Shift Supervisor',
        'summoner',
        'shock',
        'skeleton-king',
        'Ruft Kehrdrohnen zur nächsten Schicht. Seine leuchtende Meldeleiste zeigt das Beschwörungsfenster.',
        'Calls sweeper drones for the next shift. Its glowing report strip reveals the summoning window.',
      ],
      [
        'Zutrittswächter',
        'Access Warden',
        'controller',
        'stagger',
        'construct',
        'Versetzt die markierten Torfenster. Warte auf die feste sichere Lücke, bevor du den Raum kreuzt.',
        'Shifts marked gate windows. Wait for the fixed safe gap before crossing the room.',
      ],
    ],
    guardian: [
      'Qualitätsprüfer Q-17',
      'Quality Inspector Q-17',
      'Stempelt den Boden, dann prüft er dich mit Scanlinien. Seine Erholung nach dem Stempel ist das sichere Angriffsfenster.',
      'Stamps the floor, then inspects you with scan lines. Its recovery after stamping is your safe attack window.',
      'shock',
      ['line', 'cleave', 'ring'],
      'construct',
    ],
    hunt: [
      'Kabelgreif',
      'Cable Gryphon',
      'Ein Kabelnest zieht sich in geraden Sätzen über die Halle. Weiche zuerst der Zuglinie aus; dann ist der Kern offen.',
      'A cable nest pulls itself across the hall in straight leaps. Dodge the pull line first; its core opens afterwards.',
      'shock',
      ['charge', 'burst', 'line'],
      'goblin-beast',
    ],
    boss: [
      'Pförtner-900',
      'Gatekeeper-900',
      'Scanlinien, Sperrringe und ein überlasteter Kern halten den Einlass geschlossen. Zwischen zwei Prüfungen bleibt immer eine sichere Seite.',
      'Scan lines, lockdown rings and an overloaded core seal the entrance. One side is always safe between inspections.',
      'shock',
      ['line', 'ring', 'burst', 'cleave', 'line'],
      'skeleton-king',
    ],
  },
  {
    name: ['Rostkanäle', 'Rust Channels'],
    description: [
      'Kupferrohre führen braunes Wasser durch versunkene Behandlungsräume. Jeder Druckstoß erinnert daran, dass auch Versorgung ein Werkzeug der Kontrolle ist.',
      'Copper pipes carry brown water through submerged treatment rooms. Each pressure surge reminds you that provision can be a tool of control.',
    ],
    story: [
      'Mira versteckt ihre Klinik im Rücklauf einer Pumpe. Der Sender kann jeden Anschluss einzeln abdrehen. Eine saubere Versorgung wäre ihr erster Schritt aus dem Vertrag.',
      'Mira hides her clinic in a pump return line. The broadcaster can shut off every connection individually. Clean provision would be her first step out of the contract.',
    ],
    colors: ['#3c443a', '#242e2b', '#8cae86', '#c9bb8b'],
    mechanic: 'water',
    mobs: [
      [
        'Rostratte',
        'Rust Rat',
        'flanker',
        'bleed',
        'rat',
        'Flitzt an Wasserflächen entlang und springt auf die freie Flanke. Lass ihr nicht den Rücken eines Tanks als Deckung.',
        'Darts along water edges and leaps at an open flank. Do not give it a tank’s back for cover.',
      ],
      [
        'Sporenläufer',
        'Spore Runner',
        'chaser',
        'corrosion',
        'goblin-beast',
        'Trägt eine undichte Filterkapsel. Seine kurze Giftspur bestraft blindes Hinterherlaufen.',
        'Carries a leaking filter capsule. Its short toxic trail punishes blind pursuit.',
      ],
      [
        'Ventilspucker',
        'Valve Spitter',
        'shooter',
        'corrosion',
        'slime',
        'Baut sichtbar Druck auf, bevor ein langsamer Strahl kommt. Nutze Rohrstützen oder kreuze seine Linie früh.',
        'Visibly builds pressure before releasing a slow jet. Use pipe supports or cross its line early.',
      ],
      [
        'Kanalwache',
        'Channel Guard',
        'tank',
        'physical',
        'construct',
        'Steht breit auf dem Steg. Nach dem schweren Schlag muss sie den Fuß aus dem Rost lösen.',
        'Stands wide across the walkway. After a heavy strike it must pull its foot from the rust.',
      ],
      [
        'Saugwurm',
        'Suction Worm',
        'ambusher',
        'bleed',
        'rat',
        'Sein Ablauf gurgelt vor dem Ausbruch. Warte außerhalb des markierten Radius und greife nach dem Sprung an.',
        'Its drain gurgles before it erupts. Wait outside the marked radius and attack after the leap.',
      ],
      [
        'Druckqualle',
        'Pressure Jelly',
        'controller',
        'shock',
        'slime',
        'Sendet einen angekündigten Strompuls durch die nasse Umgebung. Trockene Inseln geben dir Zeit zum Gegenangriff.',
        'Sends a telegraphed electrical pulse through wet ground. Dry islands give you time to counterattack.',
      ],
      [
        'Filterkrabbe',
        'Filter Crab',
        'tank',
        'corrosion',
        'construct',
        'Ihre Panzerseite deckt den Abfluss. Drehe sie mit einer Flanke, statt den Schild frontal zu bearbeiten.',
        'Its armoured side covers the drain. Turn it by flanking rather than striking the shield head-on.',
      ],
      [
        'Rinnenhexe',
        'Gutter Witch',
        'summoner',
        'corrosion',
        'necromancer',
        'Kippt Schleimkopien in offene Rinnen. Die Beschwörung ist langsam; der erste Treffer stört ihre Ordnung.',
        'Pours slime copies into open gutters. Summoning is slow; your first hit disrupts its order.',
      ],
    ],
    elites: [
      [
        'Pumpenwart',
        'Pump Keeper',
        'support',
        'shield',
        'skeleton-king',
        'Stabilisiert angeschlagene Kanalwachen. Seine Reparaturöffnung ist leichter zu treffen als der Panzer der Wachen.',
        'Stabilises wounded channel guards. Its repair opening is easier to hit than the guards’ armour.',
      ],
      [
        'Druckmeister',
        'Pressure Master',
        'controller',
        'shock',
        'goblin-beast',
        'Verbindet einen geraden Ventilstoß mit einem schweren Nahschlag. Erst Linie meiden, dann hinter den Arm wechseln.',
        'Combines a straight valve jet with a heavy melee blow. Avoid the line, then move behind its arm.',
      ],
    ],
    guardian: [
      'Ventilzwillinge',
      'Valve Twins',
      'Zwei verbundene Pumpenköpfe wechseln zwischen Sog und Stoß. Der gemeinsame Takt bietet nach jedem Doppelimpuls eine Öffnung.',
      'Two connected pump heads alternate suction and pressure. Their shared rhythm offers an opening after each double pulse.',
      'shock',
      ['line', 'pool', 'ring'],
      'construct',
    ],
    hunt: [
      'Der Fettfang',
      'Grease Maw',
      'Verstopfte Abläufe nähren den schlammigen Körper. Seine Säurepfützen bleiben klein, wenn du ihn durch trockene Korridore führst.',
      'Blocked drains feed its muddy body. Its acid pools stay manageable when you lead it through dry corridors.',
      'corrosion',
      ['pool', 'charge', 'burst'],
      'slime',
    ],
    boss: [
      'Mutter Pumpe',
      'Mother Pump',
      'Wechselnde Druckzonen und Wasserströme teilen die Arena. Nach den großen Stößen öffnet sich das manuelle Ventilfenster.',
      'Alternating pressure zones and water flows divide the arena. Major surges open a manual valve window.',
      'corrosion',
      ['pool', 'line', 'charge', 'ring', 'pool'],
      'goblin-beast',
    ],
  },
  {
    name: ['Schrottbasilika', 'Scrap Basilica'],
    description: [
      'Schwarze Stahlaltäre halten die Tiefe zusammen. Bernsteinlichter beleuchten Dinge, die als Reliquien verkauft werden, obwohl sie einmal Menschen gehörten.',
      'Black steel altars hold the depths together. Amber lamps light objects sold as relics, though they once belonged to people.',
    ],
    story: [
      'Der Sammler katalogisiert nicht nur Besitz. Seine seltensten Stücke sind Erinnerungen, deren Besitzer noch im System leben. Tam erkennt auf einem Pfandschein den Namen seiner Familie.',
      'The Collector catalogues more than property. Its rarest pieces are memories whose owners still live in the system. Tam recognises his family’s name on a pawn receipt.',
    ],
    colors: ['#3d3830', '#292925', '#e5b16b', '#d1bc87'],
    mechanic: 'magnet',
    mobs: [
      [
        'Magnethund',
        'Magnet Hound',
        'chaser',
        'shock',
        'rat',
        'Seine Spulen knacken vor jedem Ansturm. Ein früher Seitenschritt lässt das schwere Maul ins Leere greifen.',
        'Its coils crackle before every charge. An early sidestep leaves the heavy jaw snapping at air.',
      ],
      [
        'Schrottschütze',
        'Scrap Shooter',
        'shooter',
        'physical',
        'skeleton-hunter',
        'Verschießt klar erkennbare Metallpakete. Eine Säule stoppt die Salve und eröffnet einen Wechsel der Position.',
        'Fires clearly visible bundles of metal. A pillar stops the volley and gives you a chance to reposition.',
      ],
      [
        'Stapelgolem',
        'Stack Golem',
        'tank',
        'stagger',
        'construct',
        'Trägt seinen Schutz in mehreren schweren Schichten. Weiche dem langsamen Bodenschlag aus und greife während des Aufrichtens an.',
        'Carries protection in heavy layers. Dodge its slow ground strike and attack while it rises.',
      ],
      [
        'Funkenvogel',
        'Spark Bird',
        'flanker',
        'fire',
        'bat',
        'Zieht einen leuchtenden Bogen hinter dem Ziel. Beobachte den Kreis, statt seinem Schatten zu folgen.',
        'Draws a glowing arc behind its target. Watch the circle rather than chase its shadow.',
      ],
      [
        'Kabelschlange',
        'Cable Snake',
        'controller',
        'shock',
        'rat',
        'Spannt den Körper vor dem Zug. Ihre gerade Reichweite ist gefährlich; die Seite bleibt frei.',
        'Tenses its body before pulling. Its straight reach is dangerous; its side stays open.',
      ],
      [
        'Rostmönch',
        'Rust Monk',
        'support',
        'shield',
        'necromancer',
        'Segnet benachbarte Schrottkörper. Die kleine Schutzgruppe zerfällt, wenn du den Mönch zuerst störst.',
        'Blesses nearby scrap bodies. The protected group breaks apart if you interrupt the monk first.',
      ],
      [
        'Presswerk',
        'Presswork',
        'chaser',
        'stagger',
        'construct',
        'Eine laufende Presse braucht Platz zum Bremsen. Locke ihre Charge an einer breiten Wand vorbei.',
        'A walking press needs room to brake. Lure its charge past a broad wall.',
      ],
      [
        'Altardrohne',
        'Altar Drone',
        'shooter',
        'shock',
        'bat',
        'Schießt kurze kontrollierte Bursts aus fester Höhe. Während ihrer Kühlpause gehört dir die offene Fläche.',
        'Fires short controlled bursts from a fixed height. The open ground is yours during its cooling pause.',
      ],
    ],
    elites: [
      [
        'Magnetdiakon',
        'Magnet Deacon',
        'controller',
        'shock',
        'skeleton-king',
        'Zieht mehrere Metallkörper zusammen. Halte Abstand von der markierten Sammelzone und greife den freistehenden Diakon an.',
        'Pulls several metal bodies together. Stay out of the marked gathering zone and attack the exposed deacon.',
      ],
      [
        'Schrottherold',
        'Scrap Herald',
        'summoner',
        'physical',
        'goblin-beast',
        'Errichtet vor der Beschwörung eine sichtbare Magnetzone. Ein schneller Angriff verhindert den nächsten Schrottwall.',
        'Raises a visible magnetic zone before summoning. A quick attack prevents the next scrap wall.',
      ],
    ],
    guardian: [
      'Kranheilige',
      'Crane Saint',
      'Hebt ihre Last sichtbar über den Boden. Nach dem Aufschlag bleibt Zeit, zwischen den Trümmern an den Kranarm zu gelangen.',
      'Visibly lifts its load above the ground. After impact there is time to reach its crane arm between the debris.',
      'stagger',
      ['pool', 'cleave', 'charge'],
      'construct',
    ],
    hunt: [
      'Pfandschein-Golem',
      'Pawn Receipt Golem',
      'Jede Eigentumsplatte ist eine Forderung. Seine schweren Schläge machen die Rückseite erreichbar, bevor er sich neu sortiert.',
      'Every ownership plate is a claim. Its heavy strikes expose its rear before it reassembles.',
      'physical',
      ['cleave', 'ring', 'charge'],
      'goblin-beast',
    ],
    boss: [
      'Der Sammler',
      'The Collector',
      'Schrottwellen schützen ein Archiv voller gestohlener Stimmen. Seine Beschwörungen binden Aufmerksamkeit, doch der Kern bleibt zwischen den Wellen angreifbar.',
      'Scrap waves protect an archive of stolen voices. Its summons demand attention, but the core is vulnerable between waves.',
      'shock',
      ['summon', 'line', 'cleave', 'burst', 'ring'],
      'skeleton-king',
    ],
  },
  {
    name: ['Pilzredaktion', 'Mycelium Newsroom'],
    description: [
      'Biolumineszente Wurzeln drängen durch Schreibmaschinen und Satzwände. Hier wächst die morgige Nachricht aus dem Material der gestrigen Erinnerung.',
      'Bioluminescent roots push through typewriters and printing walls. Here tomorrow’s news grows from the material of yesterday’s memory.',
    ],
    story: [
      'Zuv hält die organischen Leitungen am Leben. Myr überschreibt damit die Archive. Du brauchst eine unabhängige Versorgung, sonst trifft jede zerstörte Schlagzeile auch die Bewohner.',
      'Zuv keeps the organic conduits alive. Myr uses them to overwrite archives. You need independent provision, or every destroyed headline harms the residents too.',
    ],
    colors: ['#343b35', '#202e29', '#9ab578', '#c6c88e'],
    mechanic: 'spores',
    mobs: [
      [
        'Tintenling',
        'Inkling',
        'chaser',
        'corrosion',
        'slime',
        'Rutscht aus einer offenen Druckwanne. Sein Tintenstoß ist kurz; ein Schritt Abstand verhindert den ganzen Treffer.',
        'Slides from an open printing vat. Its ink strike is short; one step of distance avoids the whole hit.',
      ],
      [
        'Sporenwerfer',
        'Spore Thrower',
        'shooter',
        'corrosion',
        'sorceress',
        'Bläst langsame Sporenpakete durch den Gang. Kleine Kurswechsel sind sicherer als eine Flucht entlang der Schusslinie.',
        'Blows slow spore bundles down the corridor. Small course changes are safer than fleeing along its firing line.',
      ],
      [
        'Wurzelfänger',
        'Root Catcher',
        'controller',
        'stagger',
        'construct',
        'Zeigt die nächste Wurzelöffnung mit einem hellen Ring. Verlasse den Ring, bevor du weiter angreifst.',
        'Marks the next root opening with a bright ring. Leave it before continuing your attack.',
      ],
      [
        'Redaktionskäfer',
        'Newsroom Beetle',
        'tank',
        'physical',
        'rat',
        'Ein schwerer Satzkasten schützt seine Front. Die Rückseite bleibt während des Aufrichtens offen.',
        'A heavy typecase guards its front. Its rear remains open while it rises.',
      ],
      [
        'Druckkobold',
        'Printing Goblin',
        'ambusher',
        'corrosion',
        'goblin-beast',
        'Klebt Papierfallen unter den freien Weg. Die helle Falzkante verrät den kleinen Gefahrenbereich.',
        'Sticks paper traps beneath open paths. A bright fold reveals each small danger area.',
      ],
      [
        'Pilzschreiber',
        'Mushroom Scribe',
        'summoner',
        'corrosion',
        'necromancer',
        'Schreibt langsam eine lebende Spore in den Boden. Unterbrich den fertigen Satz, bevor eine zweite Zeile entsteht.',
        'Slowly writes a living spore into the floor. Interrupt the sentence before it adds a second line.',
      ],
      [
        'Klebemasse',
        'Glue Mass',
        'controller',
        'frost',
        'slime',
        'Wandert als klebrige Sperre durch den Raum. Führe sie an eine Außenwand und halte den zentralen Weg frei.',
        'Drifts through the room as a sticky barrier. Lead it to an outer wall and keep the central route free.',
      ],
      [
        'Wortsammler',
        'Word Collector',
        'support',
        'exposed',
        'bat',
        'Sammelt den Fokus der Redaktion. Seine Bindung kündigt sich mit einem deutlich sichtbaren Wortkreis an.',
        'Collects the newsroom’s focus. Its binding is announced by a clearly visible word circle.',
      ],
    ],
    elites: [
      [
        'Chefredakteur',
        'Chief Editor',
        'summoner',
        'corrosion',
        'skeleton-king',
        'Erklärt seine Sporen zur einzigen gültigen Fassung. Die Beschwörung benötigt eine ungestörte Zeile; lass sie nicht fertig werden.',
        'Declares its spores the only valid edition. Summoning needs an uninterrupted line; do not let it finish.',
      ],
      [
        'Sporenkurator',
        'Spore Curator',
        'controller',
        'corrosion',
        'goblin-beast',
        'Verbindet zwei leuchtende Anker. Der Bereich dazwischen ist gefährlich, die Außenkante gibt eine klare Flanke.',
        'Connects two glowing anchors. The space between is dangerous; the outer edge gives a clear flank.',
      ],
    ],
    guardian: [
      'Richtigsteller',
      'The Corrector',
      'Übermalt angekündigte Flächen und zieht dann eine gerade Korrekturlinie. Wechsel die freie Seite, bevor die zweite Fassung gilt.',
      'Paints over telegraphed areas, then draws a straight correction line. Change to the free side before the second edition takes effect.',
      'corrosion',
      ['pool', 'line', 'burst'],
      'skeleton-king',
    ],
    hunt: [
      'Sporenorakel',
      'Spore Oracle',
      'Form und Farbe der Sporen sagen den nächsten Puls voraus. Die schmale Lücke im Muster ist absichtlich groß genug für einen sicheren Schritt.',
      'The spores’ shape and colour predict the next pulse. A narrow gap in the pattern deliberately leaves room for a safe step.',
      'corrosion',
      ['burst', 'summon', 'pool'],
      'goblin-beast',
    ],
    boss: [
      'Redaktor Myr',
      'Editor Myr',
      'Lebende Schlagzeilen wechseln zwischen Flächen und Wurzelgriffen. Lies das Bodenmuster, bevor du die vergiftete Fassung angreifst.',
      'Living headlines alternate between zones and root grasps. Read the floor pattern before attacking the poisoned edition.',
      'corrosion',
      ['pool', 'summon', 'ring', 'line', 'burst'],
      'skeleton-king',
    ],
  },
  {
    name: ['Glutgießerei', 'Ember Foundry'],
    description: [
      'Basalt und Weißglut umgeben eine Fertigungsstraße ohne Schichtende. In den Gussformen liegen Körper, jeder mit einer eigenen Seriennummer.',
      'Basalt and white heat surround a production line without an end of shift. Bodies lie in the moulds, each carrying its own serial number.',
    ],
    story: [
      'Die Gießerei macht Rekonstruktion bequem: Ein neuer Körper, ein altes Eigentumsrecht. Ash nennt das Fürsorge. Mira braucht die Fertigungsdaten, um Versorgung ohne Besitzanspruch möglich zu machen.',
      'The foundry makes reconstruction convenient: a new body, an old ownership right. Ash calls that care. Mira needs the production data to make provision possible without ownership.',
    ],
    colors: ['#43392f', '#2a2925', '#d78a53', '#e5bd82'],
    mechanic: 'heat',
    mobs: [
      [
        'Ofenimp',
        'Furnace Imp',
        'flanker',
        'fire',
        'goblin-beast',
        'Springt vom heißen Rand in die freie Flanke. Seine Glut leuchtet auf, bevor die Füße den Boden verlassen.',
        'Leaps from the hot edge into an open flank. Its embers flare before its feet leave the ground.',
      ],
      [
        'Gussläufer',
        'Cast Runner',
        'chaser',
        'fire',
        'warrior',
        'Ein frisch gegossener Körper greift geradlinig an. Die Kühlpause nach der Charge ist seine Schwäche.',
        'A freshly cast body attacks in a straight line. Its cooling pause after a charge is its weakness.',
      ],
      [
        'Kettenschleuder',
        'Chain Slinger',
        'shooter',
        'stagger',
        'skeleton-hunter',
        'Spannung läuft sichtbar durch die Kette. Die gespannte Linie darfst du meiden, den Rückzug kannst du bestrafen.',
        'Tension visibly runs along its chain. Avoid the taut line and punish its recoil.',
      ],
      [
        'Kühlwächter',
        'Cooling Guard',
        'tank',
        'frost',
        'construct',
        'Versiegelt den Kühlausgang mit einer schweren Platte. Ein Seitenschritt nach dem Froststoß legt die Ventile frei.',
        'Seals the coolant outlet with a heavy plate. A sidestep after its frost strike exposes the valves.',
      ],
      [
        'Schlackenkäfer',
        'Slag Beetle',
        'controller',
        'fire',
        'rat',
        'Hinterlässt eine kurze Glutspur. Bewege den Kampf von seiner alten Route weg.',
        'Leaves a short ember trail. Move the fight away from its old route.',
      ],
      [
        'Schmiedekonstrukt',
        'Smith Construct',
        'tank',
        'physical',
        'construct',
        'Öffnet den Panzer für einen schweren Werkstattschlag. Warte auf diese klare Lücke statt den Stahl zu bearbeiten.',
        'Opens its armour for a heavy workshop strike. Wait for that clear opening rather than batter the steel.',
      ],
      [
        'Aschegeist',
        'Ash Spirit',
        'ambusher',
        'fire',
        'necromancer',
        'Ein Aschekreis zeigt seinen nächsten Standort. Greife dort erst an, wenn der Auftritt beendet ist.',
        'An ash circle reveals its next position. Attack there only after its arrival is complete.',
      ],
      [
        'Zunderträger',
        'Tinder Carrier',
        'chaser',
        'fire',
        'slime',
        'Sein Kessel beginnt vor der Explosion zu zittern. Abstand macht seinen letzten Angriff ungefährlich.',
        'Its kettle starts shaking before it explodes. Distance makes its final attack harmless.',
      ],
    ],
    elites: [
      [
        'Vorarbeiter Glut',
        'Foreman Ember',
        'summoner',
        'fire',
        'skeleton-king',
        'Ruft die nächste Gusscharge. Unterbrich ihn vor dem fertigen Arbeitssignal, um die Formation klein zu halten.',
        'Calls the next cast batch. Interrupt its completed work signal to keep the formation small.',
      ],
      [
        'Härtungsmeister',
        'Tempering Master',
        'controller',
        'frost',
        'goblin-beast',
        'Seine kühlen und heißen Phasen sind sichtbar. Bleibe auf der sicheren Seite des jeweils markierten Zyklus.',
        'Its cool and hot phases are visible. Stay on the safe side of each marked cycle.',
      ],
    ],
    guardian: [
      'Schlackenkönig',
      'Slag King',
      'Der schwere Panzer braucht Kühlung zwischen zwei Glutwellen. Das Ventilfenster ist dein Angriffsmoment.',
      'Its heavy armour needs cooling between ember waves. The valve window is your moment to attack.',
      'fire',
      ['ring', 'pool', 'cleave'],
      'goblin-beast',
    ],
    hunt: [
      'Die Nachtschicht',
      'The Night Shift',
      'Eine Maschinenkombination arbeitet nach einem festen sichtbaren Rhythmus. Folge der Pause, nicht dem lautesten Schlag.',
      'A machine assembly works to a fixed visible rhythm. Follow the pause, not the loudest strike.',
      'fire',
      ['line', 'charge', 'pool'],
      'construct',
    ],
    boss: [
      'Vorarbeiterin Ash',
      'Forewoman Ash',
      'Schmelzwellen drängen dich aus der Mitte, Kühllinien geben einen Weg zurück. Die aufgerissene Ofenfront ist nur nach dem großen Zyklus offen.',
      'Molten waves drive you from the centre; cooling lines offer a way back. The furnace front opens only after the major cycle.',
      'fire',
      ['ring', 'pool', 'line', 'charge', 'cleave'],
      'skeleton-king',
    ],
  },
  {
    name: ['Sponsorengalerie', 'Sponsor Gallery'],
    description: [
      'Goldene Rahmen und petrolfarbene Reklame spiegeln einen Sieg, der nie endet. Unter jedem Versprechen steht eine kleiner gedruckte Forderung.',
      'Golden frames and petrol advertisements reflect a victory that never ends. Beneath every promise is a claim in smaller print.',
    ],
    story: [
      'Rhea hat gewonnen und trotzdem keinen Ausgang gefunden. Ihr Sponsorvertrag besitzt keine Freigabeklausel. Ein Duell zeigt ihr erstmals, dass sie auch ohne die geliehene Siegerrolle bestehen kann.',
      'Rhea won and still found no exit. Her sponsorship contract contains no release clause. A duel shows her for the first time that she can survive without her borrowed champion role.',
    ],
    colors: ['#344340', '#1f2d2e', '#d5b371', '#cbbd9c'],
    mechanic: 'contracts',
    mobs: [
      [
        'Reklame-Drohne',
        'Advertisement Drone',
        'shooter',
        'shock',
        'bat',
        'Unterbricht ihre Ansage nur zum Schießen. Die geschlossene Leuchtzeile kündigt jede Salve an.',
        'Interrupts its advertisement only to fire. A closed strip of light announces every volley.',
      ],
      [
        'Vertragsritter',
        'Contract Knight',
        'tank',
        'shield',
        'warrior',
        'Trägt das Siegel eines großen Sponsors. Nach seinem langsamen Urteilsschlag ist die Vertragsseite ungeschützt.',
        'Bears a major sponsor’s seal. After its slow judgment strike, its contract side is exposed.',
      ],
      [
        'Maskentänzer',
        'Mask Dancer',
        'flanker',
        'bleed',
        'necromancer',
        'Bewegt sich um die Kameraseite und schlägt vom Rand. Folge den sichtbaren Füßen, nicht der schimmernden Maske.',
        'Circles the camera side and strikes from the edge. Follow its visible feet, not its shimmering mask.',
      ],
      [
        'Pfandvollstrecker',
        'Pledge Enforcer',
        'chaser',
        'stagger',
        'goblin-beast',
        'Seine Forderung kommt als angekündigter schwerer Schritt. Verlasse die Linie und lasse ihn den Preis allein bezahlen.',
        'Its claim arrives as a telegraphed heavy step. Leave the line and let it pay the price alone.',
      ],
      [
        'Siegelträger',
        'Seal Bearer',
        'support',
        'shield',
        'construct',
        'Hält Verträge für benachbarte Ritter offen. Unterbrich zuerst das Siegel, danach bricht die geschützte Front.',
        'Maintains contracts for nearby knights. Interrupt the seal first and the protected front follows.',
      ],
      [
        'Rabattjäger',
        'Discount Hunter',
        'flanker',
        'exposed',
        'rat',
        'Bietet seinen Rücken beim riskanten Flankenlauf an. Eine klare Seitwärtsbewegung lässt das Angebot scheitern.',
        'Exposes its back during a risky flanking run. A clear sidestep makes its offer fail.',
      ],
      [
        'Reklamefalter',
        'Advertisement Moth',
        'controller',
        'shock',
        'bat',
        'Stellt sich in der hellsten Kamerazone auf. Verlasse den markierten Lockkreis, bevor du auf die Flügel zielst.',
        'Settles in the brightest camera zone. Leave the marked lure circle before aiming for its wings.',
      ],
      [
        'Vertragsgeist',
        'Contract Ghost',
        'shooter',
        'corrosion',
        'necromancer',
        'Sein Pfandstrahl braucht eine feste Sichtlinie. Deckung und Unterbrechung nehmen der Forderung ihren Wert.',
        'Its pledge beam needs a fixed sightline. Cover and interruption remove the claim’s value.',
      ],
    ],
    elites: [
      [
        'Markenchampion',
        'Brand Champion',
        'tank',
        'physical',
        'skeleton-king',
        'Zeigt jede große Attacke mit einem Sponsorzeichen. Lass den Auftritt enden, dann bleibt ein echtes Angriffsfeld.',
        'Announces each major attack with a sponsor emblem. Let the performance end; a real opening remains.',
      ],
      [
        'Vertragsscharfrichter',
        'Contract Executioner',
        'controller',
        'exposed',
        'goblin-beast',
        'Markiert sein Urteil mit einem roten Kreis. Lasse zwischen Forderung und Vollstreckung einen sicheren Abstand.',
        'Marks its judgment with a red circle. Keep safe distance between the claim and its execution.',
      ],
    ],
    guardian: [
      'Inkasso-Engel',
      'Collection Angel',
      'Zeigt sein Pfandziel, dann zieht er eine klare Urteilslinie. Nach dem verfehlten Urteil bleiben die Schwingen offen.',
      'Shows its pledge target, then draws a clear line of judgment. Its wings stay open after a missed verdict.',
      'exposed',
      ['line', 'charge', 'ring'],
      'skeleton-king',
    ],
    hunt: [
      'Der Rabattgraf',
      'Count Discount',
      'Jedes große Angebot folgt einer sichtbaren Risikozone. Gehe um den Preis herum und greife die anschließende schwache Haltung an.',
      'Every grand offer follows a visible risk zone. Go around the price and attack its weakened stance afterwards.',
      'physical',
      ['burst', 'cleave', 'pool'],
      'goblin-beast',
    ],
    boss: [
      'Rhea, die Siegerin',
      'Rhea, the Champion',
      'Ein ehrliches Duell wird von Sponsorfeuer unterbrochen. Lies ihre schnellen Schritte und die langsam angekündigten Flächen getrennt.',
      'An honest duel is interrupted by sponsor fire. Read her quick steps separately from slowly telegraphed zones.',
      'physical',
      ['charge', 'cleave', 'burst', 'line', 'summon'],
      'warrior',
    ],
  },
  {
    name: ['Eisarchiv', 'Frozen Archive'],
    description: [
      'Blaue Eisglasregale bergen versiegelte Leben. Jede Nummer ist lesbar; was darunter gelöscht wurde, lässt sich erst mit Licht erkennen.',
      'Blue ice-glass shelves hold sealed lives. Every number is readable; only light reveals what was erased underneath.',
    ],
    story: [
      'Ilya trennt Originale von nachträglich geschnittenen Fassungen. Ennos erste Akte enthält Entscheidungen, an die er sich nicht erinnert. Die Wahrheit darf kein neues Eigentumsrecht werden.',
      'Ilya separates originals from later edits. Enno’s first file contains choices he does not remember. Truth must not become a new ownership right.',
    ],
    colors: ['#35424b', '#26323b', '#8cc9e2', '#c1d2d2'],
    mechanic: 'ice',
    mobs: [
      [
        'Frostschreiber',
        'Frost Scribe',
        'shooter',
        'frost',
        'sorceress',
        'Schreibt einen langsamen Eisstrahl in die Regalzeile. Halte einen Quergang frei, um die Linie zu kreuzen.',
        'Writes a slow ice beam along the shelves. Keep a cross-aisle open to cross the line.',
      ],
      [
        'Archivmotte',
        'Archive Moth',
        'flanker',
        'frost',
        'bat',
        'Versteckt sich im Licht der Register. Ihre scharfe Kurve endet in einem kurzen, angreifbaren Stillstand.',
        'Hides in the registers’ light. Its sharp turn ends in a short, vulnerable pause.',
      ],
      [
        'Splittergeist',
        'Shard Spirit',
        'ambusher',
        'bleed',
        'necromancer',
        'Sein Eisbild wird vor dem Angriff dunkler. Warte den sichtbaren Eintritt ab, statt ihm blind entgegenzulaufen.',
        'Its ice image darkens before an attack. Wait for its visible arrival rather than rushing blindly towards it.',
      ],
      [
        'Indexwächter',
        'Index Guard',
        'tank',
        'physical',
        'construct',
        'Schiebt einen schweren Registerdeckel vor sich. Eine Seitenroute im Regal macht seinen Schutz bedeutungslos.',
        'Pushes a heavy register lid ahead of it. A side route through the shelves makes that defence useless.',
      ],
      [
        'Kältespinne',
        'Cold Spider',
        'controller',
        'frost',
        'rat',
        'Spannt kleine Eisnetze in freie Wege. Der Rand des Netzes ist sichtbar und bietet eine sichere Umgehung.',
        'Spins small ice webs across open routes. The web edge is visible and allows a safe detour.',
      ],
      [
        'Datenschatten',
        'Data Shadow',
        'chaser',
        'shock',
        'necromancer',
        'Eine helle Position zeigt seine nächste Abkürzung. Laufe seitlich aus dem angekündigten Eintritt.',
        'A bright position shows its next shortcut. Move sideways away from the telegraphed entry.',
      ],
      [
        'Siegelgolem',
        'Seal Golem',
        'tank',
        'shield',
        'goblin-beast',
        'Ein eingefrorenes Siegel schützt den vorderen Bogen. Sein langsamer Schlag öffnet die ungeschützte Rückseite.',
        'A frozen seal protects its front arc. Its slow strike opens the unprotected rear.',
      ],
      [
        'Registerjäger',
        'Register Hunter',
        'shooter',
        'frost',
        'skeleton-hunter',
        'Nutzt die langen Regalzwischenräume. Die erste Zielgerade verrät die Richtung seiner nächsten Salve.',
        'Uses the long gaps between shelves. Its first aiming line reveals the next volley’s direction.',
      ],
    ],
    elites: [
      [
        'Hauptregistrar',
        'Chief Registrar',
        'support',
        'shield',
        'skeleton-king',
        'Wertet den Schutz der Archivwachen neu auf. Seine offene Leselinse ist der schnellste Weg zur freien Zeile.',
        'Renews the archive guards’ protection. Its exposed reading lens is the quickest path to a clear aisle.',
      ],
      [
        'Frostsiegelwart',
        'Frost Seal Keeper',
        'controller',
        'frost',
        'goblin-beast',
        'Kühlt einen vorher markierten Gang. Die Außenroute bleibt frei; nutze sie, bevor der Frost greift.',
        'Cools a corridor marked in advance. The outer route stays clear; use it before the frost takes hold.',
      ],
    ],
    guardian: [
      'Index Null',
      'Index Zero',
      'Sortierte Suchstrahlen prüfen erst eine Linie, dann den Ring. Nach dem Suchwechsel ist das leere Register offen.',
      'Ordered search beams inspect a line first, then a ring. The empty register opens after the search changes.',
      'frost',
      ['line', 'burst', 'cleave'],
      'skeleton-king',
    ],
    hunt: [
      'Frostnotar',
      'Frost Notary',
      'Versiegelt markierte Teilflächen, bevor ein schwerer Siegelstoß folgt. Der freie Weg führt direkt an die offene Archivkante.',
      'Seals marked sections before a heavy stamping strike. The clear route leads straight to its exposed archive edge.',
      'frost',
      ['pool', 'cleave', 'ring'],
      'construct',
    ],
    boss: [
      'Der Bibliothekar',
      'The Librarian',
      'Suchstrahlen, Regalwellen und ein gefrorener Gedächtniskern schützen das Originalregister. Nach jeder großen Suche wird die Linse warm.',
      'Search beams, shelf waves and a frozen memory core protect the original register. Its lens warms after each major search.',
      'frost',
      ['line', 'burst', 'pool', 'summon', 'ring'],
      'skeleton-king',
    ],
  },
  {
    name: ['Uhrwerkstadt', 'Clockwork Borough'],
    description: [
      'Messingstege und cyanfarbene Fenster verbinden Wohnungen mit einer unablässigen Maschine. Die Bewohner kennen jede Minute, aber keinen eigenen Morgen.',
      'Brass walkways and cyan windows join homes to a relentless machine. The residents know every minute but have no tomorrow of their own.',
    ],
    story: [
      'Ennos frühere Durchläufe laufen als Verhaltensmodelle in den Uhrwerken weiter. Eine freie Minute ist kein Zeitzauber: Sie entsteht, wenn jemand den zentralen Zeitplan nicht mehr befolgt.',
      'Enno’s earlier runs continue as behavioural models in the clockwork. A free minute is no time spell: it begins when someone stops obeying the central timetable.',
    ],
    colors: ['#3d4036', '#2b302b', '#9bcfc5', '#d1c69c'],
    mechanic: 'cycles',
    mobs: [
      [
        'Zeittick',
        'Time Tick',
        'flanker',
        'bleed',
        'rat',
        'Seine Sprünge folgen einem regelmäßigen Takt. Bewege dich in der Pause statt im angekündigten Auftakt.',
        'Its leaps follow a regular rhythm. Move during the pause rather than the telegraphed upbeat.',
      ],
      [
        'Zahnradläufer',
        'Gear Runner',
        'chaser',
        'physical',
        'warrior',
        'Dreht vor dem Sprint ein sichtbares Zahnrad hoch. Nach dem Durchlauf muss die Feder neu gespannt werden.',
        'Winds a visible gear before sprinting. Its spring must be rewound after each run.',
      ],
      [
        'Pendelschütze',
        'Pendulum Shooter',
        'shooter',
        'shock',
        'skeleton-hunter',
        'Feuert in einer festen Schwingungsfolge. Nutze den Richtungswechsel für eine sichere Querbewegung.',
        'Fires in a fixed swinging sequence. Use its change of direction to cross safely.',
      ],
      [
        'Reparaturspinne',
        'Repair Spider',
        'support',
        'shield',
        'rat',
        'Zieht beschädigte Wachen zusammen. Trenne die Reparaturgruppe mit einem Angriff auf ihren kleinen Mittelpunkt.',
        'Gathers damaged guards together. Break the repair group with a strike at its small centre.',
      ],
      [
        'Federling',
        'Springling',
        'ambusher',
        'stagger',
        'goblin-beast',
        'Eine gespannte Feder verrät den Sprung. Nach dem Aufprall braucht der kleine Körper Zeit zum Aufrichten.',
        'A taut spring reveals its jump. After landing, its small body needs time to rise.',
      ],
      [
        'Schienenkrabbe',
        'Rail Crab',
        'tank',
        'physical',
        'construct',
        'Beschleunigt nur in einer klaren Gleislinie. Stelle dich früh daneben und nutze die schwere Bremsphase.',
        'Accelerates only along a clear rail line. Step aside early and use its heavy braking phase.',
      ],
      [
        'Messingvogt',
        'Brass Bailiff',
        'support',
        'shield',
        'necromancer',
        'Hält den Reparaturauftrag über der Formation. Ohne den Vogt müssen die Zahnräder ohne Nachschub weiterlaufen.',
        'Holds the repair order above the formation. Without the bailiff, the gears must run without replenishment.',
      ],
      [
        'Minutenräuber',
        'Minute Thief',
        'controller',
        'frost',
        'bat',
        'Legt kleine langsame Zeitfelder aus. Ihre Grenze ist lesbar; umrunde sie, bevor du wieder zielst.',
        'Places small slowing time fields. Their boundary is readable; go around them before aiming again.',
      ],
    ],
    elites: [
      [
        'Uhrmeister',
        'Clock Master',
        'summoner',
        'shock',
        'skeleton-king',
        'Ruft die nächste Uhrwerkschicht im festen Takt. Ein rechtzeitiger Treffer bricht die ganze Aufstellung.',
        'Calls the next clockwork shift to a fixed beat. A timely hit breaks the whole formation.',
      ],
      [
        'Taktrichter',
        'Beat Judge',
        'controller',
        'stagger',
        'goblin-beast',
        'Synchronisiert die markierten Angriffsfenster. Nach dem gemeinsamen Schlag ist der Raum kurz wirklich still.',
        'Synchronises marked attack windows. After the shared strike, the room is briefly truly quiet.',
      ],
    ],
    guardian: [
      'Der Fahrkartenrichter',
      'Ticket Judge',
      'Prüft eine gerade Gleisroute und schließt mit einem Stempel. Halte die Kreuzung frei, bis das Urteil gefallen ist.',
      'Inspects a straight rail route and ends with a stamp. Keep the crossing clear until judgment is complete.',
      'stagger',
      ['charge', 'line', 'cleave'],
      'construct',
    ],
    hunt: [
      'Rostpendel',
      'Rust Pendulum',
      'Der große Pendelbogen kündigt jede neue Taktfolge an. Gehe mit dem Richtungswechsel in die freie Innenseite.',
      'Its great pendulum arc announces each new rhythm. Move into the open inner side when it changes direction.',
      'physical',
      ['cleave', 'burst', 'charge'],
      'goblin-beast',
    ],
    boss: [
      'Sekundant',
      'The Second',
      'Angekündigte Sprünge, Bahnwechsel und Pausen legen den Synchronkern frei. Der Takt ändert sich sichtbar, bevor eine neue Folge beginnt.',
      'Telegraphed jumps, lane changes and pauses expose its synchronisation core. The beat visibly changes before a new sequence begins.',
      'shock',
      ['charge', 'line', 'burst', 'cleave', 'pool'],
      'skeleton-king',
    ],
  },
  {
    name: ['Spiegelarena', 'Mirror Arena'],
    description: [
      'Obsidianböden und magentafarbene Kameralinsen zeigen eine perfekte Fassung von dir. Der echte Weg führt durch die kleinen Fehler im Bild.',
      'Obsidian floors and magenta camera lenses show a perfect version of you. The real path runs through the small flaws in the image.',
    ],
    story: [
      'SERA hört im Originalprotokoll eine eigene Entscheidung, die aus ihrer Erinnerung entfernt wurde. Der Sender hat nicht nur Teilnehmer bearbeitet. Eine freie Regie braucht deshalb überprüfbare Grenzen.',
      'SERA hears one of her own decisions in the original protocol, erased from her memory. The broadcaster edited more than contestants. A free production desk therefore needs verifiable limits.',
    ],
    colors: ['#37343e', '#262330', '#bf8ba9', '#d5bfc8'],
    mechanic: 'mirrors',
    mobs: [
      [
        'Echo-Klinge',
        'Echo Blade',
        'chaser',
        'bleed',
        'warrior',
        'Wiederholt eine kurze sichtbare Schlagfolge. Halte Abstand bis zum letzten Schnitt, dann ist der Echoarm offen.',
        'Repeats a short visible attack sequence. Stay clear until the final cut, then its echo arm is exposed.',
      ],
      [
        'Prismenschütze',
        'Prism Shooter',
        'shooter',
        'shock',
        'skeleton-hunter',
        'Eine helle Linse zeigt die nächste Schussrichtung. Bewege dich quer zum Prisma und benutze die dunkle Seite.',
        'A bright lens shows the next firing direction. Move across the prism and use its dark side.',
      ],
      [
        'Maskenweber',
        'Mask Weaver',
        'summoner',
        'exposed',
        'necromancer',
        'Webt kleine falsche Stars an den Raumrand. Unterbrich die offene Maske, bevor der Auftritt voll wird.',
        'Weaves small false stars at the room edge. Interrupt its open mask before the performance fills up.',
      ],
      [
        'Reflexbestie',
        'Reflex Beast',
        'tank',
        'physical',
        'goblin-beast',
        'Ihr glänzender Frontpanzer lenkt den Blick. Der langsame Körper kann eine saubere Flanke nicht halten.',
        'Its polished front armour draws your attention. Its slow body cannot hold a clean flank.',
      ],
      [
        'Glasläufer',
        'Glass Runner',
        'flanker',
        'bleed',
        'rat',
        'Seine Kurve endet in einem Splitterhieb. Bleibe außerhalb der hell gezeichneten Bogenkante.',
        'Its curve ends in a shard slash. Stay outside the brightly drawn arc edge.',
      ],
      [
        'Linsenauge',
        'Lens Eye',
        'controller',
        'shock',
        'bat',
        'Schwenkt einen sichtbaren Suchstrahl. Die Rückseite der Linse ist frei, wenn der Strahl weiterzieht.',
        'Sweeps a visible search beam. Its lens rear is exposed when the beam moves on.',
      ],
      [
        'Spiegelspinner',
        'Mirror Spinner',
        'support',
        'shield',
        'construct',
        'Schützt Verbündete unter einer kleinen Spiegelfläche. Naher Druck auf den Spinner trennt die Formation.',
        'Protects allies beneath a small mirror shield. Close pressure on the spinner splits the formation.',
      ],
      [
        'Kulissenfänger',
        'Backdrop Catcher',
        'ambusher',
        'stagger',
        'necromancer',
        'Der Schatten stimmt nicht mit der Kulisse überein. Der verratene Eintritt ist deine Chance auf den ersten Treffer.',
        'Its shadow does not match the scenery. Its betrayed arrival is your chance to land the first hit.',
      ],
    ],
    elites: [
      [
        'Doppelstar',
        'Double Star',
        'summoner',
        'physical',
        'skeleton-king',
        'Seine Kopien beginnen erst nach dem sichtbaren Auftrittssignal. Störe den Star, bevor die zweite Rolle erscheint.',
        'Its copies begin only after a visible entrance signal. Interrupt the star before its second role appears.',
      ],
      [
        'Prismenvogt',
        'Prism Bailiff',
        'controller',
        'shock',
        'goblin-beast',
        'Teilt einen angekündigten Strahlfächer. Zwischen den deutlich markierten Linien bleibt eine freie Route.',
        'Splits a telegraphed beam fan. A clear route remains between the marked lines.',
      ],
    ],
    guardian: [
      'Das Stand-In',
      'The Stand-In',
      'Kopiert eine begrenzte Folge aus Charge und Schnitt. Die echte Erholungsphase lässt sich nicht wegspiegeln.',
      'Copies a limited charge-and-slash sequence. It cannot mirror away its genuine recovery phase.',
      'physical',
      ['charge', 'cleave', 'burst'],
      'warrior',
    ],
    hunt: [
      'Splitterstar',
      'Shard Star',
      'Falsche Spiegel stehen sichtbar neben der echten Linse. Bewege dich durch die Lücke im Strahlfächer und zerbrich die Quelle.',
      'False mirrors stand visibly beside its real lens. Move through the beam fan’s gap and break the source.',
      'shock',
      ['burst', 'line', 'summon'],
      'goblin-beast',
    ],
    boss: [
      'Das Publikum',
      'The Audience',
      'Zuschauergruppen, geliehene Angriffe und ein offener Regiekern bilden die letzte Illusion. Die sichtbare Reihenfolge sagt dir, welche Rolle gerade gefährlich ist.',
      'Audience groups, borrowed attacks and an exposed production core form the final illusion. The visible sequence tells you which role is dangerous now.',
      'exposed',
      ['summon', 'charge', 'burst', 'ring', 'line'],
      'skeleton-king',
    ],
  },
  {
    name: ['Knochennetz', 'Bone Network'],
    description: [
      'Elfenbeinfarbene Träger tragen pulsierende Kabel und leise Stimmen. Das Rückgrat des Senders ist zugleich die Lebensleitung seiner Gefangenen.',
      'Ivory supports carry pulsing cables and quiet voices. The broadcaster’s spine is also its prisoners’ lifeline.',
    ],
    story: [
      'Die Archive sind an lebende Knoten gebunden. Ein einfaches Abschalten würde die Menschen löschen, die du retten willst. Mira und Zuv bereiten deshalb eine kontrollierte Übertragung vor.',
      'Archives are bound to living nodes. A simple shutdown would erase the people you intend to save. Mira and Zuv therefore prepare a controlled transfer.',
    ],
    colors: ['#44403c', '#2c2b30', '#b59cc9', '#d2c7b4'],
    mechanic: 'nodes',
    mobs: [
      [
        'Nervensucher',
        'Nerve Seeker',
        'chaser',
        'shock',
        'rat',
        'Folgt dem stärksten Bewegungssignal. Eine klare Flanke lässt seinen kurzen Suchansturm ins Leere gehen.',
        'Follows the strongest movement signal. A clean sidestep makes its short searching charge miss.',
      ],
      [
        'Knochenwächter',
        'Bone Guard',
        'tank',
        'physical',
        'construct',
        'Trägt eine breite Rippenplatte. Der kurze Stillstand nach dem Schlag macht seine Kabelseite erreichbar.',
        'Carries a broad rib plate. Its brief pause after striking makes its cable side reachable.',
      ],
      [
        'Pulswerfer',
        'Pulse Thrower',
        'shooter',
        'shock',
        'skeleton-hunter',
        'Jeder leuchtende Knoten bereitet ein Projektil vor. Stoppe die Sichtlinie, bevor der Puls den Raum durchzieht.',
        'Every glowing node prepares a projectile. Break its sightline before the pulse crosses the room.',
      ],
      [
        'Kabelbrut',
        'Cable Brood',
        'summoner',
        'bleed',
        'slime',
        'Teilt kleine Kabelkörper aus. Seine eigene Quelle bleibt während der Teilung frei und angreifbar.',
        'Distributes small cable bodies. Its own source is exposed and vulnerable while dividing.',
      ],
      [
        'Synapsenling',
        'Synapseling',
        'flanker',
        'shock',
        'rat',
        'Greift mit einem kurzen Knotenansturm von außen an. Halte die Seiten der Formation im Blick.',
        'Attacks from outside with a short nodal charge. Keep an eye on the formation’s sides.',
      ],
      [
        'Rippenschütze',
        'Rib Shooter',
        'shooter',
        'physical',
        'skeleton-hunter',
        'Nutzt organische Stützen als Deckung. Eine veränderte Schusslinie nimmt ihm den sicheren Stand.',
        'Uses organic supports for cover. A changed firing angle removes its safe position.',
      ],
      [
        'Transplantat',
        'Transplant',
        'support',
        'shield',
        'necromancer',
        'Flickt benachbarte Netzträger. Ein Treffer auf den offenen Anschluss bricht den Reparaturfluss.',
        'Patches nearby network supports. A hit on its open connector breaks the repair flow.',
      ],
      [
        'Signalzecke',
        'Signal Tick',
        'controller',
        'exposed',
        'bat',
        'Bindet einen kleinen klar markierten Fokusbereich. Verlasse die Zone und gib dem Signal keinen dauerhaften Halt.',
        'Binds a small, clearly marked focus area. Leave the zone and give its signal no permanent hold.',
      ],
    ],
    elites: [
      [
        'Netzchirurg',
        'Network Surgeon',
        'support',
        'shield',
        'skeleton-king',
        'Verteilt Reparaturpuls und Abschirmung. Die sichtbare Naht des Armes ist sein verwundbares Operationsfenster.',
        'Distributes repair pulses and shielding. The visible seam in its arm is its vulnerable operating window.',
      ],
      [
        'Pulsarchon',
        'Pulse Archon',
        'controller',
        'shock',
        'goblin-beast',
        'Verbindet zwei leuchtende Leitungszonen. Die freie Außenroute führt direkt hinter seinen Taktgeber.',
        'Connects two glowing conduit zones. The clear outer route leads directly behind its pacemaker.',
      ],
    ],
    guardian: [
      'Knotenarzt',
      'Node Surgeon',
      'Repariert offen liegende Leitungen und schneidet im gleichen Rhythmus. Unterbrich den Puls und nutze die freie Kabelseite.',
      'Repairs exposed conduits and cuts to the same rhythm. Interrupt the pulse and use its clear cable side.',
      'shock',
      ['summon', 'cleave', 'line'],
      'skeleton-king',
    ],
    hunt: [
      'Archivverschlinger',
      'Archive Devourer',
      'Verschluckt temporäre Kopien, bevor ein schwerer Ringpuls kommt. Im anschließenden offenen Fenster lassen sich die Stimmen zurückholen.',
      'Swallows temporary copies before a heavy ring pulse. The following opening lets you reclaim their voices.',
      'corrosion',
      ['summon', 'pool', 'burst'],
      'goblin-beast',
    ],
    boss: [
      'Wirbelsender',
      'Spine Transmitter',
      'Knotenbarrieren und Leitungswellen sichern die Archivträger. Schlage in den offenen Takt, damit die vorbereitete Übertragung intakt bleibt.',
      'Nodal barriers and conduit waves protect the archive supports. Strike during the open beat to preserve the prepared transfer.',
      'shock',
      ['summon', 'pool', 'line', 'ring', 'cleave'],
      'skeleton-king',
    ],
  },
  {
    name: ['Nullsignal', 'Null Signal'],
    description: [
      'Verlassene Sendeschränke stehen zwischen kleinen cyanfarbenen Lichtinseln. Selbst das Rauschen hat aufgehört. Jede Gefahr bleibt trotzdem sichtbar.',
      'Abandoned broadcast cabinets stand between small cyan islands of light. Even the static has stopped. Every danger remains visible nonetheless.',
    ],
    story: [
      'Die Freie Frequenz braucht eine Leitung außerhalb des Sendernetzes. Oris legt sein Prüfprotokoll offen: Das Konsortium verletzt selbst die Regeln, mit denen es die Gefangenen bindet.',
      'The Free Frequency needs a conduit outside the broadcast network. Oris opens its audit protocol: the Consortium violates the very rules it uses to bind its prisoners.',
    ],
    colors: ['#303a39', '#1c282a', '#86c7cb', '#a8c9c6'],
    mechanic: 'signal',
    mobs: [
      [
        'Ausfalldrohne',
        'Outage Drone',
        'shooter',
        'shock',
        'bat',
        'Sendet sichtbare Einzelpulse ohne Ton. Beobachte die helle Linse und halte die Querroute offen.',
        'Sends visible single pulses without sound. Watch its bright lens and keep a cross-route open.',
      ],
      [
        'Nullgeist',
        'Null Ghost',
        'ambusher',
        'frost',
        'necromancer',
        'Der dunkle Körper hinterlässt helle Eintrittsspuren. Warte die angekündigte Position ab, bevor du zuschlägst.',
        'Its dark body leaves bright entry traces. Wait for the announced position before striking.',
      ],
      [
        'Antennenjäger',
        'Antenna Hunter',
        'chaser',
        'shock',
        'skeleton-hunter',
        'Richtet seine Antenne vor jedem Sprint auf dich. Eine Seitwärtsbewegung genügt, wenn du sie früh erkennst.',
        'Points its antenna at you before every sprint. A sidestep is enough if you read it early.',
      ],
      [
        'Schweigewächter',
        'Silent Guard',
        'tank',
        'physical',
        'construct',
        'Ein heller Rahmen markiert den schweren Schlag. Sein langsames Aufrichten bietet eine gut sichtbare offene Seite.',
        'A bright outline marks its heavy strike. Its slow rise provides a clearly visible open side.',
      ],
      [
        'Flüsterläufer',
        'Whisper Runner',
        'flanker',
        'bleed',
        'rat',
        'Auch sein getarnter Lauf hinterlässt leuchtende Spuren. Verfolge die Spur, nicht die dunkle Körpermitte.',
        'Even its concealed run leaves glowing traces. Follow the trail, not its dark body centre.',
      ],
      [
        'Senderkrabbe',
        'Transmitter Crab',
        'controller',
        'shock',
        'construct',
        'Schiebt periodische Signalbänder durch den Raum. Die breite Lücke zwischen zwei Bändern ist der sichere Weg.',
        'Pushes periodic signal bands across the room. The broad gap between two bands is the safe route.',
      ],
      [
        'Blinde Kamera',
        'Blind Camera',
        'shooter',
        'exposed',
        'bat',
        'Ihr Suchkegel bleibt als feste Form sichtbar. Nutze die freie Seite statt in das Zentrum zu treten.',
        'Its search cone remains a fixed visible shape. Use the free side instead of entering its centre.',
      ],
      [
        'Störschwarm',
        'Jamming Swarm',
        'support',
        'frost',
        'slime',
        'Flimmert nur im eigenen klar begrenzten Radius. Ein Angriff auf die Quelle beendet den störenden Fokus.',
        'Flickers only within its clearly bounded radius. An attack on the source ends its disruptive focus.',
      ],
    ],
    elites: [
      [
        'Störkommissar',
        'Jamming Commissioner',
        'summoner',
        'shock',
        'skeleton-king',
        'Ruft eine gemeldete Störgruppe. Die helle Kommandoleiste gibt dir Zeit, den nächsten Ruf zu unterbrechen.',
        'Calls an announced jamming group. Its bright command strip gives you time to interrupt the next call.',
      ],
      [
        'Sendeverweigerer',
        'Broadcast Refuser',
        'controller',
        'frost',
        'goblin-beast',
        'Öffnet und schließt klar angekündigte Signalinseln. Verlasse die markierte Fläche vor dem letzten Lichtwechsel.',
        'Opens and closes clearly telegraphed signal islands. Leave the marked area before the final change of light.',
      ],
    ],
    guardian: [
      'Antennenfürst',
      'Antenna Prince',
      'Schwenkt mehrere sichtbare Signalbänder, dann schlägt ein fester Ring. Die sichere Außenkante bleibt erreichbar.',
      'Sweeps several visible signal bands, then releases a fixed ring. The safe outer edge stays reachable.',
      'shock',
      ['line', 'burst', 'pool'],
      'skeleton-king',
    ],
    hunt: [
      'Der ungesendete Ruf',
      'The Unbroadcast Call',
      'Sein Echo wiederholt die letzte sichtbare Linie. Nach der Antwort ist der dunkle Mittelpunkt offen.',
      'Its echo repeats the last visible line. After the answer, its dark centre is exposed.',
      'frost',
      ['line', 'ring', 'charge'],
      'goblin-beast',
    ],
    boss: [
      'Stille',
      'Silence',
      'Sichtbare Pulse trennen Lichtinseln und bauen ein Echo auf. Alle Warnungen erscheinen am Boden, selbst wenn der Raum keinen Ton mehr hat.',
      'Visible pulses split islands of light and build an echo. Every warning appears on the floor, even when the room has no sound left.',
      'frost',
      ['ring', 'line', 'pool', 'burst', 'charge'],
      'skeleton-king',
    ],
  },
  {
    name: ['Sendekern', 'Broadcast Core'],
    description: [
      'Weiße Regiefelder, schwarzer Stein und rote Leitlinien führen zur großen Konsole. Hier wird entschieden, wessen Geschichte morgen noch existiert.',
      'White production panels, black stone and red guide lines lead to the great console. Here tomorrow’s surviving stories are decided.',
    ],
    story: [
      'Veyl bietet Stabilität als Preis für bleibenden Besitz an. Die Archive sind gesichert, die Beweise unabhängig übertragen. Du kannst nun befreien, übernehmen oder einen überprüfbaren neuen Vertrag schließen.',
      'Veyl offers stability in exchange for continued ownership. The archives are secured and the evidence transmitted independently. You can now free them, take control or establish a verifiable new contract.',
    ],
    colors: ['#42413e', '#26292a', '#d66b58', '#d7cbb6'],
    mechanic: 'core',
    mobs: [
      [
        'Protokollritter',
        'Protocol Knight',
        'tank',
        'physical',
        'warrior',
        'Seine schwere Schlagfolge kombiniert bekannte Frontmuster. Eine saubere Flanke funktioniert weiterhin.',
        'Its heavy attack sequence combines familiar frontal patterns. A clean flank still works.',
      ],
      [
        'Kernsplitter',
        'Core Shard',
        'shooter',
        'shock',
        'bat',
        'Der kleine Kern lädt einen sichtbaren Strahl. Die alten Regeln für Deckung und Querbewegung gelten auch hier.',
        'Its small core charges a visible beam. The old rules for cover and crossing still apply here.',
      ],
      [
        'Regieschatten',
        'Director Shadow',
        'ambusher',
        'bleed',
        'necromancer',
        'Der angekündigte Kulissenwechsel verrät seine Eintrittsseite. Bleibe ruhig und greife nach dem letzten Schnitt an.',
        'Its telegraphed scene change reveals its entry side. Stay calm and attack after its final cut.',
      ],
      [
        'Archivar-Konstrukt',
        'Archivist Construct',
        'support',
        'shield',
        'construct',
        'Flickt die letzte Schutzfront des Senders. Unterbrich den offenen Lesearm, bevor sich die Ritter neu ordnen.',
        'Patches the broadcaster’s last defensive front. Interrupt its open reading arm before the knights regroup.',
      ],
      [
        'Befehlsklinge',
        'Command Blade',
        'chaser',
        'stagger',
        'skeleton-hunter',
        'Ein rotes Kommando zeigt ihre geradlinige Charge. Sie kann den Befehl nicht mitten im Lauf ändern.',
        'A red command shows its straight charge. It cannot change orders halfway through its run.',
      ],
      [
        'Übertragungswächter',
        'Transfer Guard',
        'tank',
        'shock',
        'goblin-beast',
        'Dreht einen sichtbaren Schutzbogen. Die freie Hälfte der Arena erlaubt den Wechsel hinter seine Leitung.',
        'Turns a visible guard arc. The arena’s free half allows you to move behind its conduit.',
      ],
      [
        'Lizenzjäger',
        'Licence Hunter',
        'controller',
        'exposed',
        'rat',
        'Seine Bindung braucht eine kleine markierte Zone. Verlasse das Feld, bevor der Anspruch vollständig wird.',
        'Its binding requires a small marked zone. Leave the field before its claim is complete.',
      ],
      [
        'Archivfalter',
        'Archive Moth',
        'summoner',
        'shield',
        'bat',
        'Ein kurzer Schutzruf öffnet neue Kernkopien. Die helle Quelle ist während des Rufs leicht erreichbar.',
        'A short protective call opens new core copies. Its bright source is easy to reach during the call.',
      ],
    ],
    elites: [
      [
        'Letzter Vollstrecker',
        'Final Enforcer',
        'tank',
        'physical',
        'skeleton-king',
        'Der letzte Vertragswall ist schwer, aber ehrlich angekündigt. Deine gelernten Ausweichfenster tragen bis zum Kern.',
        'The last contract wall is heavy but honestly telegraphed. Your learned dodge windows carry you to the core.',
      ],
      [
        'Kernelhüter',
        'Kernel Keeper',
        'controller',
        'shock',
        'goblin-beast',
        'Mischt bekannte Pulse, Linien und Sperrflächen. Jede neue Folge beginnt mit derselben lesbaren Vorbereitung.',
        'Mixes familiar pulses, lines and blocked zones. Each new sequence begins with the same readable preparation.',
      ],
    ],
    guardian: [
      'Produktionsrat',
      'Production Council',
      'Drei kleine Teilinstanzen teilen sich einen sichtbaren Befehlstakt. Zuerst die Linie, dann die Welle, zuletzt der offene Kommandokern.',
      'Three small sub-instances share a visible command beat. First the line, then the wave, finally the exposed command core.',
      'shock',
      ['line', 'summon', 'burst'],
      'construct',
    ],
    hunt: [
      'Der letzte Statist',
      'The Last Extra',
      'Ein letzter geliehener Auftritt kombiniert bekannte Rollen. Seine starken Muster bleiben begrenzt und lassen eine echte Pause.',
      'One last borrowed performance combines familiar roles. Its strong patterns stay limited and leave a real pause.',
      'physical',
      ['charge', 'pool', 'cleave'],
      'goblin-beast',
    ],
    boss: [
      'Direktor Veyl',
      'Director Veyl',
      'Regiekommandos koppeln Sponsorfeuer und Archivbarrieren. Nach jeder klar angekündigten Folge ist der Mensch hinter dem System angreifbar.',
      'Production commands link sponsor fire and archive barriers. After each clearly telegraphed sequence, the person behind the system is vulnerable.',
      'exposed',
      ['line', 'summon', 'charge', 'burst', 'ring', 'cleave', 'pool'],
      'skeleton-king',
    ],
  },
];

const roleHp: Record<Role, number> = {
  chaser: 1,
  flanker: 0.72,
  shooter: 0.82,
  summoner: 1.05,
  tank: 1.85,
  support: 0.95,
  controller: 1.1,
  ambusher: 0.84,
};
const roleSpeed: Record<Role, number> = {
  chaser: 104,
  flanker: 129,
  shooter: 67,
  summoner: 57,
  tank: 52,
  support: 65,
  controller: 55,
  ambusher: 114,
};

export const FLOORS: FloorDef[] = seeds.map((seed, n) => {
  const floor = n + 1,
    p = String(floor).padStart(2, '0');
  const mob = (s: MobSeed, i: number, elite = false): MobDef => ({
    id: `f${p}-${elite ? 'elite' : 'mob'}-${i + 1}`,
    name: t(s[0], s[1]),
    role: s[2],
    element: s[3],
    sprite: s[4],
    description: t(s[5], s[6] ?? s[5]),
    hp: Math.round((42 + floor * 13) * roleHp[s[2]] * (elite ? 2.6 : 1)),
    damage: Math.round((7 + floor * 2.1) * (elite ? 1.65 : 1)),
    speed: roleSpeed[s[2]] + (elite ? 7 : 0),
    color: elite ? seed.colors[3] : seed.colors[2],
    elite,
  });
  const boss = (s: BossSeed, kind: 'guardian' | 'hunt' | 'boss'): BossDef => ({
    id: `f${p}-${kind}`,
    name: t(s[0], s[1]),
    description: t(s[2], s[3]),
    element: s[4],
    patterns: s[5],
    sprite: s[6] ?? 'skeleton-king',
    hp: Math.round((floor * 98 + 440) * (kind === 'boss' ? 2.1 : 1)),
    damage: Math.round((12 + floor * 2.5) * (kind === 'boss' ? 1.2 : 1)),
    color: kind === 'boss' ? seed.colors[2] : seed.colors[3],
    unique: `unique-${kind}-${p}`,
  });
  return {
    id: `floor-${p}`,
    index: floor,
    act: Math.ceil(floor / 3),
    name: t(...seed.name),
    description: t(...seed.description),
    story: t(...seed.story),
    colors: {
      floor: seed.colors[0],
      wall: seed.colors[1],
      accent: seed.colors[2],
      light: seed.colors[3],
    },
    mechanic: seed.mechanic,
    mobs: seed.mobs.map((s, i) => mob(s, i)),
    elites: seed.elites.map((s, i) => mob(s, i, true)),
    minibosses: [boss(seed.guardian, 'guardian'), boss(seed.hunt, 'hunt')],
    boss: boss(seed.boss, 'boss'),
  };
});
