import type { AffixDef, GearSlot, ItemDef, RecipeDef, SetDef, Text } from '../game/types';

const t = (de: string, en: string): Text => ({ de, en });
const slots: GearSlot[] = [
  'weapon',
  'offhand',
  'head',
  'body',
  'hands',
  'feet',
  'amulet',
  'talisman',
];
const slotNames: Record<GearSlot, Text> = {
  weapon: t('Waffe', 'Weapon'),
  offhand: t('Nebenhand', 'Off-hand'),
  head: t('Kopfschutz', 'Headgear'),
  body: t('Körperrüstung', 'Body armour'),
  hands: t('Handschutz', 'Handgear'),
  feet: t('Stiefel', 'Boots'),
  amulet: t('Amulett', 'Amulet'),
  talisman: t('Talisman', 'Talisman'),
};
const effectText: Record<string, Text> = {
  lifesteal: t(
    'Lebensraub: Treffer geben zusätzlich 2,5 % ihres Schadens als Leben zurück.',
    'Life steal: hits additionally return 2.5% of their damage as health.',
  ),
  chain: t(
    'Kette: 18 % Chance auf Folgetreffer gegen bis zu zwei nahe Gegner mit je 40 % Trefferschaden.',
    'Chain: 18% chance of follow-up strikes against up to two nearby enemies, each dealing 40% hit damage.',
  ),
  burn: t(
    'Brennen: Treffer entzünden das Ziel für drei Sekunden und verursachen weiteren Schaden über Zeit.',
    'Burn: hits ignite the target for three seconds, causing additional damage over time.',
  ),
  frost: t(
    'Frost: Treffer verlangsamen das Ziel für drei Sekunden.',
    'Frost: hits slow the target for three seconds.',
  ),
  thorns: t(
    'Dornen: Ein Angreifer erhält 25 % seines zugefügten Schadens zurück.',
    'Thorns: an attacker receives 25% of the damage it inflicted back.',
  ),
  'dodge-shield': t(
    'Ausweichschutz: Ausweichen erzeugt 12 Schutzpunkte, bis höchstens 60.',
    'Dodge shield: dodging creates 12 shield points, up to a maximum of 60.',
  ),
  turret: t(
    'Geschütz: 10 % Trefferchance auf drei Sekunden zusätzliches Gerätefeuer.',
    'Turret: hits have a 10% chance to create three seconds of additional device fire.',
  ),
  execute: t(
    'Vollstreckung: +35 % Schaden gegen Gegner unter 20 % Leben.',
    'Execution: +35% damage against enemies below 20% health.',
  ),
  crit: t(
    'Präzision: +8 Prozentpunkte kritische Trefferchance.',
    'Precision: +8 percentage points of critical-hit chance.',
  ),
  healing: t('Erholung: +15 % Heilwirkung.', 'Recovery: +15% healing.'),
  nix: t('Begleiterhilfe: +25 % NIX-Schaden.', 'Companion support: +25% NIX damage.'),
  gold: t('Verwertung: +20 % Schrottgewinn.', 'Recovery value: +20% scrap income.'),
  speed: t('Freier Schritt: +10 % Bewegungstempo.', 'Free step: +10% movement speed.'),
  armor: t('Verstärkter Schutz: +8 Rüstung.', 'Reinforced protection: +8 armour.'),
  stagger: t(
    'Taumeln: Treffer unterbrechen Gegner kurz für eine halbe Sekunde.',
    'Stagger: hits briefly interrupt enemies for half a second.',
  ),
};

type UniqueSeed = [string, string, string, string, string, string, number?];
const bossUniques: UniqueSeed[] = [
  [
    'Einlass ohne Rückkehr',
    'Admission Without Return',
    'Der abgebrochene Schlüssel des Pförtners öffnet keine Tür mehr. Er passt erstaunlich gut in die Schwachstelle einer Rüstung.',
    'The gatekeeper’s broken key opens no more doors. It fits surprisingly well into the weak point of armour.',
    'stagger',
    'damage',
  ],
  [
    'Mutterleitung',
    'Mother Line',
    'Ein Seitenventil der Pumpe. Zum ersten Mal fließt die Reserve nicht an den Eigentümer zurück.',
    'A side valve from the pump. For the first time, the reserve does not flow back to its owner.',
    'healing',
    'armor',
  ],
  [
    'Krone der nicht verkauften Namen',
    'Crown of Unsold Names',
    'Jede kleine Platte trägt einen Namen statt eines Preises. Der Sammler fand diese Sortierung unwirtschaftlich.',
    'Every small plate bears a name rather than a price. The Collector found this arrangement uneconomical.',
    'gold',
    'maxResource',
  ],
  [
    'Ungeschnittene Fassung',
    'Unedited Edition',
    'Eine Jacke voller echter Randnotizen. Myr hätte lieber das entfernte Material getragen.',
    'A jacket full of genuine marginal notes. Myr would rather have worn the deleted material.',
    'frost',
    'maxHp',
  ],
  [
    'Hand der letzten Serie',
    'Hand of the Final Batch',
    'Die Finger wurden für hundert identische Arbeitsschritte gebaut. Jetzt darf jeder Griff anders ausfallen.',
    'These fingers were built for a hundred identical work steps. Now every grip may turn out differently.',
    'burn',
    'damage',
  ],
  [
    'Siegerweg',
    'Champion’s Route',
    'Rheas schwerste Stiefel: leicht genug, sobald sie nicht mehr für einen Sponsor stillstehen muss.',
    'Rhea’s heaviest boots: light enough once she no longer has to stand still for a sponsor.',
    'dodge-shield',
    'speed',
  ],
  [
    'Originalanhänger',
    'Original Pendant',
    'Im Inneren steht ein Datum ohne Bearbeitungsstempel. Herkunft ist ein Anhaltspunkt, kein Befehl.',
    'Inside is a date without an edit stamp. Origin is a reference, not an order.',
    'crit',
    'crit',
  ],
  [
    'Die freie Sekunde',
    'The Free Second',
    'Ein Zahnrad ohne zugeteilten Takt. Seine winzige Pause passt nicht in den Fahrplan.',
    'A gear with no assigned rhythm. Its tiny pause fits no timetable.',
    'speed',
    'cooldown',
  ],
  [
    'Urteil ohne Publikum',
    'Judgment Without an Audience',
    'Eine Bühnenklinge, deren Gewicht auch ohne Applaus stimmt. Sie wartet nicht auf den besten Kamerawinkel.',
    'A stage blade with the right weight even without applause. It does not wait for the best camera angle.',
    'execute',
    'damage',
  ],
  [
    'Offene Rippe',
    'Open Rib',
    'Ein Teil des Wirbelsenders trägt jetzt die Leitung nach außen. Nicht jede getrennte Verbindung ist eine Wunde.',
    'A part of the Spine Transmitter now carries the conduit outward. Not every severed connection is a wound.',
    'thorns',
    'armor',
  ],
  [
    'Hörer der Stille',
    'Listener of Silence',
    'Der Sender verstummte. Die matte Hörschale empfängt trotzdem jede Antwort.',
    'The transmitter fell silent. This dull listening shell still receives every answer.',
    'nix',
    'maxHp',
  ],
  [
    'Mantel der offenen Regie',
    'Coat of Open Production',
    'Veyls letzter Leitmantel besitzt nun einen sichtbaren Abschalter. Schutz braucht eine Grenze, die andere prüfen können.',
    'Veyl’s final control coat now has a visible off switch. Protection needs a limit others can verify.',
    'armor',
    'armor',
  ],
];

const minibossUniques: UniqueSeed[] = [
  [
    'Zulassungsstempel',
    'Admission Stamp',
    'Q-17 prüfte jedes Handgelenk. Dieser Stempel bestätigt nun nur noch, dass du selbst zugestimmt hast.',
    'Q-17 inspected every wrist. This stamp now confirms only that you consented yourself.',
    'stagger',
    'damage',
  ],
  [
    'Geerdete Fangspule',
    'Grounded Catch Coil',
    'Die Spule des Kabelgreifs trägt keinen Zugbefehl mehr. Der Strom findet trotzdem das nächste Ziel.',
    'The Cable Gryphon’s coil carries no pull order now. The current still finds the next target.',
    'chain',
    'speed',
  ],
  [
    'Doppelventil-Amulett',
    'Twin-Valve Amulet',
    'Zwei kleine Ventile einigen sich darauf, gleichzeitig loszulassen. Ein überraschend nützlicher Vertrag.',
    'Two small valves agree to release together. A surprisingly useful agreement.',
    'healing',
    'regen',
  ],
  [
    'Fettfangfilter',
    'Grease-Maw Filter',
    'Fängt mehr als Schlamm auf. Die alten Forderungen bleiben draußen, die verwendbare Kraft kommt hindurch.',
    'Catches more than sludge. Old claims stay outside while usable strength passes through.',
    'lifesteal',
    'lifesteal',
  ],
  [
    'Kransegen',
    'Crane Blessing',
    'Die Kranheilige trug jeden Brocken allein. Dieser Splitter verteilt das Gewicht des nächsten Schlags.',
    'The Crane Saint carried every load alone. This fragment shares the weight of the next strike.',
    'stagger',
    'damage',
  ],
  [
    'Quittung für geliehene Wut',
    'Receipt for Borrowed Rage',
    'Bezahlte Wut kann zurückgefordert werden. Bitte behalten Sie den zerknitterten Beleg.',
    'Paid-for rage may be reclaimed. Please keep the crumpled receipt.',
    'thorns',
    'armor',
  ],
  [
    'Mikrofon des Widerspruchs',
    'Microphone of Dissent',
    'Seine erste unzensierte Aufnahme ist ein einzelnes Nein. Die Redaktion fand den Pegel unangemessen.',
    'Its first uncensored recording is a single no. The newsroom found the volume inappropriate.',
    'stagger',
    'maxResource',
  ],
  [
    'Kapsel des Orakels',
    'Oracle’s Capsule',
    'Das Orakel sah viele Morgen. In dieser Kapsel bleibt gerade genug Kälte für den nächsten sicheren Schritt.',
    'The Oracle saw many mornings. This capsule keeps just enough cold for the next safe step.',
    'frost',
    'maxHp',
  ],
  [
    'Kalte Krone',
    'Cold Crown',
    'Die Krone hielt den Schlackenkönig auf Temperatur. Ein unabhängiger Kühlkreis macht sie nun tragbar.',
    'This crown kept the Slag King at temperature. An independent cooling circuit now makes it wearable.',
    'frost',
    'damage',
  ],
  [
    'Handschuhe der Nachtschicht',
    'Night-Shift Gloves',
    'Keine Arbeitszeile verlangt mehr, dass diese Hände zuerst den Ofen versorgen.',
    'No work order now demands that these hands feed the furnace first.',
    'burn',
    'speed',
  ],
  [
    'Versicherung gegen Kleingedrucktes',
    'Insurance Against Small Print',
    'Deckt ausdrücklich den Augenblick zwischen Frage und Zustimmung. Ein seltener ehrlicher Absatz.',
    'Explicitly covers the moment between a question and consent. A rare honest paragraph.',
    'dodge-shield',
    'armor',
  ],
  [
    'Rabatt auf den Untergang',
    'Discount on Doom',
    'Der Graf versprach einen günstigeren letzten Tag. Die Rückseite nennt jetzt den wirklichen Preis.',
    'The Count promised a cheaper final day. The reverse now states the actual price.',
    'execute',
    'damage',
  ],
  [
    'Band Null',
    'Volume Zero',
    'Ein Registerband vor der ersten Ausgabe. Jede spätere Behauptung muss sich an seinem leeren Rand messen.',
    'A register volume before the first edition. Every later claim must face its empty margin.',
    'crit',
    'crit',
  ],
  [
    'Siegelbrecher',
    'Seal Breaker',
    'Die Spitze passt genau in den Frostnotarstempel. Manche Schlösser bestehen nur aus sehr festem Vertrauen.',
    'The tip fits exactly into the Frost Notary’s stamp. Some locks are made only of very firm trust.',
    'frost',
    'damage',
  ],
  [
    'Notausgang auf Rollen',
    'Emergency Exit on Wheels',
    'Der Fahrkartenrichter hätte diese Route nie zugelassen. Die Rollen interessieren sich nicht für seinen Fahrplan.',
    'The Ticket Judge would never have approved this route. The wheels do not care about its timetable.',
    'dodge-shield',
    'speed',
  ],
  [
    'Pendelgewicht',
    'Pendulum Weight',
    'Nach dem letzten Ausschlag bleibt ein kurzer ruhiger Punkt. Genau dort lohnt sich ein eigener Schritt.',
    'After the final swing comes a brief still point. That is precisely where your own step belongs.',
    'stagger',
    'cooldown',
  ],
  [
    'Maske des zweiten Auftritts',
    'Mask of the Second Entrance',
    'Das Stand-In versuchte, jeden Fehler zu kopieren. Diese Maske kopiert lieber den guten Rückweg.',
    'The Stand-In tried to copy every mistake. This mask would rather copy a good retreat.',
    'dodge-shield',
    'damage',
  ],
  [
    'Prismenkern',
    'Prism Core',
    'Ein echter Kern aus einem Raum voller falscher Linsen. Seine Folgetreffer brauchen keine Spiegelrolle.',
    'A real core from a room full of false lenses. Its follow-up strikes need no mirror role.',
    'chain',
    'armor',
  ],
  [
    'Einweg-Kronzeuge',
    'Disposable Star Witness',
    'Ein gedruckter Zeuge kennt nur eine Aussage: Du warst schon einmal schwerer verletzt und bist zurückgekommen.',
    'A printed witness knows only one statement: you have been hurt worse before, and you returned.',
    'healing',
    'maxHp',
  ],
  [
    'Archiv der verpassten Chancen',
    'Archive of Missed Chances',
    'Die kleinste Randnotiz hält eine zweite Antwort bereit. Der Archivverschlinger hätte sie lieber verschluckt.',
    'The smallest marginal note keeps a second answer ready. The Archive Devourer would rather have swallowed it.',
    'lifesteal',
    'regen',
  ],
  [
    'NIX’ zweiter Gedanke',
    'NIX’s Second Thought',
    'Ein Rest des Antennenfürsten ergänzt den Gedanken eines Schakals. Es enthält ausdrücklich keinen neuen Auftrag.',
    'A remnant of the Antenna Prince supplements a jackal’s thought. It explicitly contains no new assignment.',
    'nix',
    'nix',
  ],
  [
    'Restfrequenz-Talisman',
    'Residual-Frequency Talisman',
    'Ein Ruf, der nie ausgestrahlt wurde, kann dennoch ankommen. Das kleine Funkteil bewahrt seine Antwort.',
    'A call that was never broadcast can still arrive. This small radio component preserves its answer.',
    'chain',
    'elemental',
  ],
  [
    'Letzte Freigabe',
    'Final Approval',
    'Der Produktionsrat hat drei Stempel benötigt. Hier steht nur eine gut sichtbare eigene Unterschrift.',
    'The Production Council needed three stamps. Here there is only one clearly visible signature of your own.',
    'armor',
    'armor',
  ],
  [
    'Der letzte saubere Löffel',
    'The Last Clean Spoon',
    'Ein Statist hat ihn bis zum Schluss bewahrt. Manchmal ist die überzeugendste Zukunft eine brauchbare Mahlzeit.',
    'An extra kept it until the end. Sometimes the most convincing future is a usable meal.',
    'healing',
    'healing',
  ],
];

const questUniques: UniqueSeed[] = [
  [
    'Marke der verschwundenen Schicht',
    'Badge of the Vanished Shift',
    'Der Name wurde aus der Wartungsliste gelöscht. Du trägst die kleine Metallzeile trotzdem weiter.',
    'The name was erased from the maintenance list. You carry its small metal line onwards anyway.',
    'gold',
    'damage',
  ],
  [
    'Kamera mit geschlossenem Auge',
    'Camera with a Closed Eye',
    'Das Gehäuse schützt noch, aber die Aufnahmeleitung ist bewusst getrennt.',
    'The casing still protects, but its recording lead has deliberately been severed.',
    'armor',
    'armor',
  ],
  [
    'Filter der ehrlichen Klinik',
    'Filter of the Honest Clinic',
    'Ein sauberer Filter aus einem Rettungsauftrag. Seine Ausgabe besitzt kein Sponsorlogo.',
    'A clean filter from a rescue assignment. Its outlet bears no sponsor logo.',
    'healing',
    'maxHp',
  ],
  [
    'Rohrpost ohne Absenderkontrolle',
    'Post Without Sender Control',
    'Das Innenfutter trägt eine Nachricht, die ungeschnitten ankam.',
    'Its lining carries a message that arrived unedited.',
    'speed',
    'maxHp',
  ],
  [
    'Werkzeug ohne Pfand',
    'Tool Without a Pledge',
    'Tam hat den Griff zurückgegeben, ohne zuerst eine neue Schuld einzutragen.',
    'Tam returned its handle without first recording a new debt.',
    'stagger',
    'damage',
  ],
  [
    'Schritt des stummen Chors',
    'Step of the Silent Choir',
    'Ein ruhiger Takt ersetzt die verkaufte Stimme. Die Sohlen brauchen keine Bühne.',
    'A steady beat replaces the sold voice. These soles need no stage.',
    'frost',
    'speed',
  ],
  [
    'Ungesendete Randnotiz',
    'Unbroadcast Marginal Note',
    'Der vierte Bericht passte nicht in die Sendung. Seine scharfe Kante passt in deine Tasche.',
    'The fourth report did not fit the broadcast. Its sharp edge fits your pocket.',
    'crit',
    'crit',
  ],
  [
    'Samen ohne Schlagzeile',
    'Seed Without a Headline',
    'Eine geschützte Kultur darf wachsen, ohne vorher ihr späteres Bild zu erklären.',
    'A protected culture may grow without first explaining its later image.',
    'healing',
    'regen',
  ],
  [
    'Hammer der Handarbeit',
    'Hammer of Handwork',
    'Seine ungleichen Schlagspuren beweisen, dass ein Mensch ihn geführt hat.',
    'Its uneven impact marks prove a person wielded it.',
    'stagger',
    'damage',
  ],
  [
    'Restwärmeschild',
    'Residual-Heat Shield',
    'Der abgezweigte Wärmerest hält eine kleine Fläche länger benutzbar.',
    'The diverted heat remnant keeps a small surface usable longer.',
    'burn',
    'armor',
  ],
  [
    'Kleingedruckte Stirn',
    'Small-Print Brow',
    'Die Vertragskosten stehen auf der Außenseite, groß genug für jeden Blick.',
    'The contract costs are on the outside, large enough for anyone to read.',
    'crit',
    'maxResource',
  ],
  [
    'Ohne-Marke-Jacke',
    'Unbranded Jacket',
    'Eine entfernte Werbung hinterließ ein Loch. Mira hat es mit neutralem Stoff geflickt.',
    'A removed advertisement left a hole. Mira patched it with neutral fabric.',
    'dodge-shield',
    'maxHp',
  ],
  [
    'Briefhalter der letzten Stimme',
    'Last-Voice Letter Holder',
    'Ein Verschluss für etwas, das kein öffentlicher Beweis werden muss.',
    'A clasp for something that need not become public evidence.',
    'healing',
    'healing',
  ],
  [
    'Sohle der richtigen Nummer',
    'Sole of the Right Number',
    'Die Kennung gehört nun zu der Person, die tatsächlich in diesen Stiefeln steht.',
    'The designation now belongs to the person actually standing in these boots.',
    'speed',
    'speed',
  ],
  [
    'Wohnschlüssel im Zahnrad',
    'Home Key in the Gear',
    'Ein kleines Zahnrad dreht für einen Wohnraum statt für den nächsten Auftritt.',
    'A small gear turns for a home rather than the next performance.',
    'armor',
    'maxHp',
  ],
  [
    'Unabhängiger Zeitzeuge',
    'Independent Time Witness',
    'Der Zeitstempel wurde außerhalb des Haupttakts gesetzt. Eine kurze Pause war wirklich deine.',
    'The timestamp was made outside the main beat. A brief pause truly belonged to you.',
    'crit',
    'cooldown',
  ],
  [
    'Klinge ohne Applaus',
    'Blade Without Applause',
    'Ein vollendeter Kampf hat auch auf der leeren Bühne Gewicht.',
    'A completed fight has weight even on an empty stage.',
    'execute',
    'damage',
  ],
  [
    'Ungeschnittene Gesprächsscheibe',
    'Uncut Conversation Disc',
    'Diese Platte behält die Pausen. SERA hielt sie zuerst für unnötigen Speicherplatz.',
    'This disc keeps the pauses. SERA initially thought them wasted storage.',
    'chain',
    'armor',
  ],
  [
    'Pulsleser',
    'Pulse Reader',
    'Misst einen lebenden Knoten, ohne ihm zuerst einen Wert zuzuweisen.',
    'Measures a living node without assigning it a value first.',
    'nix',
    'maxHp',
  ],
  [
    'Rücklauf ohne Schmerz',
    'Return Without Pain',
    'Die Naht leitet Kraft zurück, ohne den alten Schmerzkreis zu schließen.',
    'Its seam returns power without closing the old pain circuit.',
    'lifesteal',
    'maxHp',
  ],
  [
    'Licht für eine Stimme',
    'Light for One Voice',
    'Ein Orientierungszeichen aus der dunklen letzten Schicht. Das Licht besitzt keinen Sieger.',
    'A navigation sign from the dark final shift. This light has no winner.',
    'nix',
    'nix',
  ],
  [
    'Für-später-Stiefel',
    'For-Later Boots',
    'Sie tragen die Notfallkopie dorthin, wo ein nächster Tag sie finden kann.',
    'They carry the emergency copy where a next day may find it.',
    'dodge-shield',
    'speed',
  ],
  [
    'Offene Kameralinse',
    'Open Camera Lens',
    'Spiegelt die Beweise ohne vorherige Auswahl. Die Kontrollleitung bleibt sichtbar.',
    'Mirrors the evidence without prior selection. Its control lead stays visible.',
    'crit',
    'crit',
  ],
  [
    'Versprechen mit Ende',
    'Promise with an End',
    'Dieser Vertrag hat eine tatsächlich benutzbare Kündigungsklausel. Das Siegel darf brechen.',
    'This contract has a genuinely usable termination clause. Its seal may break.',
    'gold',
    'gold',
  ],
];

const craftUniques: UniqueSeed[] = [
  [
    'Selbst unterschriebene Handschuhe',
    'Self-Signed Gloves',
    'Tam hat die Zulassungslinie entfernt. Die Hand, die zugreift, entscheidet nun selbst.',
    'Tam removed the admission line. The hand that grips now decides for itself.',
    'crit',
    'damage',
  ],
  [
    'Klinikräder',
    'Clinic Wheels',
    'Zwei kleine Filterrollen bringen Hilfe über nasse Gänge, ohne auf einen Pumpenauftrag zu warten.',
    'Two small filter wheels bring aid over wet corridors without waiting for a pump order.',
    'speed',
    'speed',
  ],
  [
    'Rostchor-Amulett',
    'Rust-Choir Amulet',
    'Ilya und Tam haben die Stimme geschützt statt die ganze Reliquie weiterzuverkaufen.',
    'Ilya and Tam protected the voice rather than reselling the whole relic.',
    'nix',
    'nix',
  ],
  [
    'Lebende Fußnote',
    'Living Footnote',
    'Zuvs Kultur ergänzt einen Bericht, ohne ihn zu überschreiben. Die Wurzel hält nur, solange du sie pflegst.',
    'Zuv’s culture adds to a report without overwriting it. The root holds only while you tend it.',
    'healing',
    'regen',
  ],
  [
    'Miras formfreier Mantel',
    'Mira’s Mould-Free Coat',
    'Ein schützender Mantel, der keine neue Seriennummer erzeugt. Die Gießerei würde ihn nicht freigeben.',
    'A protective coat that produces no new serial number. The foundry would not approve it.',
    'lifesteal',
    'maxHp',
  ],
  [
    'Ausgang ohne Sponsor',
    'Exit Without a Sponsor',
    'Ein Paar Sohlen aus entfernten Werbetafeln. Ihr nächster Weg ist zum ersten Mal frei.',
    'A pair of soles made from removed billboards. Their next route is free for the first time.',
    'dodge-shield',
    'speed',
  ],
  [
    'Leselinse der Zustimmung',
    'Consent Reading Lens',
    'Die Linse öffnet ein Archiv erst, wenn jemand selbst die Frage beantwortet.',
    'This lens opens an archive only when someone answers the question themselves.',
    'crit',
    'maxResource',
  ],
  [
    'Jacke der eigenen Minute',
    'Jacket of Your Own Minute',
    'Die Werkstatt nähte den unabhängigen Takt in den Saum. Kein Wecker kann ihn zurückfordern.',
    'The workshop stitched the independent beat into its hem. No alarm clock can reclaim it.',
    'speed',
    'maxHp',
  ],
  [
    'Ungekürzte Hand',
    'Uncut Hand',
    'Ein Griff mit Platz für Zögern. Präzision braucht nicht immer die kürzeste Bewegung.',
    'A grip with room for hesitation. Precision does not always need the shortest movement.',
    'chain',
    'damage',
  ],
  [
    'Träger eines freien Rücklaufs',
    'Carrier of a Free Return',
    'Die Knotenleitung steckt in einer beweglichen Sohle. Versorgung kann endlich den Raum wechseln.',
    'A node conduit sits in a mobile sole. Provision can finally change rooms.',
    'healing',
    'speed',
  ],
  [
    'Antenne des freiwilligen Auftrags',
    'Antenna of the Voluntary Assignment',
    'NIX hat die Teile ausgewählt. Tam hat ausdrücklich keinen Zielbefehl hineingeschrieben.',
    'NIX chose the components. Tam explicitly wrote no targeting order into them.',
    'nix',
    'nix',
  ],
  [
    'Prüfung ohne Eigentümer',
    'Audit Without an Owner',
    'Oris’ Prüfzeichen steckt in einem Paar stabiler Stiefel. Die außen lesbare Grenze gilt auch für ihren Träger.',
    'Oris’s audit sign sits in a pair of sturdy boots. The externally readable limit applies to their bearer too.',
    'armor',
    'armor',
  ],
];

const scalar = (stat: string, floor: number): number => {
  if (stat === 'damage') return 8 + floor * 2.3;
  if (stat === 'armor') return 4 + Math.ceil(floor * 1.15);
  if (stat === 'maxHp') return 12 + floor * 4;
  if (stat === 'maxResource') return 8 + floor * 2;
  if (stat === 'regen') return 0.7 + floor * 0.15;
  if (stat === 'nix') return 0.12 + floor * 0.025;
  if (stat === 'crit' || stat === 'lifesteal') return 0.02 + floor * 0.006;
  return 0.06 + floor * 0.012;
};
const describe = (lore: Text, effect?: string): Text =>
  effect ? t(`${lore.de} ${effectText[effect].de}`, `${lore.en} ${effectText[effect].en}`) : lore;

const uniqueDefs: { id: string; seed: UniqueSeed; floor: number; source: string }[] = [
  ...bossUniques.map((seed, i) => ({
    id: `unique-boss-${String(i + 1).padStart(2, '0')}`,
    seed,
    floor: i + 1,
    source: 'boss',
  })),
  ...minibossUniques.map((seed, i) => ({
    id: `unique-${i % 2 === 0 ? 'guardian' : 'hunt'}-${String(Math.floor(i / 2) + 1).padStart(2, '0')}`,
    seed,
    floor: Math.floor(i / 2) + 1,
    source: 'mini',
  })),
  ...questUniques.map((seed, i) => ({
    id: `unique-quest-${String(i + 1).padStart(2, '0')}`,
    seed,
    floor: Math.floor(i / 2) + 1,
    source: 'quest',
  })),
  ...craftUniques.map((seed, i) => ({
    id: `unique-craft-${String(i + 1).padStart(2, '0')}`,
    seed,
    floor: i + 1,
    source: 'craft',
  })),
];
const uniqueSlots: GearSlot[] = [
  'weapon',
  'offhand',
  'head',
  'body',
  'hands',
  'feet',
  'amulet',
  'talisman',
  'weapon',
  'offhand',
  'head',
  'body',
  'hands',
  'offhand',
  'amulet',
  'body',
  'weapon',
  'talisman',
  'weapon',
  'amulet',
  'head',
  'hands',
  'body',
  'talisman',
  'offhand',
  'weapon',
  'feet',
  'amulet',
  'head',
  'offhand',
  'talisman',
  'offhand',
  'amulet',
  'talisman',
  'hands',
  'weapon',
  'amulet',
  'offhand',
  'head',
  'body',
  'weapon',
  'feet',
  'talisman',
  'talisman',
  'weapon',
  'offhand',
  'head',
  'body',
  'hands',
  'feet',
  'amulet',
  'talisman',
  'weapon',
  'offhand',
  'head',
  'body',
  'hands',
  'feet',
  'head',
  'talisman',
  'hands',
  'feet',
  'amulet',
  'amulet',
  'body',
  'feet',
  'head',
  'body',
  'hands',
  'feet',
  'hands',
  'feet',
];
const uniqueItems: ItemDef[] = uniqueDefs.map((u, i) => ({
  id: u.id,
  name: t(u.seed[0], u.seed[1]),
  description: describe(t(u.seed[2], u.seed[3]), u.seed[4]),
  kind: 'gear',
  slot: uniqueSlots[i],
  rarity: u.source === 'boss' ? 5 : 4,
  floor: u.floor,
  icon: i % 128,
  stat: u.seed[5],
  value: scalar(u.seed[5], u.floor) * 1.35,
  effect: u.seed[4],
  price: 300 + u.floor * 85,
}));

export const SETS: SetDef[] = [
  {
    id: 'set-shift',
    name: t('Letzte Wartungsschicht', 'Final Maintenance Shift'),
    two: t('2 Teile: +8 Rüstung.', '2 pieces: +8 armour.'),
    four: t(
      '4 Teile: Ausweichen erzeugt kurz Schutz. Wechsle Position statt nur stehen zu bleiben.',
      '4 pieces: dodging briefly creates protection. Reposition rather than only stand still.',
    ),
    stat: 'armor',
    value: 8,
    effect: 'dodge-shield',
  },
  {
    id: 'set-clinic',
    name: t('Klinik ohne Vertrag', 'Clinic Without a Contract'),
    two: t('2 Teile: +20 % Heilwirkung.', '2 pieces: +20% healing.'),
    four: t(
      '4 Teile: verstärkte Heilung. Du investierst vier Slots in Erholung statt maximale Angriffswerte.',
      '4 pieces: reinforced healing. Four slots invest in recovery rather than maximum attack stats.',
    ),
    stat: 'healing',
    value: 0.2,
    effect: 'healing',
  },
  {
    id: 'set-choir',
    name: t('Unverkaufter Chor', 'Unsold Choir'),
    two: t('2 Teile: +12 % Schaden.', '2 pieces: +12% damage.'),
    four: t(
      '4 Teile: Treffer können Taumeln auslösen. Die große Wirkung folgt einem tatsächlich getroffenen Ziel.',
      '4 pieces: hits can stagger enemies. The major effect follows an actually hit target.',
    ),
    stat: 'damage',
    value: 0.12,
    effect: 'stagger',
  },
  {
    id: 'set-root',
    name: t('Freier Wurzelkreis', 'Free Root Circuit'),
    two: t('2 Teile: +1,8 Ressource pro Sekunde.', '2 pieces: +1.8 resource per second.'),
    four: t(
      '4 Teile: Treffer können Frost auslösen. Flächenkontrolle ersetzt einen Teil deiner direkten Schlagkraft.',
      '4 pieces: hits can inflict frost. Area control replaces part of your direct striking power.',
    ),
    stat: 'regen',
    value: 1.8,
    effect: 'frost',
  },
  {
    id: 'set-foundry',
    name: t('Handgeformte Serie', 'Hand-Shaped Batch'),
    two: t('2 Teile: +18 % Elementarschaden.', '2 pieces: +18% elemental damage.'),
    four: t(
      '4 Teile: Treffer können Brennen auslösen. Der Folgeschaden benötigt Zeit, bevor das Ziel fällt.',
      '4 pieces: hits can ignite enemies. Follow-up damage needs time before the target falls.',
    ),
    stat: 'elemental',
    value: 0.18,
    effect: 'burn',
  },
  {
    id: 'set-unbranded',
    name: t('Ohne Marke', 'Unbranded'),
    two: t('2 Teile: +12 % Bewegungstempo.', '2 pieces: +12% movement speed.'),
    four: t(
      '4 Teile: verstärkter Positionswechsel. Nutze Bewegung, um Schutzfenster selbst herzustellen.',
      '4 pieces: reinforced repositioning. Use movement to create your own protection windows.',
    ),
    stat: 'speed',
    value: 0.12,
    effect: 'speed',
  },
  {
    id: 'set-source',
    name: t('Originalregister', 'Original Register'),
    two: t('2 Teile: +10 % kritische Trefferchance.', '2 pieces: +10% critical chance.'),
    four: t(
      '4 Teile: zusätzliche kritische Fenster. Präzision hängt weiter davon ab, dass dein Angriff trifft.',
      '4 pieces: additional critical windows. Precision still depends on your attack landing.',
    ),
    stat: 'crit',
    value: 0.1,
    effect: 'crit',
  },
  {
    id: 'set-minute',
    name: t('Eigene Minute', 'Your Own Minute'),
    two: t('2 Teile: 15 % kürzere Abklingzeiten.', '2 pieces: 15% shorter cooldowns.'),
    four: t(
      '4 Teile: Geräteunterstützung. Ein freier Aufstellplatz ist weiterhin wichtiger als blindes Nachbauen.',
      '4 pieces: device support. An open deployment position still matters more than blindly rebuilding.',
    ),
    stat: 'cooldown',
    value: 0.15,
    effect: 'turret',
  },
  {
    id: 'set-stage',
    name: t('Leere Bühne', 'Empty Stage'),
    two: t('2 Teile: +15 % Schaden.', '2 pieces: +15% damage.'),
    four: t(
      '4 Teile: verwundete Ziele sind anfälliger. Der Eröffnungsschlag braucht trotzdem seine eigene Lücke.',
      '4 pieces: wounded targets are more vulnerable. The opening strike still needs its own gap.',
    ),
    stat: 'damage',
    value: 0.15,
    effect: 'execute',
  },
  {
    id: 'set-backbone',
    name: t('Offenes Rückgrat', 'Open Backbone'),
    two: t('2 Teile: +35 maximales Leben.', '2 pieces: +35 maximum health.'),
    four: t(
      '4 Teile: Gegenschaden bei erlittenen Treffern. Die Gegenwirkung ist eine Reserve und kein Grund, Gefahren stehen zu lassen.',
      '4 pieces: retaliation on received hits. Retaliation is a reserve, not a reason to remain in danger.',
    ),
    stat: 'maxHp',
    value: 35,
    effect: 'thorns',
  },
  {
    id: 'set-echo',
    name: t('Freiwilliges Echo', 'Voluntary Echo'),
    two: t('2 Teile: +35 % NIX-Schaden.', '2 pieces: +35% NIX damage.'),
    four: t(
      '4 Teile: verstärkte Begleiterhilfe. NIX braucht weiterhin ein erreichbares Ziel statt einer verschlossenen Wand.',
      '4 pieces: reinforced companion support. NIX still needs a reachable target rather than a closed wall.',
    ),
    stat: 'nix',
    value: 0.35,
    effect: 'nix',
  },
  {
    id: 'set-audit',
    name: t('Lesbare Grenze', 'Readable Limit'),
    two: t('2 Teile: +20 % Schrottgewinn.', '2 pieces: +20% scrap income.'),
    four: t(
      '4 Teile: zusätzlicher verwertbarer Schrott. Das Set bietet Versorgung statt einer Pflichtlösung für jeden Boss.',
      '4 pieces: additional recoverable scrap. This set offers provision rather than a required answer to every boss.',
    ),
    stat: 'gold',
    value: 0.2,
    effect: 'gold',
  },
];

const setSlotGroups: GearSlot[][] = [
  ['weapon', 'offhand', 'head', 'body'],
  ['hands', 'feet', 'amulet', 'talisman'],
  ['weapon', 'hands', 'feet', 'amulet'],
  ['offhand', 'head', 'body', 'talisman'],
  ['weapon', 'offhand', 'body', 'talisman'],
  ['head', 'hands', 'feet', 'amulet'],
  ['head', 'body', 'feet', 'amulet'],
  ['weapon', 'offhand', 'hands', 'talisman'],
  ['weapon', 'head', 'hands', 'talisman'],
  ['offhand', 'body', 'feet', 'amulet'],
  ['weapon', 'body', 'hands', 'feet'],
  ['offhand', 'head', 'amulet', 'talisman'],
];
const setPieceNames: [string[], string[]][] = [
  [
    ['Schichthebel', 'Türplatte', 'Wartungsvisier', 'Arbeitsmantel'],
    ['Shift Lever', 'Door Panel', 'Maintenance Visor', 'Work Coat'],
  ],
  [
    ['Saubere Hände', 'Kliniksohlen', 'Versorgungszeichen', 'Offene Akte'],
    ['Clean Hands', 'Clinic Soles', 'Provision Sign', 'Open File'],
  ],
  [
    ['Chorhammer', 'Stimmgriff', 'Unverkaufte Sohlen', 'Namensmedaillon'],
    ['Choir Hammer', 'Voice Grip', 'Unsold Soles', 'Name Medallion'],
  ],
  [
    ['Rindenschild', 'Wurzelhaube', 'Lebender Mantel', 'Freie Knospe'],
    ['Bark Shield', 'Root Hood', 'Living Coat', 'Free Bud'],
  ],
  [
    ['Handgussklinge', 'Kühlplatte', 'Formjacke', 'Glutfreiheit'],
    ['Hand-Cast Blade', 'Cooling Plate', 'Mould Jacket', 'Ember Freedom'],
  ],
  [
    ['Neutrale Maske', 'Logoentferner', 'Ungestempelte Sohlen', 'Offener Anhänger'],
    ['Neutral Mask', 'Logo Remover', 'Unstamped Soles', 'Open Pendant'],
  ],
  [
    ['Quellenlinse', 'Registermantel', 'Echte Spur', 'Erstes Datum'],
    ['Source Lens', 'Register Coat', 'True Trace', 'First Date'],
  ],
  [
    ['Taktloser Stab', 'Freier Zeiger', 'Eigensinnige Finger', 'Ungeplante Minute'],
    ['Unclocked Staff', 'Free Hand', 'Independent Fingers', 'Unplanned Minute'],
  ],
  [
    ['Unbeobachtete Klinge', 'Leere Maske', 'Eigener Griff', 'Stiller Abspann'],
    ['Unobserved Blade', 'Empty Mask', 'Your Own Grip', 'Quiet Credits'],
  ],
  [
    ['Rippenstütze', 'Rücklaufmantel', 'Knotensohle', 'Pulsanhänger'],
    ['Rib Support', 'Return Coat', 'Node Sole', 'Pulse Pendant'],
  ],
  [
    ['Gemeinsame Fährte', 'Warmlichtfell', 'Zweiter Gedanke', 'Freiwilliger Schritt'],
    ['Shared Trail', 'Warm-Light Coat', 'Second Thought', 'Voluntary Step'],
  ],
  [
    ['Sichtbare Gegenklausel', 'Prüfvisier', 'Leserecht', 'Kündbares Siegel'],
    ['Visible Counter-Clause', 'Audit Visor', 'Reading Right', 'Terminable Seal'],
  ],
];
const setItems: ItemDef[] = SETS.flatMap((set, i) =>
  setSlotGroups[i].map((slot, j) => {
    const stat =
      slot === 'weapon'
        ? 'damage'
        : ['head', 'body', 'offhand'].includes(slot)
          ? 'armor'
          : slot === 'feet'
            ? 'speed'
            : slot === 'hands'
              ? 'crit'
              : set.stat;
    return {
      id: `${set.id}-${slot}`,
      name: t(setPieceNames[i][0][j], setPieceNames[i][1][j]),
      description: t(
        `${set.name.de}: ${set.two.de} ${set.four.de}`,
        `${set.name.en}: ${set.two.en} ${set.four.en}`,
      ),
      kind: 'gear' as const,
      slot,
      rarity: 3,
      floor: i + 1,
      icon: (72 + i * 4 + j) % 128,
      stat,
      value: scalar(stat, i + 1),
      set: set.id,
      price: 180 + (i + 1) * 55,
    };
  }),
);

const gearNames: Record<GearSlot, [string[], string[]]> = {
  weapon: [
    [
      'Wartungshebel',
      'Splitterdolch',
      'Bürstenhammer',
      'Kupferlanze',
      'Ventilbeil',
      'Rinnenbogen',
      'Spulensäbel',
      'Schrottschleuder',
      'Pressenkeule',
      'Tintenstab',
      'Wurzelmesser',
      'Papierklinge',
      'Gusshammer',
      'Kettenaxt',
      'Ofenspeer',
      'Stempelschwert',
      'Maskendegen',
      'Leuchtarmbrust',
      'Eisglasspeer',
      'Registerstab',
      'Frostmesser',
      'Messingsäbel',
      'Zeigerlanze',
      'Federwerfer',
      'Obsidianbeil',
      'Prismabogen',
      'Echomesser',
      'Rippenhammer',
      'Antennenstab',
      'Leitlinienklinge',
    ],
    [
      'Maintenance Lever',
      'Shard Dagger',
      'Brush Hammer',
      'Copper Lance',
      'Valve Axe',
      'Gutter Bow',
      'Coil Sabre',
      'Scrap Slinger',
      'Press Club',
      'Ink Staff',
      'Root Knife',
      'Paper Blade',
      'Cast Hammer',
      'Chain Axe',
      'Furnace Spear',
      'Stamp Sword',
      'Mask Rapier',
      'Light Crossbow',
      'Ice-Glass Spear',
      'Register Staff',
      'Frost Knife',
      'Brass Sabre',
      'Clock-Hand Lance',
      'Spring Thrower',
      'Obsidian Axe',
      'Prism Bow',
      'Echo Knife',
      'Rib Hammer',
      'Antenna Staff',
      'Guide-Line Blade',
    ],
  ],
  offhand: [
    [
      'Türblech',
      'Kabelrolle',
      'Stempelplatte',
      'Kupferschild',
      'Filterkorb',
      'Ventilschutz',
      'Magnetdeckel',
      'Altarscheibe',
      'Pfandplatte',
      'Rindendeckel',
      'Tintenbuch',
      'Sporenschale',
      'Kühlblech',
      'Gussschild',
      'Kettenrolle',
      'Werbetafel',
      'Siegelbuch',
      'Goldrahmen',
      'Archivdeckel',
      'Eisplatte',
      'Indexscheibe',
      'Zahnradschutz',
      'Pendelteller',
      'Wohnschirm',
      'Spiegelplatte',
      'Linsenscheibe',
      'Kulissentuch',
      'Rippenrahmen',
      'Signalblende',
      'Offene Schutzzeile',
    ],
    [
      'Door Sheet',
      'Cable Reel',
      'Stamp Plate',
      'Copper Shield',
      'Filter Basket',
      'Valve Guard',
      'Magnet Lid',
      'Altar Disc',
      'Pawn Plate',
      'Bark Lid',
      'Ink Book',
      'Spore Bowl',
      'Cooling Sheet',
      'Cast Shield',
      'Chain Reel',
      'Billboard',
      'Seal Book',
      'Golden Frame',
      'Archive Lid',
      'Ice Plate',
      'Index Disc',
      'Gear Guard',
      'Pendulum Dish',
      'Home Screen',
      'Mirror Plate',
      'Lens Disc',
      'Backdrop Cloth',
      'Rib Frame',
      'Signal Shade',
      'Open Guard Line',
    ],
  ],
  head: [
    [
      'Schichtkappe',
      'Lesebrille',
      'Bürstenhelm',
      'Rohrhaube',
      'Filtermaske',
      'Kupfervisier',
      'Rostkrone',
      'Spulenband',
      'Stahlkapuze',
      'Pilzhaube',
      'Satzschutz',
      'Tintenvisier',
      'Gusshelm',
      'Kühlmaske',
      'Aschehaube',
      'Siegerdiadem',
      'Reklameblende',
      'Vertragsbrille',
      'Eiskapuze',
      'Registerlinse',
      'Frostvisier',
      'Messingkappe',
      'Uhrwerksbrille',
      'Federhaube',
      'Spiegelmaske',
      'Prismavisier',
      'Kulissenkrone',
      'Nervenkappe',
      'Antennenhaube',
      'Regievisier',
    ],
    [
      'Shift Cap',
      'Reading Glasses',
      'Brush Helmet',
      'Pipe Hood',
      'Filter Mask',
      'Copper Visor',
      'Rust Crown',
      'Coil Band',
      'Steel Hood',
      'Mushroom Hood',
      'Type Guard',
      'Ink Visor',
      'Cast Helmet',
      'Cooling Mask',
      'Ash Hood',
      'Champion Diadem',
      'Advertising Shade',
      'Contract Glasses',
      'Ice Hood',
      'Register Lens',
      'Frost Visor',
      'Brass Cap',
      'Clockwork Glasses',
      'Spring Hood',
      'Mirror Mask',
      'Prism Visor',
      'Backdrop Crown',
      'Nerve Cap',
      'Antenna Hood',
      'Production Visor',
    ],
  ],
  body: [
    [
      'Wartungsweste',
      'Aufnahmejacke',
      'Sicherheitsmantel',
      'Rohrkittel',
      'Filterweste',
      'Kupferhemd',
      'Rostrobe',
      'Stapelpanzer',
      'Spulenmantel',
      'Rindenjacke',
      'Redaktionsschürze',
      'Tintenumhang',
      'Basaltweste',
      'Gussmantel',
      'Kühlhemd',
      'Siegerjacke',
      'Maskenrobe',
      'Vertragsmantel',
      'Archivkittel',
      'Eisglasweste',
      'Frostumhang',
      'Messingjacke',
      'Wohnmantel',
      'Uhrwerksweste',
      'Bühnenrobe',
      'Prismahemd',
      'Spiegelmantel',
      'Rippenweste',
      'Signaljacke',
      'Offene Regierobe',
    ],
    [
      'Maintenance Vest',
      'Intake Jacket',
      'Security Coat',
      'Pipe Gown',
      'Filter Vest',
      'Copper Shirt',
      'Rust Robe',
      'Stack Armour',
      'Coil Coat',
      'Bark Jacket',
      'Newsroom Apron',
      'Ink Cloak',
      'Basalt Vest',
      'Cast Coat',
      'Cooling Shirt',
      'Champion Jacket',
      'Mask Robe',
      'Contract Coat',
      'Archive Gown',
      'Ice-Glass Vest',
      'Frost Cloak',
      'Brass Jacket',
      'Home Coat',
      'Clockwork Vest',
      'Stage Robe',
      'Prism Shirt',
      'Mirror Coat',
      'Rib Vest',
      'Signal Jacket',
      'Open Production Robe',
    ],
  ],
  hands: [
    [
      'Arbeitsgriff',
      'Kabelhandschuhe',
      'Stempelfinger',
      'Rohrhandschuhe',
      'Filterfäustlinge',
      'Ventilgriff',
      'Spulenfinger',
      'Schrottgriff',
      'Stahlfäustlinge',
      'Tintenfinger',
      'Rindenhandschuhe',
      'Falzgriff',
      'Gusshandschuhe',
      'Kühlgriff',
      'Aschefinger',
      'Siegelhandschuhe',
      'Maskengriff',
      'Goldfinger',
      'Lesefäustlinge',
      'Indexgriff',
      'Frostfinger',
      'Federgriff',
      'Messinghandschuhe',
      'Zeigerfinger',
      'Glasgriff',
      'Prismahandschuhe',
      'Kulissenfinger',
      'Pulsgriff',
      'Signalhandschuhe',
      'Freigabefinger',
    ],
    [
      'Work Grip',
      'Cable Gloves',
      'Stamp Fingers',
      'Pipe Gloves',
      'Filter Mittens',
      'Valve Grip',
      'Coil Fingers',
      'Scrap Grip',
      'Steel Mittens',
      'Ink Fingers',
      'Bark Gloves',
      'Folding Grip',
      'Cast Gloves',
      'Cooling Grip',
      'Ash Fingers',
      'Seal Gloves',
      'Mask Grip',
      'Golden Fingers',
      'Reading Mittens',
      'Index Grip',
      'Frost Fingers',
      'Spring Grip',
      'Brass Gloves',
      'Clock-Hand Fingers',
      'Glass Grip',
      'Prism Gloves',
      'Backdrop Fingers',
      'Pulse Grip',
      'Signal Gloves',
      'Approval Fingers',
    ],
  ],
  feet: [
    [
      'Schichtstiefel',
      'Bürstensohlen',
      'Förderschuhe',
      'Rohrstiefel',
      'Trockenfüße',
      'Ventilsohlen',
      'Magnetstiefel',
      'Schrottschuhe',
      'Kettenabsatz',
      'Wurzelschritt',
      'Papierfüße',
      'Tintenstiefel',
      'Basaltsohlen',
      'Gussschuhe',
      'Kühlstiefel',
      'Siegerschritt',
      'Maskenschuhe',
      'Goldsohlen',
      'Eisglasstiefel',
      'Registerschritt',
      'Frostschuhe',
      'Gleissohlen',
      'Messingstiefel',
      'Federfüße',
      'Bühnenschritt',
      'Prismaschuhe',
      'Spiegelfüße',
      'Rücklaufstiefel',
      'Signalschritt',
      'Offene Route',
    ],
    [
      'Shift Boots',
      'Brush Soles',
      'Conveyor Shoes',
      'Pipe Boots',
      'Dry Feet',
      'Valve Soles',
      'Magnet Boots',
      'Scrap Shoes',
      'Chain Heel',
      'Root Step',
      'Paper Feet',
      'Ink Boots',
      'Basalt Soles',
      'Cast Shoes',
      'Cooling Boots',
      'Champion Step',
      'Mask Shoes',
      'Golden Soles',
      'Ice-Glass Boots',
      'Register Step',
      'Frost Shoes',
      'Rail Soles',
      'Brass Boots',
      'Spring Feet',
      'Stage Step',
      'Prism Shoes',
      'Mirror Feet',
      'Return Boots',
      'Signal Step',
      'Open Route',
    ],
  ],
  amulet: [
    [
      'Wartungsmarke',
      'Aufnahmering',
      'Kabelanhänger',
      'Kupferknoten',
      'Filteramulett',
      'Ventilmedaillon',
      'Spulenherz',
      'Pfandzeichen',
      'Stahlanhänger',
      'Sporenamulett',
      'Rindenknoten',
      'Tintenmedaillon',
      'Basaltherz',
      'Kühlanhänger',
      'Gusszeichen',
      'Siegeramulett',
      'Siegelknoten',
      'Maskenanhänger',
      'Originalzeichen',
      'Eisglasherz',
      'Registermedaillon',
      'Taktamulett',
      'Messingknoten',
      'Federanhänger',
      'Echoherz',
      'Prismamarke',
      'Spiegelzeichen',
      'Pulsmedaillon',
      'Frequenzknoten',
      'Morgenamulett',
    ],
    [
      'Maintenance Badge',
      'Intake Ring',
      'Cable Pendant',
      'Copper Knot',
      'Filter Amulet',
      'Valve Medallion',
      'Coil Heart',
      'Pawn Sign',
      'Steel Pendant',
      'Spore Amulet',
      'Bark Knot',
      'Ink Medallion',
      'Basalt Heart',
      'Cooling Pendant',
      'Cast Sign',
      'Champion Amulet',
      'Seal Knot',
      'Mask Pendant',
      'Original Sign',
      'Ice-Glass Heart',
      'Register Medallion',
      'Beat Amulet',
      'Brass Knot',
      'Spring Pendant',
      'Echo Heart',
      'Prism Badge',
      'Mirror Sign',
      'Pulse Medallion',
      'Frequency Knot',
      'Morning Amulet',
    ],
  ],
  talisman: [
    [
      'Reststromchip',
      'Schichtbeleg',
      'Einlassfaden',
      'Wasserzeichen',
      'Rohrpostband',
      'Sauberer Filter',
      'Magnetbeleg',
      'Chorfragment',
      'Unverkaufte Zeile',
      'Sporensiegel',
      'Vierte Seite',
      'Freie Knospe',
      'Formfragment',
      'Wärmezeichen',
      'Offener Kühlkreis',
      'Leere Werbung',
      'Siegerklausel',
      'Ungestempelte Quittung',
      'Originalsplitter',
      'Letzte Briefzeile',
      'Private Nummer',
      'Freie Feder',
      'Eigener Takt',
      'Ungeplanter Fahrplan',
      'Ungesendetes Echo',
      'Echter Spiegel',
      'Leere Applauszeile',
      'Lebender Rücklauf',
      'Stiller Ruf',
      'Kündbares Versprechen',
    ],
    [
      'Residual-Power Chip',
      'Shift Receipt',
      'Admission Thread',
      'Watermark',
      'Pneumatic-Post Band',
      'Clean Filter',
      'Magnet Receipt',
      'Choir Fragment',
      'Unsold Line',
      'Spore Seal',
      'Fourth Page',
      'Free Bud',
      'Mould Fragment',
      'Heat Sign',
      'Open Coolant Circuit',
      'Empty Advertisement',
      'Winner Clause',
      'Unstamped Receipt',
      'Original Shard',
      'Last Letter Line',
      'Private Number',
      'Free Spring',
      'Your Own Beat',
      'Unplanned Timetable',
      'Unbroadcast Echo',
      'True Mirror',
      'Empty Applause Line',
      'Living Return',
      'Quiet Call',
      'Terminable Promise',
    ],
  ],
};

const provenance: Text[] = [
  t(
    'Aus der Wartung der Aufnahmehalle geborgen. Keine Zulassung nötig, um es selbst zu benutzen.',
    'Recovered from Intake Hall maintenance. No admission is required to use it yourself.',
  ),
  t(
    'Für die Rostkanäle gebaut: ein brauchbares Werkzeug zwischen Wasser und enger Deckung.',
    'Built for the Rust Channels: a useful tool between water and tight cover.',
  ),
  t(
    'Aus Schrottaltären gelöst. Der frühere Pfandvermerk wurde sauber entfernt.',
    'Freed from scrap altars. Its old pledge marking has been cleanly removed.',
  ),
  t(
    'Lebendes Material aus der Redaktion, bewusst vom Schreibnetz getrennt.',
    'Living material from the newsroom, deliberately separated from the writing network.',
  ),
  t(
    'Handgeprüftes Teil aus der Gießerei. Seine Seriennummer bestimmt nicht seinen nächsten Einsatz.',
    'A hand-checked foundry part. Its serial number does not determine its next use.',
  ),
  t(
    'Ein Galerieteil ohne verpflichtende Sponsormarke. Seine Kosten enden beim Kauf.',
    'A gallery component without a required sponsor brand. Its costs end at purchase.',
  ),
  t(
    'Im Eisarchiv konserviert und vorsichtig geöffnet. Die Herkunftszeile bleibt lesbar.',
    'Preserved in the Frozen Archive and carefully opened. Its origin line remains readable.',
  ),
  t(
    'Aus einer unabhängigen Uhrwerkschicht. Das Gerät folgt jetzt deinem eigenen Takt.',
    'From an independent clockwork shift. This device now follows your own beat.',
  ),
  t(
    'Ein echtes Werkzeug von einer falschen Bühne. Es behält seinen Wert ohne Kamera.',
    'A genuine tool from a false stage. It keeps its worth without a camera.',
  ),
  t(
    'Trägt einen kleinen offenen Netzanschluss. Die Leitung führt zurück zu dir.',
    'Carries a small open network connector. Its conduit returns to you.',
  ),
  t(
    'In einer dunklen Signalinsel gesichert. Jede aktive Fläche ist weiterhin sichtbar.',
    'Secured on a dark signal island. Every active surface remains visible.',
  ),
  t(
    'Ein letztes Regieteil mit außen lesbarer Kontrolle. Der morgige Einsatz bleibt deine Wahl.',
    'A final production component with externally readable controls. Tomorrow’s use remains your choice.',
  ),
];
const regularItems: ItemDef[] = slots.flatMap((slot, s) =>
  gearNames[slot][0].map((name, i) => {
    const floor = Math.min(12, Math.floor(i / 2.5) + 1);
    const stat =
      slot === 'weapon'
        ? 'damage'
        : slot === 'offhand'
          ? i % 3 === 1
            ? 'maxResource'
            : 'armor'
          : slot === 'head'
            ? i % 3 === 1
              ? 'maxResource'
              : 'armor'
            : slot === 'body'
              ? i % 3 === 2
                ? 'armor'
                : 'maxHp'
              : slot === 'hands'
                ? i % 3 === 0
                  ? 'damage'
                  : 'crit'
                : slot === 'feet'
                  ? i % 3 === 2
                    ? 'dodge'
                    : 'speed'
                  : slot === 'amulet'
                    ? ['maxHp', 'healing', 'nix'][i % 3]
                    : ['regen', 'elemental', 'cooldown'][i % 3];
    const effects = [
      'stagger',
      'crit',
      'burn',
      'frost',
      'chain',
      'armor',
      'nix',
      'healing',
      'speed',
      'lifesteal',
    ];
    const effect = i % 5 === 4 ? effects[(i + s) % effects.length] : undefined;
    const note = t(
      `${provenance[floor - 1].de} ${slotNames[slot].de} für ${stat === 'damage' ? 'direkten Druck' : stat === 'armor' ? 'beständigen Schutz' : stat === 'maxHp' ? 'eine größere Lebensreserve' : stat === 'maxResource' ? 'eine zusätzliche Ressourcenreserve' : stat === 'speed' || stat === 'dodge' ? 'sichere Positionswechsel' : stat === 'crit' ? 'präzise Treffer' : stat === 'nix' ? 'die gemeinsame Jagd' : stat === 'healing' ? 'verlässliche Erholung' : stat === 'elemental' ? 'Elementkombinationen' : 'einen stetigen Fähigkeitsrhythmus'}.`,
      `${provenance[floor - 1].en} ${slotNames[slot].en} for ${stat === 'damage' ? 'direct pressure' : stat === 'armor' ? 'steady protection' : stat === 'maxHp' ? 'a larger health reserve' : stat === 'maxResource' ? 'an extra resource reserve' : stat === 'speed' || stat === 'dodge' ? 'safe repositioning' : stat === 'crit' ? 'precise hits' : stat === 'nix' ? 'a shared hunt' : stat === 'healing' ? 'reliable recovery' : stat === 'elemental' ? 'element combinations' : 'a steady ability rhythm'}.`,
    );
    return {
      id: `gear-${slot}-${String(i + 1).padStart(2, '0')}`,
      name: t(name, gearNames[slot][1][i]),
      description: describe(note, effect),
      kind: 'gear' as const,
      slot,
      rarity: i % 5 === 4 ? 3 : i % 3,
      floor,
      icon: (s * 16 + i) % 128,
      stat,
      value: scalar(stat, floor) * (i % 5 === 4 ? 1.1 : 1),
      effect,
      price: 30 + floor * 25 + (i % 3) * 15,
    };
  }),
);

const relicNames: [string[], string[]][] = [
  [
    [
      'Taschengewitter',
      'Frost im Glas',
      'Glut ohne Ofen',
      'Kalter Funke',
      'Leitender Kiesel',
      'Verkohlte Fußnote',
      'Winterspule',
      'Warmer Nullpunkt',
      'Dritte Sicherung',
      'Rote Rückleitung',
      'Blaue Restladung',
      'Sturm im Gehäuse',
      'Asche im Index',
      'Schmelzfreie Kante',
      'Unruhiger Draht',
      'Schockprotokoll',
      'Gefaltete Kälte',
      'Sporenglut',
      'Kupferregen',
      'Element ohne Eigentümer',
    ],
    [
      'Pocket Thunderstorm',
      'Frost in a Jar',
      'Ember Without a Furnace',
      'Cold Spark',
      'Conductive Pebble',
      'Charred Footnote',
      'Winter Coil',
      'Warm Zero Point',
      'Third Fuse',
      'Red Return Lead',
      'Blue Residual Charge',
      'Storm in a Casing',
      'Ash in the Index',
      'Melt-Free Edge',
      'Restless Wire',
      'Shock Protocol',
      'Folded Cold',
      'Spore Ember',
      'Copper Rain',
      'Element Without an Owner',
    ],
  ],
  [
    [
      'Eigensinnige Schraube',
      'Turm in der Tasche',
      'Minenetikett',
      'Zweiter Auslöser',
      'Unbenutzte Feder',
      'Wartungskaffee',
      'Drahtknäuel',
      'Ersatz für den Ersatz',
      'Spätes Werkzeug',
      'Knappe Aufbauzeit',
      'Schraube mit Meinung',
      'Sicherer Prototyp',
      'Bauteil ohne Auftrag',
      'Batterie der Pause',
      'Letzter Lötpunkt',
      'Mutter ohne Bolzen',
      'Der kleine Plan B',
      'Gerät mit Abschalter',
      'Kühlung für Anfänger',
      'Freiwillige Mechanik',
    ],
    [
      'Opinionated Screw',
      'Tower in Your Pocket',
      'Mine Label',
      'Second Trigger',
      'Unused Spring',
      'Maintenance Coffee',
      'Wire Tangle',
      'Spare for the Spare',
      'Late Tool',
      'Brief Assembly Time',
      'Screw with an Opinion',
      'Safe Prototype',
      'Uncommissioned Component',
      'Battery of the Pause',
      'Last Solder Point',
      'Nut Without a Bolt',
      'Little Plan B',
      'Device with an Off Switch',
      'Beginner’s Cooling',
      'Voluntary Mechanics',
    ],
  ],
  [
    [
      'Applaus im Umschlag',
      'Neutraler Markenfleck',
      'Prämie ohne Bühne',
      'Scheinwerferpause',
      'Rabatt mit Quittung',
      'Glanz auf Probe',
      'Zielgruppenverlust',
      'Ungefilmter Sieg',
      'Letzter Werbeblock',
      'Sponsorfreier Atem',
      'Treuer Kleindruck',
      'Nicht gesponserter Stein',
      'Kostenlose Vorführung',
      'Goldener Leerraum',
      'Preis ohne Pfand',
      'Publikumsfreier Blick',
      'Echte Zufriedenheit',
      'Wette mit Ende',
      'Reklamefeierabend',
      'Unverkäuflicher Rest',
    ],
    [
      'Applause in an Envelope',
      'Neutral Brand Stain',
      'Prize Without a Stage',
      'Spotlight Pause',
      'Discount with a Receipt',
      'Trial Shine',
      'Audience Loss',
      'Unfilmed Victory',
      'Last Ad Break',
      'Sponsor-Free Breath',
      'Faithful Small Print',
      'Unsponsored Stone',
      'Free Demonstration',
      'Golden Empty Space',
      'Price Without a Pledge',
      'Audience-Free Look',
      'Genuine Satisfaction',
      'Bet with an End',
      'Advertising Break',
      'Unsellable Remainder',
    ],
  ],
  [
    [
      'Kündbarer Fluch',
      'Schonfristkiesel',
      'Lebenszeile',
      'Ehrliche Gegenleistung',
      'Offener Widerspruch',
      'Sicherheitsabsatz',
      'Nicht bindende Klausel',
      'Verzögerte Forderung',
      'Restschuld ohne Stimme',
      'Faires Bannzeichen',
      'Gegenseitiger Schutz',
      'Unverpfändeter Puls',
      'Formular mit Ende',
      'Prüfbare Zustimmung',
      'Aufgehobene Strafe',
      'Saubere Unterschrift',
      'Grenze im Licht',
      'Vertrag ohne Fanghaken',
      'Preis der eigenen Hand',
      'Lesbarer Rückweg',
    ],
    [
      'Terminable Curse',
      'Grace-Period Pebble',
      'Life Line',
      'Honest Consideration',
      'Open Objection',
      'Safety Paragraph',
      'Non-Binding Clause',
      'Deferred Claim',
      'Residual Debt Without a Voice',
      'Fair Binding Sign',
      'Mutual Protection',
      'Unpledged Pulse',
      'Form with an End',
      'Verifiable Consent',
      'Repealed Penalty',
      'Clean Signature',
      'Limit in the Light',
      'Contract Without a Hook',
      'Price of Your Own Hand',
      'Readable Return Route',
    ],
  ],
  [
    [
      'Zusätzliche Schakalpfote',
      'Archivlicht für NIX',
      'Zahn ohne Nummer',
      'Ohren der nächsten Schicht',
      'Gemeinsamer Geruch',
      'Kleiner Jagdplan',
      'Freiwillige Leine',
      'Schakal ohne Werkseinstellung',
      'Geteilte Fährte',
      'Metallener Trost',
      'Warme Antennenspitze',
      'Schwanzsignal',
      'Unvollständiger Freund',
      'Zwei gute Ohren',
      'Zusammengefundener Weg',
      'Gedächtnis ohne Befehl',
      'NIX’ halber Witz',
      'Bereitwilliger Biss',
      'Nach Hause führende Marke',
      'Ein eigener Schakalname',
    ],
    [
      'Extra Jackal Paw',
      'Archive Light for NIX',
      'Tooth Without a Number',
      'Ears of the Next Shift',
      'Shared Scent',
      'Small Hunting Plan',
      'Voluntary Lead',
      'Jackal Without Factory Settings',
      'Shared Trail',
      'Metal Comfort',
      'Warm Antenna Tip',
      'Tail Signal',
      'Incomplete Friend',
      'Two Good Ears',
      'Route Found Together',
      'Memory Without an Order',
      'NIX’s Half Joke',
      'Willing Bite',
      'Homeward Badge',
      'A Jackal Name of One’s Own',
    ],
  ],
  [
    [
      'Fluchtweg im Knopfloch',
      'Leichte letzte Last',
      'Ausweichbeleg',
      'Rolle statt Regel',
      'Offene Flanke',
      'Pause unter den Sohlen',
      'Weg ohne Marke',
      'Schneller Widerspruch',
      'Sicherer Umweg',
      'Kleiner Freiraum',
      'Kamerafreier Schritt',
      'Zweiter Rückweg',
      'Gleis ohne Fahrplan',
      'Ungeplante Kurve',
      'Tritt ins Morgen',
      'Standort mit Wahl',
      'Freier Federweg',
      'Stufe ohne Eigentümer',
      'Abstand als Antwort',
      'Noch ein Schritt',
    ],
    [
      'Escape Route in a Buttonhole',
      'Light Final Load',
      'Dodge Receipt',
      'Wheel Instead of Rule',
      'Open Flank',
      'Pause Beneath the Soles',
      'Unbranded Route',
      'Quick Objection',
      'Safe Detour',
      'Small Free Space',
      'Camera-Free Step',
      'Second Return Route',
      'Rail Without a Timetable',
      'Unplanned Curve',
      'Step into Tomorrow',
      'Position with a Choice',
      'Free Spring Travel',
      'Ownerless Step',
      'Distance as an Answer',
      'One More Step',
    ],
  ],
];
const relicEffects = [
  ['chain', 'frost', 'burn', 'frost', 'chain'],
  ['turret', 'stagger', 'burn', 'turret', 'armor'],
  ['gold', 'crit', 'healing', 'execute', 'gold'],
  ['lifesteal', 'armor', 'thorns', 'healing', 'execute'],
  ['nix', 'nix', 'crit', 'healing', 'nix'],
  ['speed', 'dodge-shield', 'frost', 'speed', 'armor'],
];
const relicStats = [
  ['elemental', 'cooldown', 'elemental', 'regen', 'crit'],
  ['cooldown', 'damage', 'elemental', 'maxResource', 'armor'],
  ['gold', 'crit', 'healing', 'damage', 'gold'],
  ['lifesteal', 'armor', 'maxHp', 'healing', 'damage'],
  ['nix', 'nix', 'crit', 'healing', 'nix'],
  ['speed', 'dodge', 'cooldown', 'speed', 'armor'],
];
const relicLore = [
  t(
    'Ein unabhängiger Rest der Elementleitungen. Führe die Energie in ein getroffenes Ziel, statt dich nur auf den Namen zu verlassen.',
    'An independent remnant of elemental conduits. Guide its energy into a struck target rather than relying on its name alone.',
  ),
  t(
    'Ein Gerät aus Tams offener Werkstatt. Seine Aufgabe endet dort, wo du den letzten Schalter loslässt.',
    'A device from Tam’s open workshop. Its assignment ends where you release the final switch.',
  ),
  t(
    'Ein Sponsorstück mit entfernten Eigentumszeilen. Der brauchbare Rest darf seinen Zweck wechseln.',
    'A sponsor component with its ownership clauses removed. Its useful remainder may change purpose.',
  ),
  t(
    'Oris hat die Bindung lesbar gemacht. Dieser kleine Vertrag nennt seine Wirkung auf der Außenseite.',
    'Oris made the binding readable. This small contract names its effect on the outside.',
  ),
  t(
    'Von NIX geprüfte Begleitertechnik. Die Unterstützung folgt einem gemeinsamen Kampf, nicht einer neuen Werkseinstellung.',
    'Companion technology checked by NIX. Its support follows a shared fight, not a new factory setting.',
  ),
  t(
    'Ein Teil einer selbst gewählten Route. Der nächste sichere Schritt gehört weiterhin deiner Entscheidung.',
    'Part of a freely chosen route. The next safe step still belongs to your decision.',
  ),
];
const relicItems: ItemDef[] = relicNames.flatMap((pair, family) =>
  pair[0].map((name, i) => {
    const floor = Math.min(12, 1 + Math.floor(i * 0.6)),
      effect = relicEffects[family][i % 5],
      stat = relicStats[family][i % 5];
    return {
      id: `relic-${['element', 'device', 'sponsor', 'pact', 'nix', 'mobility'][family]}-${String(i + 1).padStart(2, '0')}`,
      name: t(name, pair[1][i]),
      description: describe(relicLore[family], effect),
      kind: 'relic' as const,
      rarity: 2 + (i % 3),
      floor,
      icon: (24 + family * 17 + i) % 128,
      stat,
      value: scalar(stat, floor) * (1 + (i % 4) * 0.1),
      effect,
      price: 120 + floor * 45,
    };
  }),
);

const tacticalNames: [string[], string[]] = [
  [
    'Funkenflasche',
    'Kälteampulle',
    'Glutkapsel',
    'Taumelpaket',
    'Leitender Tropfen',
    'Eisstaub',
    'Brennender Falz',
    'Schlagfeder',
    'Gewitterglas',
    'Froststempel',
    'Aschebeutel',
    'Druckdose',
    'Stromschraube',
    'Kühlrolle',
    'Tintenbrand',
    'Magnetwurf',
    'Pulsflasche',
    'Kältesiegel',
    'Heißer Beleg',
    'Splitterdruck',
    'Letzter Funke',
    'Winter im Umschlag',
    'Freie Glut',
    'Offener Einschlag',
  ],
  [
    'Spark Bottle',
    'Cold Ampoule',
    'Ember Capsule',
    'Stagger Package',
    'Conductive Drop',
    'Ice Dust',
    'Burning Fold',
    'Impact Spring',
    'Storm Jar',
    'Frost Stamp',
    'Ash Pouch',
    'Pressure Tin',
    'Current Screw',
    'Cooling Roll',
    'Ink Fire',
    'Magnetic Throw',
    'Pulse Bottle',
    'Cold Seal',
    'Hot Receipt',
    'Shard Pressure',
    'Last Spark',
    'Winter in an Envelope',
    'Free Ember',
    'Open Impact',
  ],
];
const recoveryNames: [string[], string[]] = [
  [
    'Klinikpflaster',
    'Filterwasser',
    'Warme Ration',
    'Sauberer Verband',
    'Gildenbrühe',
    'Kühlgel',
    'Rekonstruktionssalbe',
    'Gedächtnistee',
    'Werkstattmahlzeit',
    'Pulsruhe',
    'Notfallreserve',
    'Erster Morgen',
  ],
  [
    'Clinic Dressing',
    'Filtered Water',
    'Warm Ration',
    'Clean Bandage',
    'Guild Broth',
    'Cooling Gel',
    'Reconstruction Salve',
    'Memory Tea',
    'Workshop Meal',
    'Pulse Rest',
    'Emergency Reserve',
    'First Morning',
  ],
];
const toolNames: [string[], string[]] = [
  [
    'Isolierband',
    'Ventilöl',
    'Magnetreiniger',
    'Wurzelbinder',
    'Kühlpaste',
    'Siegelkreide',
    'Linsentuch',
    'Federfett',
    'Spiegelsand',
    'Knotenklammer',
    'Antennenwachs',
    'Regieklebeband',
  ],
  [
    'Insulating Tape',
    'Valve Oil',
    'Magnet Cleaner',
    'Root Binder',
    'Coolant Paste',
    'Seal Chalk',
    'Lens Cloth',
    'Spring Grease',
    'Mirror Sand',
    'Node Clamp',
    'Antenna Wax',
    'Production Tape',
  ],
];
const boostNames: [string[], string[]] = [
  [
    'Reststromkaffee',
    'Druckration',
    'Rostmut',
    'Sporenfokus',
    'Glutpuls',
    'Ungesponserter Schluck',
    'Kalte Konzentration',
    'Freier Takttrunk',
    'Stiller Bühnenmut',
    'Netzreserve',
    'Licht im Becher',
    'Eigene Entscheidung',
  ],
  [
    'Residual-Power Coffee',
    'Pressure Ration',
    'Rust Courage',
    'Spore Focus',
    'Ember Pulse',
    'Unsponsored Sip',
    'Cold Concentration',
    'Free Beat Drink',
    'Quiet Stage Courage',
    'Network Reserve',
    'Light in a Cup',
    'Your Own Decision',
  ],
];
const explorationNames: [string[], string[]] = [
  [
    'Wartungsration',
    'Trockenweg-Proviant',
    'Chorruhe',
    'Gärtnerpause',
    'Kühlproviant',
    'Galeriefeierabend',
    'Archivsnack',
    'Wohnmodulration',
    'Bühnenpause',
    'Rücklaufproviant',
    'Signalinsel-Ration',
    'Abspannmahlzeit',
  ],
  [
    'Maintenance Ration',
    'Dry-Route Provisions',
    'Choir Rest',
    'Gardener’s Break',
    'Coolant Provisions',
    'Gallery Break',
    'Archive Snack',
    'Home-Module Ration',
    'Stage Break',
    'Return Provisions',
    'Signal-Island Ration',
    'Credits Meal',
  ],
];
const tacticalItems: ItemDef[] = tacticalNames[0].map((name, i) => {
  const effect = ['chain', 'frost', 'burn', 'stagger'][i % 4],
    floor: number = Math.floor(i / 2) + 1;
  return {
    id: `consumable-tactical-${String(i + 1).padStart(2, '0')}`,
    name: t(name, tacticalNames[1][i]),
    description: t(
      `Benutzen verstärkt 45 Sekunden lang deine Treffer und deinen Elementarschaden. Verbraucht keine Fähigkeitsressource. Während der Wirkung: ${effectText[effect].de}`,
      `Use enhances your hits and elemental damage for 45 seconds. Costs no ability resource. While active: ${effectText[effect].en}`,
    ),
    kind: 'consumable',
    rarity: 1 + (i % 3),
    floor,
    icon: (70 + i) % 128,
    stat: 'elemental',
    value: 0.12 + floor * 0.01,
    effect,
    price: 35 + floor * 10,
  };
});
const supplyItems: ItemDef[] = [recoveryNames, toolNames, boostNames, explorationNames].flatMap(
  (pair, family) =>
    pair[0].map((name, i) => {
      const effect = family === 1 ? 'armor' : family === 2 ? 'healing' : 'healing';
      const lore =
        family === 1
          ? t(
              'Eine Feldhilfe für die nächste Erholung. Sie wird beim Gebrauch verbraucht und ersetzt keinen notwendigen Storyschlüssel.',
              'A field aid for the next recovery. It is consumed on use and replaces no required story key.',
            )
          : family === 2
            ? t(
                'Eine konzentrierte Reserve aus der Werkstatt. Spare sie für den Moment, in dem deine gewöhnliche Heilung nicht reicht.',
                'A concentrated reserve from the workshop. Keep it for the moment when your ordinary healing is insufficient.',
              )
            : family === 3
              ? t(
                  'Eine Reisehilfe für lange Routen. Ihre verlässliche Reserve ist wichtiger als jede versprochene Wunderwirkung.',
                  'A travel aid for long routes. Its reliable reserve matters more than any promised miracle.',
                )
              : t(
                  'Ein sauberer Versorgungssatz aus Miras Klinik. Benutzen stellt Leben wieder her.',
                  'A clean supply kit from Mira’s clinic. Use restores health.',
                );
      return {
        id: `consumable-${['recovery', 'tool', 'boost', 'exploration'][family]}-${String(i + 1).padStart(2, '0')}`,
        name: t(name, pair[1][i]),
        description: lore,
        kind: 'consumable' as const,
        rarity: Math.min(3, 1 + Math.floor(i / 4)),
        floor: i + 1,
        icon: (94 + family * 9 + i) % 128,
        stat: 'healing',
        value: 28 + (i + 1) * 7 + family * 3,
        effect,
        price: 20 + (i + 1) * 8 + family * 5,
      };
    }),
);

const keyNames: [string[], string[]] = [
  [
    'NIX’ Herkunftsmodul',
    'Unabhängiger Pumpenschlüssel',
    'Archivbeweis des Sammlers',
    'Originalbericht der Redaktion',
    'Freies Fertigungsprotokoll',
    'Rheas Vertragsschlüssel',
    'Ennos Originalindex',
    'Unabhängiger Synchronkern',
    'SERAs Originalprotokoll',
    'Gesicherter Übertragungsplan',
    'Ausfallprotokoll der Freien Frequenz',
    'Offene Verwaltungsklausel',
    'Verlorene Wartungsmarke',
    'Saubere Filterprobe',
    'Tams unbelasteter Pfandschein',
    'Unverändertes Saatgut',
    'Einmaliges Gildenformteil',
    'Vertrag ohne Sponsormark',
    'Ungeöffneter letzter Brief',
    'Unabhängiger Zeitstempel',
    'Ungeschnittenes Gespräch',
    'Name einer entfernten Stimme',
    'Notfallkopie außerhalb des Senders',
    'Kündbarer Schlussvertrag',
  ],
  [
    'NIX’s Origin Module',
    'Independent Pump Key',
    'Collector’s Archive Evidence',
    'Original Newsroom Report',
    'Free Production Protocol',
    'Rhea’s Contract Key',
    'Enno’s Original Index',
    'Independent Synchronisation Core',
    'SERA’s Original Protocol',
    'Secured Transfer Plan',
    'Free Frequency Outage Protocol',
    'Open Administration Clause',
    'Lost Maintenance Badge',
    'Clean Filter Sample',
    'Tam’s Unburdened Pawn Receipt',
    'Unaltered Seed Stock',
    'One-Off Guild Mould',
    'Contract Without a Sponsor Brand',
    'Unopened Last Letter',
    'Independent Timestamp',
    'Unedited Conversation',
    'Name of a Distant Voice',
    'Emergency Copy Outside the Broadcast',
    'Terminable Final Contract',
  ],
];
const keyItems: ItemDef[] = keyNames[0].map((name, i) => ({
  id: `key-${i < 12 ? 'story' : 'optional'}-${String((i % 12) + 1).padStart(2, '0')}`,
  name: t(name, keyNames[1][i]),
  description: t(
    `${i < 12 ? 'Gesicherter Hauptstorybeweis.' : 'Gesicherter optionaler Beweis.'} Kann nicht verkauft, verwertet oder verbraucht werden. Bestätigter Fortschritt bleibt nach einem Fehlversuch erhalten.`,
    `${i < 12 ? 'Secured main-story evidence.' : 'Secured optional evidence.'} Cannot be sold, salvaged or consumed. Confirmed progress remains after a failed attempt.`,
  ),
  kind: 'key',
  rarity: 3,
  floor: (i % 12) + 1,
  icon: (106 + i) % 128,
  stat: 'maxHp',
  value: 0,
  price: 0,
}));

/** 360 gear = 240 ordinary + 72 unique + 48 set pieces; the groups do not overlap. */
export const ITEMS: ItemDef[] = [
  ...regularItems,
  ...uniqueItems,
  ...setItems,
  ...relicItems,
  ...tacticalItems,
  ...supplyItems,
  ...keyItems,
];

const affixGroups: { id: string; name: Text; stat: string; base: number; slots: GearSlot[] }[] = [
  {
    id: 'impact',
    name: t('Überdruck', 'Overpressure'),
    stat: 'damage',
    base: 0.012,
    slots: ['weapon', 'hands'],
  },
  {
    id: 'edge',
    name: t('Scharfe Naht', 'Sharp Seam'),
    stat: 'crit',
    base: 0.008,
    slots: ['weapon', 'hands', 'amulet'],
  },
  {
    id: 'layer',
    name: t('Zweite Lage', 'Second Layer'),
    stat: 'armor',
    base: 1,
    slots: ['head', 'body', 'offhand'],
  },
  {
    id: 'vital',
    name: t('Lebensreserve', 'Life Reserve'),
    stat: 'maxHp',
    base: 4,
    slots: ['body', 'amulet', 'head'],
  },
  {
    id: 'charge',
    name: t('Zusatzladung', 'Extra Charge'),
    stat: 'maxResource',
    base: 3,
    slots: ['offhand', 'head', 'talisman'],
  },
  {
    id: 'run',
    name: t('Freier Schritt', 'Free Step'),
    stat: 'speed',
    base: 0.009,
    slots: ['feet', 'body'],
  },
  {
    id: 'cycle',
    name: t('Kurzer Zyklus', 'Short Cycle'),
    stat: 'cooldown',
    base: 0.009,
    slots: ['talisman', 'hands', 'amulet'],
  },
  {
    id: 'restore',
    name: t('Ruhiger Rücklauf', 'Steady Return'),
    stat: 'regen',
    base: 0.15,
    slots: ['talisman', 'amulet', 'offhand'],
  },
  {
    id: 'clinic',
    name: t('Saubere Erholung', 'Clean Recovery'),
    stat: 'healing',
    base: 0.018,
    slots: ['amulet', 'body', 'talisman'],
  },
  {
    id: 'escape',
    name: t('Sicherer Ausweg', 'Safe Escape'),
    stat: 'dodge',
    base: 0.012,
    slots: ['feet', 'hands'],
  },
  {
    id: 'claim',
    name: t('Gegenseitige Forderung', 'Mutual Claim'),
    stat: 'lifesteal',
    base: 0.004,
    slots: ['weapon', 'amulet'],
  },
  {
    id: 'conduct',
    name: t('Leitfähiger Rand', 'Conductive Edge'),
    stat: 'elemental',
    base: 0.018,
    slots: ['weapon', 'offhand', 'talisman'],
  },
  {
    id: 'pack',
    name: t('Gemeinsame Jagd', 'Shared Hunt'),
    stat: 'nix',
    base: 0.025,
    slots: ['amulet', 'head', 'talisman'],
  },
  {
    id: 'trade',
    name: t('Brauchbarer Rest', 'Useful Remainder'),
    stat: 'gold',
    base: 0.025,
    slots: ['hands', 'talisman', 'feet'],
  },
  {
    id: 'precision',
    name: t('Ruhige Linie', 'Steady Line'),
    stat: 'damage',
    base: 0.01,
    slots: ['offhand', 'head', 'amulet'],
  },
  {
    id: 'home',
    name: t('Dauerhafter Schutz', 'Lasting Protection'),
    stat: 'armor',
    base: 0.8,
    slots: ['feet', 'hands', 'talisman'],
  },
];
const roman = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];
export const AFFIXES: AffixDef[] = affixGroups.flatMap((g) =>
  roman.map((rank, i) => ({
    id: `affix-${g.id}-${i + 1}`,
    name: t(`${g.name.de} ${rank}`, `${g.name.en} ${rank}`),
    stat: g.stat,
    value: Number((g.base * (i + 1)).toFixed(4)),
    slots: g.slots,
  })),
);

export const RECIPES: RecipeDef[] = [
  ...craftUniques.map((s, i) => ({
    id: `recipe-unique-${String(i + 1).padStart(2, '0')}`,
    name: t(s[0], s[1]),
    item: `unique-craft-${String(i + 1).padStart(2, '0')}`,
    cost: 220 + (i + 1) * 95,
    floor: i + 1,
  })),
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `recipe-recovery-${String(i + 1).padStart(2, '0')}`,
    name: t(recoveryNames[0][i], recoveryNames[1][i]),
    item: `consumable-recovery-${String(i + 1).padStart(2, '0')}`,
    cost: 18 + (i + 1) * 6,
    floor: i + 1,
  })),
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `recipe-device-${String(i + 1).padStart(2, '0')}`,
    name: t(relicNames[1][0][i], relicNames[1][1][i]),
    item: `relic-device-${String(i + 1).padStart(2, '0')}`,
    cost: 90 + (i + 1) * 40,
    floor: i + 1,
  })),
];
