import type { RoomKind, RoomPrefab } from '../game/types';
import { FLOORS } from './floors';

const t = (de: string, en: string) => ({ de, en });
const names: [string[], string[]][] = [
  [
    [
      'Bürstengasse',
      'Kabelhof',
      'Sicherheitsprüfung',
      'Stempelstation',
      'Förderbandkreuz',
      'Umkleide',
      'Torsteuerung',
      'Schichtschacht',
      'Buchungsreihe',
      'Zulassungsbüro',
      'Fundgrube',
      'Anlieferung',
      'Quersteg',
      'Oberer Laufweg',
      'Wartungsschleife',
      'Gepäckband',
      'Notstromfolge',
      'Kameraverteiler',
      'Türregister',
      'Stummer Empfang',
      'Verlorene Schicht',
      'Ungeöffnete Aufnahme',
      'Erste-Hilfe-Nische',
      'Wartungsbucht',
      'Prüffeld Q-17',
      'Kabelnest',
      'Einlassarena',
      'Versiegeltes Fach',
    ],
    [
      'Brush Alley',
      'Cable Yard',
      'Security Inspection',
      'Stamping Station',
      'Conveyor Cross',
      'Changing Room',
      'Gate Control',
      'Shift Shaft',
      'Booking Row',
      'Admission Office',
      'Lost Property',
      'Receiving Bay',
      'Crosswalk',
      'Upper Walkway',
      'Maintenance Loop',
      'Baggage Belt',
      'Emergency Sequence',
      'Camera Junction',
      'Door Register',
      'Silent Reception',
      'Lost Shift',
      'Unopened Recording',
      'First-Aid Niche',
      'Maintenance Bay',
      'Q-17 Inspection Field',
      'Cable Nest',
      'Admission Arena',
      'Sealed Compartment',
    ],
  ],
  [
    [
      'Rohrbogen',
      'Rattensteg',
      'Brauner Überlauf',
      'Filtergehäuse',
      'Nasses Fundament',
      'Ventilwarte',
      'Druckschacht',
      'Kupferengpass',
      'Schlammkammer',
      'Rücklauf',
      'Pumpenpodest',
      'Rinnenkreuz',
      'Trockensteg',
      'Unterer Kanal',
      'Leitungsbrücke',
      'Ablaufroute',
      'Dreiventilraum',
      'Trockenschaltung',
      'Kliniksicherung',
      'Rohrpoststelle',
      'Sauberes Versprechen',
      'Nachtwachposten',
      'Kliniknische',
      'Notdusche',
      'Zwillingsventile',
      'Fettfangbecken',
      'Hauptpumpenkammer',
      'Filterlager',
    ],
    [
      'Pipe Elbow',
      'Rat Walkway',
      'Brown Overflow',
      'Filter Casing',
      'Wet Foundation',
      'Valve Watch',
      'Pressure Shaft',
      'Copper Choke',
      'Sludge Chamber',
      'Return Line',
      'Pump Platform',
      'Gutter Cross',
      'Dry Walkway',
      'Lower Channel',
      'Conduit Bridge',
      'Drain Route',
      'Three-Valve Room',
      'Drainage Switch',
      'Clinic Lock',
      'Pneumatic Post',
      'Clean Promise',
      'Night-Watch Post',
      'Clinic Niche',
      'Emergency Shower',
      'Twin Valves',
      'Grease Trap',
      'Main Pump Chamber',
      'Filter Store',
    ],
  ],
  [
    [
      'Stahlchor',
      'Schrotthof',
      'Magnetreihe',
      'Pressengang',
      'Schwarzer Altar',
      'Funkenfenster',
      'Reliquienkammer',
      'Golemfundament',
      'Spulenkuppel',
      'Rostkapelle',
      'Stapelquerung',
      'Metallkanzel',
      'Kettensteg',
      'Schräger Kreuzgang',
      'Pfandroute',
      'Dachlauf',
      'Magnetaltar',
      'Stimmenfolge',
      'Eigentumsregister',
      'Werkzeugpfand',
      'Stumme Zeugen',
      'Auktionspause',
      'Gildennische',
      'Warmes Archiv',
      'Kranschrein',
      'Quittungsgewölbe',
      'Sammlerthron',
      'Unverkaufter Bestand',
    ],
    [
      'Steel Choir',
      'Scrap Yard',
      'Magnet Row',
      'Press Passage',
      'Black Altar',
      'Spark Window',
      'Relic Chamber',
      'Golem Foundation',
      'Coil Dome',
      'Rust Chapel',
      'Stack Crossing',
      'Metal Pulpit',
      'Chain Walkway',
      'Slanted Cloister',
      'Pawn Route',
      'Roof Run',
      'Magnetic Altar',
      'Voice Sequence',
      'Ownership Register',
      'Tool Pledge',
      'Silent Witnesses',
      'Auction Pause',
      'Guild Niche',
      'Warm Archive',
      'Crane Shrine',
      'Receipt Vault',
      'Collector’s Throne',
      'Unsold Stock',
    ],
  ],
  [
    [
      'Tintenbad',
      'Sporensatz',
      'Wurzelgang',
      'Druckbogen',
      'Pilztisch',
      'Käferredaktion',
      'Klebegasse',
      'Falzkammer',
      'Manuskriptwald',
      'Lebende Seite',
      'Satzkasten',
      'Wortbank',
      'Wurzelsteg',
      'Papierlauf',
      'Helle Rinde',
      'Unterer Satzweg',
      'Kulturfolge',
      'Privatversiegelung',
      'Lebende Tür',
      'Zuvs Probe',
      'Ungesendeter Bericht',
      'Keimraum',
      'Redaktionspause',
      'Gärtnernische',
      'Korrekturfeld',
      'Orakelgarten',
      'Myrs Schlagzeile',
      'Viertes Manuskript',
    ],
    [
      'Ink Bath',
      'Spore Edition',
      'Root Passage',
      'Printing Arc',
      'Mushroom Desk',
      'Beetle Newsroom',
      'Glue Alley',
      'Fold Chamber',
      'Manuscript Forest',
      'Living Page',
      'Typecase',
      'Word Bank',
      'Root Walkway',
      'Paper Run',
      'Bright Bark',
      'Lower Type Route',
      'Culture Sequence',
      'Private Seal',
      'Living Door',
      'Zuv’s Sample',
      'Unbroadcast Report',
      'Germination Room',
      'Editorial Break',
      'Gardener’s Niche',
      'Correction Field',
      'Oracle Garden',
      'Myr’s Headline',
      'Fourth Manuscript',
    ],
  ],
  [
    [
      'Aschengang',
      'Schlackengasse',
      'Gussreihe',
      'Kettenwerk',
      'Kühlplatte',
      'Ofenrand',
      'Schmiedefront',
      'Zundersteg',
      'Basaltkreuz',
      'Formtisch',
      'Arbeitsbogen',
      'Abschlaghof',
      'Förderquerung',
      'Kühllauf',
      'Oberes Rostband',
      'Gussumweg',
      'Kaltkreis',
      'Wärmeverteiler',
      'Sichere Formfolge',
      'Gildenhand',
      'Späte Schicht',
      'Serienfehler',
      'Kühlruhe',
      'Wartungsfenster',
      'Schlackenthron',
      'Nachtschichtwerk',
      'Ashs Ofen',
      'Einmalige Form',
    ],
    [
      'Ash Passage',
      'Slag Alley',
      'Casting Row',
      'Chainworks',
      'Cooling Plate',
      'Furnace Edge',
      'Smith Front',
      'Tinder Walk',
      'Basalt Cross',
      'Mould Table',
      'Working Arc',
      'Chipping Yard',
      'Conveyor Crossing',
      'Coolant Run',
      'Upper Grate Belt',
      'Casting Detour',
      'Cold Circuit',
      'Heat Junction',
      'Safe Mould Sequence',
      'Guild Hand',
      'Late Shift',
      'Serial Fault',
      'Cooling Rest',
      'Maintenance Window',
      'Slag Throne',
      'Night-Shift Works',
      'Ash’s Furnace',
      'One-Off Mould',
    ],
  ],
  [
    [
      'Goldrahmen',
      'Siegelgang',
      'Markenpodium',
      'Reklameset',
      'Rittergalerie',
      'Pfandbank',
      'Maskenball',
      'Leuchtprospekt',
      'Vertragsfront',
      'Rabattlinie',
      'Sponsorhof',
      'Urteilssaal',
      'Kamerasteg',
      'Kulissenweg',
      'Hintere Galerie',
      'Goldene Querung',
      'Maskenfolge',
      'Vertragsvergleich',
      'Freier Zugang',
      'Kleingedrucktes',
      'Ungebrandeter Raum',
      'Fairer Einsatz',
      'Stille Garderobe',
      'Vertragsruhe',
      'Inkassoflügel',
      'Grafenkabinett',
      'Rheas Duell',
      'Leere Prämie',
    ],
    [
      'Golden Frame',
      'Seal Passage',
      'Brand Podium',
      'Advertisement Set',
      'Knight Gallery',
      'Pledge Bank',
      'Masked Ball',
      'Glowing Prospectus',
      'Contract Front',
      'Discount Line',
      'Sponsor Yard',
      'Judgment Hall',
      'Camera Walkway',
      'Backstage Route',
      'Rear Gallery',
      'Golden Crossing',
      'Mask Sequence',
      'Contract Comparison',
      'Free Access',
      'Small Print',
      'Unbranded Room',
      'Fair Stake',
      'Quiet Dressing Room',
      'Contract Rest',
      'Collection Wing',
      'Count’s Cabinet',
      'Rhea’s Duel',
      'Empty Prize',
    ],
  ],
  [
    [
      'Frostzeile',
      'Mottenregal',
      'Splitterhalle',
      'Indexfront',
      'Siegelkammer',
      'Kälteschacht',
      'Datenschatten',
      'Blaue Reihe',
      'Registerbrücke',
      'Originalgang',
      'Eisglasbogen',
      'Nummernraum',
      'Quergang',
      'Lichtlauf',
      'Regalumweg',
      'Unteres Register',
      'Originalfolge',
      'Sanftes Auftauen',
      'Private Sperre',
      'Letzter Brief',
      'Vertauschte Nummer',
      'Ennos Fragment',
      'Lesenische',
      'Warme Lampe',
      'Register Null',
      'Notarsiegel',
      'Bibliothekernest',
      'Ungeschnittene Akte',
    ],
    [
      'Frost Aisle',
      'Moth Shelf',
      'Shard Hall',
      'Index Front',
      'Seal Chamber',
      'Cold Shaft',
      'Data Shadow',
      'Blue Row',
      'Register Bridge',
      'Original Passage',
      'Ice-Glass Arc',
      'Number Room',
      'Cross-Aisle',
      'Light Run',
      'Shelf Detour',
      'Lower Register',
      'Original Sequence',
      'Gentle Thaw',
      'Private Lock',
      'Last Letter',
      'Swapped Number',
      'Enno’s Fragment',
      'Reading Niche',
      'Warm Lamp',
      'Register Zero',
      'Notary Seal',
      'Librarian’s Nest',
      'Unedited File',
    ],
  ],
  [
    [
      'Tickgasse',
      'Zahnradplatz',
      'Pendelkorridor',
      'Spinnenwerk',
      'Federhalle',
      'Schienenkreuz',
      'Messingamt',
      'Minutenwinkel',
      'Uhrwerksfront',
      'Cyanfenster',
      'Taktbogen',
      'Bahnwarte',
      'Gleisquerung',
      'Oberer Wohnsteg',
      'Kettenweg',
      'Rückholroute',
      'Freie Taktfolge',
      'Wohnzyklus',
      'Transportwahl',
      'Verspäteter Zug',
      'Eigene Minute',
      'Ungeschriebener Tag',
      'Wohnnische',
      'Gildenpause',
      'Fahrkartenkammer',
      'Pendelturm',
      'Synchronarena',
      'Unabhängiger Zeitstempel',
    ],
    [
      'Tick Alley',
      'Gear Square',
      'Pendulum Corridor',
      'Spider Works',
      'Spring Hall',
      'Rail Cross',
      'Brass Office',
      'Minute Corner',
      'Clockwork Front',
      'Cyan Window',
      'Beat Arc',
      'Rail Watch',
      'Track Crossing',
      'Upper Residential Walk',
      'Chain Route',
      'Return Route',
      'Free Beat Sequence',
      'Residential Cycle',
      'Transport Choice',
      'Late Train',
      'Your Own Minute',
      'Unwritten Day',
      'Home Niche',
      'Guild Break',
      'Ticket Chamber',
      'Pendulum Tower',
      'Synchronisation Arena',
      'Independent Timestamp',
    ],
  ],
  [
    [
      'Echoschnitt',
      'Prismengang',
      'Maskenfeld',
      'Reflexhof',
      'Glasflanke',
      'Linsensuche',
      'Spiegelnetz',
      'Kulissenrand',
      'Publikumsfront',
      'Obsidianbogen',
      'Kamerareihe',
      'Falscher Applaus',
      'Hintere Bühne',
      'Schwarzer Steg',
      'Echter Quergang',
      'Linsenroute',
      'Spiegelfolge',
      'Originalvergleich',
      'Regiezugang',
      'Echte Nachricht',
      'Ungeschnittenes Gespräch',
      'Fremde Rolle',
      'Dunkle Garderobe',
      'Stille Reihe',
      'Stand-In-Set',
      'Splitterbühne',
      'Publikumsarena',
      'Verlorene Fassung',
    ],
    [
      'Echo Cut',
      'Prism Passage',
      'Mask Field',
      'Reflection Yard',
      'Glass Flank',
      'Lens Search',
      'Mirror Network',
      'Backdrop Edge',
      'Audience Front',
      'Obsidian Arc',
      'Camera Row',
      'False Applause',
      'Rear Stage',
      'Black Walkway',
      'Real Cross-Aisle',
      'Lens Route',
      'Mirror Sequence',
      'Original Comparison',
      'Production Access',
      'Genuine Message',
      'Unedited Conversation',
      'Borrowed Role',
      'Dark Dressing Room',
      'Quiet Row',
      'Stand-In Set',
      'Shard Stage',
      'Audience Arena',
      'Lost Edition',
    ],
  ],
  [
    [
      'Nervengang',
      'Rippenfront',
      'Pulsreihe',
      'Kabelbrutnest',
      'Synapsenbogen',
      'Deckungsrippe',
      'Transplantatraum',
      'Signalader',
      'Ivoryknoten',
      'Leitungsbucht',
      'Netzträger',
      'Pulswarte',
      'Rückensteg',
      'Organische Querung',
      'Kabelumweg',
      'Sicherer Rücklauf',
      'Übertragungsfolge',
      'Schmerzkreis',
      'Knotenabgleich',
      'Entfernte Stimme',
      'Stabiler Pfad',
      'Fremder Name',
      'Ruhiger Puls',
      'Versorgungsnische',
      'Knotenarztpraxis',
      'Verschlingerarchiv',
      'Wirbelkammer',
      'Ungezählte Stimme',
    ],
    [
      'Nerve Passage',
      'Rib Front',
      'Pulse Row',
      'Cable Brood Nest',
      'Synapse Arc',
      'Cover Rib',
      'Transplant Room',
      'Signal Vein',
      'Ivory Node',
      'Conduit Bay',
      'Network Support',
      'Pulse Watch',
      'Spine Walkway',
      'Organic Crossing',
      'Cable Detour',
      'Safe Return',
      'Transfer Sequence',
      'Pain Circuit',
      'Node Comparison',
      'Distant Voice',
      'Stable Path',
      'Another Name',
      'Quiet Pulse',
      'Provision Niche',
      'Node Surgeon’s Practice',
      'Devourer Archive',
      'Spine Chamber',
      'Uncounted Voice',
    ],
  ],
  [
    [
      'Ausfallfront',
      'Geisterinsel',
      'Antennenweg',
      'Schweigesaal',
      'Leuchtspur',
      'Signalband',
      'Blinder Kegel',
      'Störzentrum',
      'Cyanfeld',
      'Nullgang',
      'Sendeschrank',
      'Echowinkel',
      'Lichtquerung',
      'Dunkler Außenweg',
      'Stiller Steg',
      'Sichtlinienroute',
      'Freie Frequenz',
      'Ausnahmeprüfung',
      'Inselverbindung',
      'Für später',
      'Ungesendete Antwort',
      'Eigenes Signal',
      'Leichte Stille',
      'Warmlichtnische',
      'Antennenthron',
      'Rufkammer',
      'Stille Arena',
      'Notfallarchiv',
    ],
    [
      'Outage Front',
      'Ghost Island',
      'Antenna Route',
      'Silent Hall',
      'Glowing Trail',
      'Signal Band',
      'Blind Cone',
      'Jamming Centre',
      'Cyan Field',
      'Null Passage',
      'Broadcast Cabinet',
      'Echo Corner',
      'Light Crossing',
      'Dark Outer Route',
      'Quiet Walkway',
      'Sightline Route',
      'Free Frequency',
      'Exception Audit',
      'Island Connection',
      'For Later',
      'Unbroadcast Answer',
      'Your Own Signal',
      'Gentle Silence',
      'Warm-Light Niche',
      'Antenna Throne',
      'Call Chamber',
      'Silence Arena',
      'Emergency Archive',
    ],
  ],
  [
    [
      'Protokollfront',
      'Splitterkern',
      'Regieschatten',
      'Archivstütze',
      'Befehlsgang',
      'Übertragungsbogen',
      'Lizenzfeld',
      'Falterregie',
      'Rote Linie',
      'Weißer Saal',
      'Konsolenreihe',
      'Letzte Wache',
      'Regiequerung',
      'Schwarzer Außensteg',
      'Freier Leitweg',
      'Zusatzextraktion',
      'Offene Verwaltung',
      'Letzter Ausweg',
      'Aufhebungsklausel',
      'Vor laufender Kamera',
      'Ein Versprechen weniger',
      'Nach dem Abspann',
      'Freie Garderobe',
      'Erster Morgen',
      'Ratskammer',
      'Letzter Auftritt',
      'Veyls Konsole',
      'Unverkauftes Morgen',
    ],
    [
      'Protocol Front',
      'Shard Core',
      'Production Shadow',
      'Archive Support',
      'Command Passage',
      'Transfer Arc',
      'Licence Field',
      'Moth Production',
      'Red Line',
      'White Hall',
      'Console Row',
      'Final Guard',
      'Production Crossing',
      'Black Outer Walk',
      'Free Conduit',
      'Extra Extraction',
      'Open Administration',
      'Last Exit',
      'Repeal Clause',
      'On Camera',
      'One Less Promise',
      'After the Credits',
      'Free Dressing Room',
      'First Morning',
      'Council Chamber',
      'Final Performance',
      'Veyl’s Console',
      'Unsold Tomorrow',
    ],
  ],
];

const kinds: RoomKind[] = [
  ...Array<RoomKind>(16).fill('combat'),
  'puzzle',
  'puzzle',
  'puzzle',
  'event',
  'event',
  'event',
  'rest',
  'rest',
  'guardian',
  'hunt',
  'boss',
  'treasure',
];

/** Layout 0–11 is combat, 12–15 traversal, 16–18 puzzle, 19–21 event,
 * 22–23 rest, 24 guardian, 25 optional hunt, 26 main boss, 27 treasure. */
export const ROOM_PREFABS: RoomPrefab[] = names.flatMap((pair, n) =>
  pair[0].map((name, i) => ({
    id: `f${String(n + 1).padStart(2, '0')}-room-${String(i + 1).padStart(2, '0')}`,
    floor: n + 1,
    kind: kinds[i],
    layout: i,
    name: t(name, pair[1][i]),
  })),
);

/** Curated formations refer to indexes in each floor's authored bestiary.
 * Singles introduce a role; mixed groups pair shield, flank and ranged pressure. */
const formations: number[][] = [
  [0, 0],
  [1, 1],
  [2, 2],
  [3, 0],
  [4, 4, 4],
  [5, 0],
  [6, 1],
  [7, 2],
  [3, 7, 4],
  [6, 2, 5],
  [1, 4, 7],
  [0, 2, 6],
  [3, 3, 7],
  [2, 2, 4, 4],
  [5, 6, 1, 7],
  [0, 0, 4, 7],
  [3, 2, 4, 5],
  [6, 7, 1, 2],
  [0, 5, 4, 4, 2],
  [3, 6, 7, 1, 5],
];
export const ENCOUNTERS: { id: string; floor: number; mobs: string[] }[] = FLOORS.flatMap((f) =>
  formations.map((pattern, i) => ({
    id: `f${String(f.index).padStart(2, '0')}-encounter-${String(i + 1).padStart(2, '0')}`,
    floor: f.index,
    mobs: pattern.map((index) => f.mobs[index].id),
  })),
);
